using Godot;
using Godot.Collections;
using System;

[GlobalClass]
[Tool]
public partial class SettingsUIController : Node
{
    /// <summary>
    /// The button to be pressed to save the settings.
    /// </summary>
	[Export]
	public Button SaveButton { get; set; }

    /// <summary>
    /// The button to be pressed to hide the UI.
    /// </summary>
	[Export]
	public Button CancelButton { get; set; }

    /// <summary>
    /// The button to reset settings to defaults.
    /// </summary>
	[Export]
	public Button ResetButton { get; set; }

    /// <summary>
    /// The Array of all controls. This property is auto generated by <see cref="SettingsGenerator"/>.
    /// </summary>
	[Export]
	public Array<Control> SettingsControls { get; set; }

    /// <summary>
    /// Control that is the root of the settings UI.
    /// </summary>
    [Export]
    public Control RootControl { get; set; }

    /// <summary>
    /// Called when the <see cref="CancelButton"/> is pressed.
    /// </summary>
    public event Action OnClosePressed;

    /// <summary>
    /// Called when a save is completed with no validation issues.
    /// </summary>
    public event Action OnSaveCompleted;

	public override void _EnterTree()
	{
		base._EnterTree();
        SaveButton.Pressed += Save_Pressed;
        ResetButton.Pressed += ResetButton_Pressed;
        CancelButton.Pressed += CancelButton_Pressed;
        RootControl.VisibilityChanged += RootControl_VisibilityChanged;
	}

    private void RootControl_VisibilityChanged()
    {
        if (!RootControl.IsVisibleInTree())
        {
            Save();
        }
    }

    private void CancelButton_Pressed()
    {
        Load();
        OnClosePressed?.Invoke();
        RootControl.Visible = false;
    }

    public override void _Ready()
    {
        base._Ready();
        if (Engine.IsEditorHint())
        {
            return;
        }
        Load();
    }

    private void ResetButton_Pressed()
    {
		Reset();
    }

    /// <summary>
    /// Loads all Settings controls in <see cref="SettingsControls"/> by calling the <see cref="ISettingsControl.Load()"/> method.
    /// </summary>
    public void Load()
    {
        //Log.Print("Load");
        foreach (Control c in SettingsControls)
        {
            //Log.Print("Load " + c.Name);
            if (c is not ISettingsControl ctrl)
            {
                Log.PrintErr($"Control {c.GetPath()} is not a {nameof(ISettingsControl)}, it has been ignored.");
            }
            else
            {
                try
                {
                    ctrl.Load();
                    ctrl.OnPreValidate();
                    if (!ctrl.Validate(out string value))
                    {
                        Log.PrintErr($"Setting {ctrl.Setting?.Name} has been reset to the default value because it failed to validate.");
                        //ctrl.OnValidateFailed(value);
                        ctrl.Reset();
                    }
                }
                catch (Exception ex)
                {
                    Log.PrintErr($"Load failed! Control: {c.Name}, Error: {ex.ToString()}");
                }
            }
        }
    }

    public void Refresh()
	{
        foreach (Control c in SettingsControls)
        {
            if (c is not ISettingsControl ctrl)
            {
                Log.PrintErr($"Control {c.GetPath()} is not a {nameof(ISettingsControl)}, it has been ignored.");
            }
            else
            {
                ctrl.Load();
                ctrl.OnPreValidate();
                if (!ctrl.Validate(out string value))
                {
                    Log.PrintErr($"Setting {ctrl?.Setting?.Name} has been reset to the default value because it failed to validate.");
                    //ctrl.OnValidateFailed(value);
                    ctrl.Reset();
                }
            }
        }
    }

    /// <summary>
    /// Resets all controls in <see cref="SettingsControls"/> by calling <see cref="ISettingsControl.Reset"/>.
    /// </summary>
	public void Reset()
	{
        foreach (Control c in SettingsControls)
        {
            if (c is not ISettingsControl ctrl)
            {
                Log.PrintErr($"Control {c.GetPath()} is not a {nameof(ISettingsControl)}, it has been ignored.");
            }
            else
            {
                ctrl.Reset();
				ctrl.Load();
            }
        }
    }

    /// <summary>
    /// Saves all Settings in <see cref="SettingsControls"/> by calling <see cref="ISettingsControl.Save"/>. If the validation fails, settings are <b>not</b> written to disk.
    /// </summary>
	public void Save()
	{
        try
        {
            bool validateError = false;
            foreach (Control c in SettingsControls)
            {
                if (c is not ISettingsControl ctrl)
                {
                    Log.PrintErr($"Control {c.GetPath()} is not a {nameof(ISettingsControl)}, it has been ignored.");
                }
                else
                {
                    ctrl.OnPreValidate();
                    if (!ctrl.Validate(out string value))
                    {
                        Log.PrintErr($"Setting {ctrl?.Setting?.Name} has been reset to the default value because it failed to validate.");
                        //ctrl.Reset();
                        ctrl.OnValidateFailed(value);
                        validateError = true;
                        continue;
                    }
                    ctrl.Save();
                }
            }
            if (!validateError)
            {
                Settings.Modified = true;
                // Settings.WriteUserSettings();
                // MenuManager.Instance?.WriteSettings();
                OnSaveCompleted?.Invoke();
            }
        }
        catch (Exception ex)
        {
            Log.PrintErr("Failed to save settings. Error: " + ex.ToString());
        }
    }

	private void Save_Pressed()
	{
        Save();
	}
}
