// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;
using Object = Godot.GodotObject;

namespace GDExtensionBindgen;

public class DiscordRPC
{
	// Engine object used for calling engine methods
	protected Object _object;

	public DiscordRPC() : this(NativeName)
	{
	}
	protected DiscordRPC(StringName @class) : this(ClassDB.Instantiate(@class))
	{
	}
	protected DiscordRPC(Variant variant) : this((Object) variant)
	{
	}
	protected DiscordRPC([NotNull] Object @object)
	{
		_object = @object;
	}

	public static implicit operator Object(DiscordRPC self) => self?._object;
	public static implicit operator Variant(DiscordRPC self) => self?._object;
	public static explicit operator DiscordRPC(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public class PropertyName : Object.PropertyName
	{
		public static readonly StringName AppId = "app_id";
		public static readonly StringName State = "state";
		public static readonly StringName Details = "details";
		public static readonly StringName LargeImage = "large_image";
		public static readonly StringName LargeImageText = "large_image_text";
		public static readonly StringName SmallImage = "small_image";
		public static readonly StringName SmallImageText = "small_image_text";
		public static readonly StringName StartTimestamp = "start_timestamp";
		public static readonly StringName EndTimestamp = "end_timestamp";
		public static readonly StringName PartyId = "party_id";
		public static readonly StringName CurrentPartySize = "current_party_size";
		public static readonly StringName MaxPartySize = "max_party_size";
		public static readonly StringName MatchSecret = "match_secret";
		public static readonly StringName JoinSecret = "join_secret";
		public static readonly StringName SpectateSecret = "spectate_secret";
		public static readonly StringName Instanced = "instanced";
		public static readonly StringName IsPublicParty = "is_public_party";
	}

	public class MethodName : Object.MethodName
	{
		public static readonly StringName GetAppId = "get_app_id";
		public static readonly StringName SetAppId = "set_app_id";
		public static readonly StringName GetState = "get_state";
		public static readonly StringName SetState = "set_state";
		public static readonly StringName GetDetails = "get_details";
		public static readonly StringName SetDetails = "set_details";
		public static readonly StringName GetLargeImage = "get_large_image";
		public static readonly StringName SetLargeImage = "set_large_image";
		public static readonly StringName GetLargeImageText = "get_large_image_text";
		public static readonly StringName SetLargeImageText = "set_large_image_text";
		public static readonly StringName GetSmallImage = "get_small_image";
		public static readonly StringName SetSmallImage = "set_small_image";
		public static readonly StringName GetSmallImageText = "get_small_image_text";
		public static readonly StringName SetSmallImageText = "set_small_image_text";
		public static readonly StringName GetStartTimestamp = "get_start_timestamp";
		public static readonly StringName SetStartTimestamp = "set_start_timestamp";
		public static readonly StringName GetEndTimestamp = "get_end_timestamp";
		public static readonly StringName SetEndTimestamp = "set_end_timestamp";
		public static readonly StringName GetPartyId = "get_party_id";
		public static readonly StringName SetPartyId = "set_party_id";
		public static readonly StringName GetCurrentPartySize = "get_current_party_size";
		public static readonly StringName SetCurrentPartySize = "set_current_party_size";
		public static readonly StringName GetMaxPartySize = "get_max_party_size";
		public static readonly StringName SetMaxPartySize = "set_max_party_size";
		public static readonly StringName GetMatchSecret = "get_match_secret";
		public static readonly StringName SetMatchSecret = "set_match_secret";
		public static readonly StringName GetJoinSecret = "get_join_secret";
		public static readonly StringName SetJoinSecret = "set_join_secret";
		public static readonly StringName GetSpectateSecret = "get_spectate_secret";
		public static readonly StringName SetSpectateSecret = "set_spectate_secret";
		public static readonly StringName GetInstanced = "get_instanced";
		public static readonly StringName SetInstanced = "set_instanced";
		public static readonly StringName GetIsPublicParty = "get_is_public_party";
		public static readonly StringName SetIsPublicParty = "set_is_public_party";
		public static readonly StringName Debug = "debug";
		public static readonly StringName RunCallbacks = "run_callbacks";
		public static readonly StringName Refresh = "refresh";
		public static readonly StringName Clear = "clear";
		public static readonly StringName Unclear = "unclear";
		public static readonly StringName RegisterCommand = "register_command";
		public static readonly StringName RegisterSteam = "register_steam";
		public static readonly StringName AcceptJoinRequest = "accept_join_request";
		public static readonly StringName SendInvite = "send_invite";
		public static readonly StringName AcceptInvite = "accept_invite";
		public static readonly StringName GetCurrentUser = "get_current_user";
		public static readonly StringName GetAllRelationships = "get_all_relationships";
		public static readonly StringName GetIsOverlayEnabled = "get_is_overlay_enabled";
		public static readonly StringName GetIsOverlayLocked = "get_is_overlay_locked";
		public static readonly StringName OpenInviteOverlay = "open_invite_overlay";
		public static readonly StringName OpenServerInviteOverlay = "open_server_invite_overlay";
		public static readonly StringName OpenVoiceSettings = "open_voice_settings";
		public static readonly StringName GetIsDiscordWorking = "get_is_discord_working";
		public static readonly StringName GetResultInt = "get_result_int";
	}

	public class SignalName : Object.SignalName
	{
		public static readonly StringName ActivityJoin = "activity_join";
		public static readonly StringName ActivitySpectate = "activity_spectate";
		public static readonly StringName ActivityJoinRequest = "activity_join_request";
		public static readonly StringName UpdatedRelationship = "updated_relationship";
		public static readonly StringName OverlayToggle = "overlay_toggle";
		public static readonly StringName RelationshipsInit = "relationships_init";
	}

	private static readonly StringName NativeName = "DiscordRPC";

	#region Properties

	public int AppId
	{
		get => (int)_object.Get(PropertyName.AppId);
		set => _object.Set(PropertyName.AppId, value);
	}

	public string State
	{
		get => (string)_object.Get(PropertyName.State);
		set => _object.Set(PropertyName.State, value);
	}

	public string Details
	{
		get => (string)_object.Get(PropertyName.Details);
		set => _object.Set(PropertyName.Details, value);
	}

	public string LargeImage
	{
		get => (string)_object.Get(PropertyName.LargeImage);
		set => _object.Set(PropertyName.LargeImage, value);
	}

	public string LargeImageText
	{
		get => (string)_object.Get(PropertyName.LargeImageText);
		set => _object.Set(PropertyName.LargeImageText, value);
	}

	public string SmallImage
	{
		get => (string)_object.Get(PropertyName.SmallImage);
		set => _object.Set(PropertyName.SmallImage, value);
	}

	public string SmallImageText
	{
		get => (string)_object.Get(PropertyName.SmallImageText);
		set => _object.Set(PropertyName.SmallImageText, value);
	}

	public int StartTimestamp
	{
		get => (int)_object.Get(PropertyName.StartTimestamp);
		set => _object.Set(PropertyName.StartTimestamp, value);
	}

	public int EndTimestamp
	{
		get => (int)_object.Get(PropertyName.EndTimestamp);
		set => _object.Set(PropertyName.EndTimestamp, value);
	}

	public string PartyId
	{
		get => (string)_object.Get(PropertyName.PartyId);
		set => _object.Set(PropertyName.PartyId, value);
	}

	public int CurrentPartySize
	{
		get => (int)_object.Get(PropertyName.CurrentPartySize);
		set => _object.Set(PropertyName.CurrentPartySize, value);
	}

	public int MaxPartySize
	{
		get => (int)_object.Get(PropertyName.MaxPartySize);
		set => _object.Set(PropertyName.MaxPartySize, value);
	}

	public string MatchSecret
	{
		get => (string)_object.Get(PropertyName.MatchSecret);
		set => _object.Set(PropertyName.MatchSecret, value);
	}

	public string JoinSecret
	{
		get => (string)_object.Get(PropertyName.JoinSecret);
		set => _object.Set(PropertyName.JoinSecret, value);
	}

	public string SpectateSecret
	{
		get => (string)_object.Get(PropertyName.SpectateSecret);
		set => _object.Set(PropertyName.SpectateSecret, value);
	}

	public bool Instanced
	{
		get => (bool)_object.Get(PropertyName.Instanced);
		set => _object.Set(PropertyName.Instanced, value);
	}

	public bool IsPublicParty
	{
		get => (bool)_object.Get(PropertyName.IsPublicParty);
		set => _object.Set(PropertyName.IsPublicParty, value);
	}

	#endregion

	#region Methods

	public int GetAppId()
	{
		return (int)_object.Call(MethodName.GetAppId);
	}

	public void SetAppId(int @Variant::INT)
	{
		_object.Call(MethodName.SetAppId, @Variant::INT);
	}

	public string GetState()
	{
		return (string)_object.Call(MethodName.GetState);
	}

	public void SetState(string @Variant::STRING)
	{
		_object.Call(MethodName.SetState, @Variant::STRING);
	}

	public string GetDetails()
	{
		return (string)_object.Call(MethodName.GetDetails);
	}

	public void SetDetails(string @Variant::STRING)
	{
		_object.Call(MethodName.SetDetails, @Variant::STRING);
	}

	public string GetLargeImage()
	{
		return (string)_object.Call(MethodName.GetLargeImage);
	}

	public void SetLargeImage(string @Variant::STRING)
	{
		_object.Call(MethodName.SetLargeImage, @Variant::STRING);
	}

	public string GetLargeImageText()
	{
		return (string)_object.Call(MethodName.GetLargeImageText);
	}

	public void SetLargeImageText(string @Variant::STRING)
	{
		_object.Call(MethodName.SetLargeImageText, @Variant::STRING);
	}

	public string GetSmallImage()
	{
		return (string)_object.Call(MethodName.GetSmallImage);
	}

	public void SetSmallImage(string @Variant::STRING)
	{
		_object.Call(MethodName.SetSmallImage, @Variant::STRING);
	}

	public string GetSmallImageText()
	{
		return (string)_object.Call(MethodName.GetSmallImageText);
	}

	public void SetSmallImageText(string @Variant::STRING)
	{
		_object.Call(MethodName.SetSmallImageText, @Variant::STRING);
	}

	public int GetStartTimestamp()
	{
		return (int)_object.Call(MethodName.GetStartTimestamp);
	}

	public void SetStartTimestamp(int @Variant::INT)
	{
		_object.Call(MethodName.SetStartTimestamp, @Variant::INT);
	}

	public int GetEndTimestamp()
	{
		return (int)_object.Call(MethodName.GetEndTimestamp);
	}

	public void SetEndTimestamp(int @Variant::INT)
	{
		_object.Call(MethodName.SetEndTimestamp, @Variant::INT);
	}

	public string GetPartyId()
	{
		return (string)_object.Call(MethodName.GetPartyId);
	}

	public void SetPartyId(string @Variant::STRING)
	{
		_object.Call(MethodName.SetPartyId, @Variant::STRING);
	}

	public int GetCurrentPartySize()
	{
		return (int)_object.Call(MethodName.GetCurrentPartySize);
	}

	public void SetCurrentPartySize(int @Variant::INT)
	{
		_object.Call(MethodName.SetCurrentPartySize, @Variant::INT);
	}

	public int GetMaxPartySize()
	{
		return (int)_object.Call(MethodName.GetMaxPartySize);
	}

	public void SetMaxPartySize(int @Variant::INT)
	{
		_object.Call(MethodName.SetMaxPartySize, @Variant::INT);
	}

	public string GetMatchSecret()
	{
		return (string)_object.Call(MethodName.GetMatchSecret);
	}

	public void SetMatchSecret(string @Variant::STRING)
	{
		_object.Call(MethodName.SetMatchSecret, @Variant::STRING);
	}

	public string GetJoinSecret()
	{
		return (string)_object.Call(MethodName.GetJoinSecret);
	}

	public void SetJoinSecret(string @Variant::STRING)
	{
		_object.Call(MethodName.SetJoinSecret, @Variant::STRING);
	}

	public string GetSpectateSecret()
	{
		return (string)_object.Call(MethodName.GetSpectateSecret);
	}

	public void SetSpectateSecret(string @Variant::STRING)
	{
		_object.Call(MethodName.SetSpectateSecret, @Variant::STRING);
	}

	public bool GetInstanced()
	{
		return (bool)_object.Call(MethodName.GetInstanced);
	}

	public void SetInstanced(bool @Variant::BOOL)
	{
		_object.Call(MethodName.SetInstanced, @Variant::BOOL);
	}

	public bool GetIsPublicParty()
	{
		return (bool)_object.Call(MethodName.GetIsPublicParty);
	}

	public void SetIsPublicParty(bool @Variant::BOOL)
	{
		_object.Call(MethodName.SetIsPublicParty, @Variant::BOOL);
	}

	public void Debug()
	{
		_object.Call(MethodName.Debug);
	}

	public void RunCallbacks()
	{
		_object.Call(MethodName.RunCallbacks);
	}

	public void Refresh()
	{
		_object.Call(MethodName.Refresh);
	}

	public void Clear(bool @reset_values = false)
	{
		_object.Call(MethodName.Clear, @reset_values);
	}

	public void Unclear()
	{
		_object.Call(MethodName.Unclear);
	}

	public void RegisterCommand(string @command)
	{
		_object.Call(MethodName.RegisterCommand, @command);
	}

	public void RegisterSteam(int @steam_id)
	{
		_object.Call(MethodName.RegisterSteam, @steam_id);
	}

	public void AcceptJoinRequest(int @user_id)
	{
		_object.Call(MethodName.AcceptJoinRequest, @user_id);
	}

	public void SendInvite(int @user_id, bool @is_spectate, string @message_content)
	{
		_object.Call(MethodName.SendInvite, @user_id, @is_spectate, @message_content);
	}

	public void AcceptInvite(int @user_id)
	{
		_object.Call(MethodName.AcceptInvite, @user_id);
	}

	public Godot.Collections.Dictionary GetCurrentUser()
	{
		return (Godot.Collections.Dictionary)_object.Call(MethodName.GetCurrentUser);
	}

	public Godot.Collections.Array GetAllRelationships()
	{
		return (Godot.Collections.Array)_object.Call(MethodName.GetAllRelationships);
	}

	public bool GetIsOverlayEnabled()
	{
		return (bool)_object.Call(MethodName.GetIsOverlayEnabled);
	}

	public bool GetIsOverlayLocked()
	{
		return (bool)_object.Call(MethodName.GetIsOverlayLocked);
	}

	public void OpenInviteOverlay(bool @is_spectate)
	{
		_object.Call(MethodName.OpenInviteOverlay, @is_spectate);
	}

	public void OpenServerInviteOverlay(string @invite_code)
	{
		_object.Call(MethodName.OpenServerInviteOverlay, @invite_code);
	}

	public void OpenVoiceSettings()
	{
		_object.Call(MethodName.OpenVoiceSettings);
	}

	public bool GetIsDiscordWorking()
	{
		return (bool)_object.Call(MethodName.GetIsDiscordWorking);
	}

	public int GetResultInt()
	{
		return (int)_object.Call(MethodName.GetResultInt);
	}

	#endregion

	#region Inherited Methods

	public void Free()
	{
		_object.Free();
	}

	public string GetClass()
	{
		return _object.GetClass();
	}

	public bool IsClass(string @class)
	{
		return _object.IsClass(@class);
	}

	public void Set(Godot.StringName @property, Variant @value)
	{
		_object.Set(@property, @value);
	}

	public Variant Get(Godot.StringName @property)
	{
		return _object.Get(@property);
	}

	public void SetIndexed(Godot.NodePath @property_path, Variant @value)
	{
		_object.SetIndexed(@property_path, @value);
	}

	public Variant GetIndexed(Godot.NodePath @property_path)
	{
		return _object.GetIndexed(@property_path);
	}

	public Godot.Collections.Array<Godot.Collections.Dictionary> GetPropertyList()
	{
		return _object.GetPropertyList();
	}

	public Godot.Collections.Array<Godot.Collections.Dictionary> GetMethodList()
	{
		return _object.GetMethodList();
	}

	public bool PropertyCanRevert(Godot.StringName @property)
	{
		return _object.PropertyCanRevert(@property);
	}

	public Variant PropertyGetRevert(Godot.StringName @property)
	{
		return _object.PropertyGetRevert(@property);
	}

	public void Notification(int @what, bool @reversed = false)
	{
		_object.Notification(@what, @reversed);
	}

	public override string ToString()
	{
		return _object.ToString();
	}

	public ulong GetInstanceId()
	{
		return _object.GetInstanceId();
	}

	public void SetScript(Variant @script)
	{
		_object.SetScript(@script);
	}

	public Variant GetScript()
	{
		return _object.GetScript();
	}

	public void SetMeta(Godot.StringName @name, Variant @value)
	{
		_object.SetMeta(@name, @value);
	}

	public void RemoveMeta(Godot.StringName @name)
	{
		_object.RemoveMeta(@name);
	}

	public Variant GetMeta(Godot.StringName @name, Variant @default = default)
	{
		return _object.GetMeta(@name, @default);
	}

	public bool HasMeta(Godot.StringName @name)
	{
		return _object.HasMeta(@name);
	}

	public Godot.Collections.Array<StringName> GetMetaList()
	{
		return _object.GetMetaList();
	}

	public void AddUserSignal(string @signal, Godot.Collections.Array @arguments = null)
	{
		@arguments ??= new();
		_object.AddUserSignal(@signal, @arguments);
	}

	public bool HasUserSignal(Godot.StringName @signal)
	{
		return _object.HasUserSignal(@signal);
	}

	public void RemoveUserSignal(Godot.StringName @signal)
	{
		_object.RemoveUserSignal(@signal);
	}

	public Godot.Error EmitSignal(Godot.StringName @signal, params Variant[] varargs)
	{
		return _object.EmitSignal(@signal, varargs);
	}

	public Variant Call(Godot.StringName @method, params Variant[] varargs)
	{
		return _object.Call(@method, varargs);
	}

	public Variant CallDeferred(Godot.StringName @method, params Variant[] varargs)
	{
		return _object.CallDeferred(@method, varargs);
	}

	public void SetDeferred(Godot.StringName @property, Variant @value)
	{
		_object.SetDeferred(@property, @value);
	}

	public Variant Callv(Godot.StringName @method, Godot.Collections.Array @arg_array)
	{
		return _object.Callv(@method, @arg_array);
	}

	public bool HasMethod(Godot.StringName @method)
	{
		return _object.HasMethod(@method);
	}

	public int GetMethodArgumentCount(Godot.StringName @method)
	{
		return _object.GetMethodArgumentCount(@method);
	}

	public bool HasSignal(Godot.StringName @signal)
	{
		return _object.HasSignal(@signal);
	}

	public Godot.Collections.Array<Godot.Collections.Dictionary> GetSignalList()
	{
		return _object.GetSignalList();
	}

	public Godot.Collections.Array<Godot.Collections.Dictionary> GetSignalConnectionList(Godot.StringName @signal)
	{
		return _object.GetSignalConnectionList(@signal);
	}

	public Godot.Collections.Array<Godot.Collections.Dictionary> GetIncomingConnections()
	{
		return _object.GetIncomingConnections();
	}

	public Godot.Error Connect(Godot.StringName @signal, Godot.Callable @callable, uint @flags = (uint)0)
	{
		return _object.Connect(@signal, @callable, @flags);
	}

	public void Disconnect(Godot.StringName @signal, Godot.Callable @callable)
	{
		_object.Disconnect(@signal, @callable);
	}

	public bool IsConnected(Godot.StringName @signal, Godot.Callable @callable)
	{
		return _object.IsConnected(@signal, @callable);
	}

	public bool HasConnections(Godot.StringName @signal)
	{
		return _object.HasConnections(@signal);
	}

	public void SetBlockSignals(bool @enable)
	{
		_object.SetBlockSignals(@enable);
	}

	public bool IsBlockingSignals()
	{
		return _object.IsBlockingSignals();
	}

	public void NotifyPropertyListChanged()
	{
		_object.NotifyPropertyListChanged();
	}

	public void SetMessageTranslation(bool @enable)
	{
		_object.SetMessageTranslation(@enable);
	}

	public bool CanTranslateMessages()
	{
		return _object.CanTranslateMessages();
	}

	public string Tr(Godot.StringName @message, Godot.StringName @context = null)
	{
		@context ??= "";
		return _object.Tr(@message, @context);
	}

	public string TrN(Godot.StringName @message, Godot.StringName @plural_message, int @n, Godot.StringName @context = null)
	{
		@context ??= "";
		return _object.TrN(@message, @plural_message, @n, @context);
	}

	public Godot.StringName GetTranslationDomain()
	{
		return _object.GetTranslationDomain();
	}

	public void SetTranslationDomain(Godot.StringName @domain)
	{
		_object.SetTranslationDomain(@domain);
	}

	public bool IsQueuedForDeletion()
	{
		return _object.IsQueuedForDeletion();
	}

	public void CancelFree()
	{
		_object.CancelFree();
	}

	#endregion

	#region Signals

	public event Action<string> ActivityJoinEvent
	{
		add
		{
			Connect(SignalName.ActivityJoin, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.ActivityJoin, Callable.From(value));
		}
	}

	public event Action<string> ActivitySpectateEvent
	{
		add
		{
			Connect(SignalName.ActivitySpectate, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.ActivitySpectate, Callable.From(value));
		}
	}

	public event Action<Godot.Collections.Dictionary> ActivityJoinRequestEvent
	{
		add
		{
			Connect(SignalName.ActivityJoinRequest, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.ActivityJoinRequest, Callable.From(value));
		}
	}

	public event Action<Godot.Collections.Dictionary> UpdatedRelationshipEvent
	{
		add
		{
			Connect(SignalName.UpdatedRelationship, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.UpdatedRelationship, Callable.From(value));
		}
	}

	public event Action<bool> OverlayToggleEvent
	{
		add
		{
			Connect(SignalName.OverlayToggle, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.OverlayToggle, Callable.From(value));
		}
	}

	public event Action RelationshipsInitEvent
	{
		add
		{
			Connect(SignalName.RelationshipsInit, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.RelationshipsInit, Callable.From(value));
		}
	}

	#endregion

	#region Inherited Signals

	public event Action ScriptChangedEvent
	{
		add
		{
			Connect(SignalName.ScriptChanged, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.ScriptChanged, Callable.From(value));
		}
	}

	public event Action PropertyListChangedEvent
	{
		add
		{
			Connect(SignalName.PropertyListChanged, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.PropertyListChanged, Callable.From(value));
		}
	}

	#endregion
}
