// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;
using Object = Godot.GodotObject;

namespace GDExtensionBindgen;

public class GodotIKEffector
{
	// Engine object used for calling engine methods
	protected Node3D _object;

	public GodotIKEffector() : this(NativeName)
	{
	}
	protected GodotIKEffector(StringName @class) : this(ClassDB.Instantiate(@class))
	{
	}
	protected GodotIKEffector(Variant variant) : this((Node3D) variant)
	{
	}
	protected GodotIKEffector([NotNull] Node3D @object)
	{
		_object = @object;
	}

	public static implicit operator Node3D(GodotIKEffector self) => self?._object;
	public static implicit operator Variant(GodotIKEffector self) => self?._object;
	public static explicit operator GodotIKEffector(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public class PropertyName : Node3D.PropertyName
	{
		public static readonly StringName BoneIdx = "bone_idx";
		public static readonly StringName ChainLength = "chain_length";
		public static readonly StringName TransformMode = "transform_mode";
		public static readonly StringName Active = "active";
	}

	public class MethodName : Node3D.MethodName
	{
		public static readonly StringName SetBoneIdx = "set_bone_idx";
		public static readonly StringName GetBoneIdx = "get_bone_idx";
		public static readonly StringName SetChainLength = "set_chain_length";
		public static readonly StringName GetChainLength = "get_chain_length";
		public static readonly StringName SetTransformMode = "set_transform_mode";
		public static readonly StringName GetTransformMode = "get_transform_mode";
		public static readonly StringName SetActive = "set_active";
		public static readonly StringName IsActive = "is_active";
		public static readonly StringName GetSkeleton = "get_skeleton";
		public static readonly StringName GetIkController = "get_ik_controller";
	}

	public class SignalName : Node3D.SignalName
	{
		public static readonly StringName BoneIdxChanged = "bone_idx_changed";
		public static readonly StringName ChainLengthChanged = "chain_length_changed";
	}

	private static readonly StringName NativeName = "GodotIKEffector";

	#region Enums

	public enum TransformModeEnum : long
	{
		PositionOnly = 0L,
		PreserveRotation = 1L,
		StraightenChain = 2L,
		FullTransform = 3L,
	}

	#endregion

	#region Properties

	public int BoneIdx
	{
		get => (int)_object.Get(PropertyName.BoneIdx);
		set => _object.Set(PropertyName.BoneIdx, value);
	}

	public int ChainLength
	{
		get => (int)_object.Get(PropertyName.ChainLength);
		set => _object.Set(PropertyName.ChainLength, value);
	}

	public int TransformMode
	{
		get => (int)_object.Get(PropertyName.TransformMode);
		set => _object.Set(PropertyName.TransformMode, value);
	}

	public bool Active
	{
		get => (bool)_object.Get(PropertyName.Active);
		set => _object.Set(PropertyName.Active, value);
	}

	#endregion

	#region Inherited Properties

	public Godot.Transform3D Transform
	{
		get => _object.Transform;
		set => _object.Transform = value;
	}

	public Godot.Transform3D GlobalTransform
	{
		get => _object.GlobalTransform;
		set => _object.GlobalTransform = value;
	}

	public Godot.Vector3 Position
	{
		get => _object.Position;
		set => _object.Position = value;
	}

	public Godot.Vector3 Rotation
	{
		get => _object.Rotation;
		set => _object.Rotation = value;
	}

	public Godot.Vector3 RotationDegrees
	{
		get => _object.RotationDegrees;
		set => _object.RotationDegrees = value;
	}

	public Godot.Quaternion Quaternion
	{
		get => _object.Quaternion;
		set => _object.Quaternion = value;
	}

	public Godot.Basis Basis
	{
		get => _object.Basis;
		set => _object.Basis = value;
	}

	public Godot.Vector3 Scale
	{
		get => _object.Scale;
		set => _object.Scale = value;
	}

	public int RotationEditMode
	{
		get => _object.RotationEditMode;
		set => _object.RotationEditMode = value;
	}

	public int RotationOrder
	{
		get => _object.RotationOrder;
		set => _object.RotationOrder = value;
	}

	public bool TopLevel
	{
		get => _object.TopLevel;
		set => _object.TopLevel = value;
	}

	public Godot.Vector3 GlobalPosition
	{
		get => _object.GlobalPosition;
		set => _object.GlobalPosition = value;
	}

	public Godot.Basis GlobalBasis
	{
		get => _object.GlobalBasis;
		set => _object.GlobalBasis = value;
	}

	public Godot.Vector3 GlobalRotation
	{
		get => _object.GlobalRotation;
		set => _object.GlobalRotation = value;
	}

	public Godot.Vector3 GlobalRotationDegrees
	{
		get => _object.GlobalRotationDegrees;
		set => _object.GlobalRotationDegrees = value;
	}

	public bool Visible
	{
		get => _object.Visible;
		set => _object.Visible = value;
	}

	public Godot.NodePath VisibilityParent
	{
		get => _object.VisibilityParent;
		set => _object.VisibilityParent = value;
	}

	public Godot.NodePath ImportPath
	{
		get => _object.ImportPath;
		set => _object.ImportPath = value;
	}

	public Godot.StringName Name
	{
		get => _object.Name;
		set => _object.Name = value;
	}

	public bool UniqueNameInOwner
	{
		get => _object.UniqueNameInOwner;
		set => _object.UniqueNameInOwner = value;
	}

	public string SceneFilePath
	{
		get => _object.SceneFilePath;
		set => _object.SceneFilePath = value;
	}

	public Node Owner
	{
		get => _object.Owner;
		set => _object.Owner = value;
	}

	public MultiplayerApi Multiplayer
	{
		get => _object.Multiplayer;
	}

	public int ProcessMode
	{
		get => _object.ProcessMode;
		set => _object.ProcessMode = value;
	}

	public int ProcessPriority
	{
		get => _object.ProcessPriority;
		set => _object.ProcessPriority = value;
	}

	public int ProcessPhysicsPriority
	{
		get => _object.ProcessPhysicsPriority;
		set => _object.ProcessPhysicsPriority = value;
	}

	public int ProcessThreadGroup
	{
		get => _object.ProcessThreadGroup;
		set => _object.ProcessThreadGroup = value;
	}

	public int ProcessThreadGroupOrder
	{
		get => _object.ProcessThreadGroupOrder;
		set => _object.ProcessThreadGroupOrder = value;
	}

	public int ProcessThreadMessages
	{
		get => _object.ProcessThreadMessages;
		set => _object.ProcessThreadMessages = value;
	}

	public int PhysicsInterpolationMode
	{
		get => _object.PhysicsInterpolationMode;
		set => _object.PhysicsInterpolationMode = value;
	}

	public int AutoTranslateMode
	{
		get => _object.AutoTranslateMode;
		set => _object.AutoTranslateMode = value;
	}

	public string EditorDescription
	{
		get => _object.EditorDescription;
		set => _object.EditorDescription = value;
	}

	#endregion

	#region Methods

	public void SetBoneIdx(int @bone_idx)
	{
		_object.Call(MethodName.SetBoneIdx, @bone_idx);
	}

	public int GetBoneIdx()
	{
		return (int)_object.Call(MethodName.GetBoneIdx);
	}

	public void SetChainLength(int @chain_length)
	{
		_object.Call(MethodName.SetChainLength, @chain_length);
	}

	public int GetChainLength()
	{
		return (int)_object.Call(MethodName.GetChainLength);
	}

	public void SetTransformMode(GodotIKEffector.TransformModeEnum @transform_mode)
	{
		_object.Call(MethodName.SetTransformMode, (int)@transform_mode);
	}

	public GodotIKEffector.TransformModeEnum GetTransformMode()
	{
		return (GodotIKEffector.TransformModeEnum)(int)_object.Call(MethodName.GetTransformMode);
	}

	public void SetActive(bool @active)
	{
		_object.Call(MethodName.SetActive, @active);
	}

	public bool IsActive()
	{
		return (bool)_object.Call(MethodName.IsActive);
	}

	public Skeleton3D GetSkeleton()
	{
		return (Skeleton3D)_object.Call(MethodName.GetSkeleton);
	}

	public GodotIK GetIkController()
	{
		return (GodotIK)_object.Call(MethodName.GetIkController);
	}

	#endregion

	#region Inherited Methods

	public void SetTransform(Godot.Transform3D @local)
	{
		_object.SetTransform(@local);
	}

	public Godot.Transform3D GetTransform()
	{
		return _object.GetTransform();
	}

	public void SetPosition(Godot.Vector3 @position)
	{
		_object.SetPosition(@position);
	}

	public Godot.Vector3 GetPosition()
	{
		return _object.GetPosition();
	}

	public void SetRotation(Godot.Vector3 @euler_radians)
	{
		_object.SetRotation(@euler_radians);
	}

	public Godot.Vector3 GetRotation()
	{
		return _object.GetRotation();
	}

	public void SetRotationDegrees(Godot.Vector3 @euler_degrees)
	{
		_object.SetRotationDegrees(@euler_degrees);
	}

	public Godot.Vector3 GetRotationDegrees()
	{
		return _object.GetRotationDegrees();
	}

	public void SetRotationOrder(EulerOrder @order)
	{
		_object.SetRotationOrder((int)@order);
	}

	public EulerOrder GetRotationOrder()
	{
		return _object.GetRotationOrder();
	}

	public void SetRotationEditMode(Node3D.RotationEditModeEnum @edit_mode)
	{
		_object.SetRotationEditMode((int)@edit_mode);
	}

	public Node3D.RotationEditModeEnum GetRotationEditMode()
	{
		return _object.GetRotationEditMode();
	}

	public void SetScale(Godot.Vector3 @scale)
	{
		_object.SetScale(@scale);
	}

	public Godot.Vector3 GetScale()
	{
		return _object.GetScale();
	}

	public void SetQuaternion(Godot.Quaternion @quaternion)
	{
		_object.SetQuaternion(@quaternion);
	}

	public Godot.Quaternion GetQuaternion()
	{
		return _object.GetQuaternion();
	}

	public void SetBasis(Godot.Basis @basis)
	{
		_object.SetBasis(@basis);
	}

	public Godot.Basis GetBasis()
	{
		return _object.GetBasis();
	}

	public void SetGlobalTransform(Godot.Transform3D @global)
	{
		_object.SetGlobalTransform(@global);
	}

	public Godot.Transform3D GetGlobalTransform()
	{
		return _object.GetGlobalTransform();
	}

	public Godot.Transform3D GetGlobalTransformInterpolated()
	{
		return _object.GetGlobalTransformInterpolated();
	}

	public void SetGlobalPosition(Godot.Vector3 @position)
	{
		_object.SetGlobalPosition(@position);
	}

	public Godot.Vector3 GetGlobalPosition()
	{
		return _object.GetGlobalPosition();
	}

	public void SetGlobalBasis(Godot.Basis @basis)
	{
		_object.SetGlobalBasis(@basis);
	}

	public Godot.Basis GetGlobalBasis()
	{
		return _object.GetGlobalBasis();
	}

	public void SetGlobalRotation(Godot.Vector3 @euler_radians)
	{
		_object.SetGlobalRotation(@euler_radians);
	}

	public Godot.Vector3 GetGlobalRotation()
	{
		return _object.GetGlobalRotation();
	}

	public void SetGlobalRotationDegrees(Godot.Vector3 @euler_degrees)
	{
		_object.SetGlobalRotationDegrees(@euler_degrees);
	}

	public Godot.Vector3 GetGlobalRotationDegrees()
	{
		return _object.GetGlobalRotationDegrees();
	}

	public Node3D GetParentNode3d()
	{
		return _object.GetParentNode3d();
	}

	public void SetIgnoreTransformNotification(bool @enabled)
	{
		_object.SetIgnoreTransformNotification(@enabled);
	}

	public void SetAsTopLevel(bool @enable)
	{
		_object.SetAsTopLevel(@enable);
	}

	public bool IsSetAsTopLevel()
	{
		return _object.IsSetAsTopLevel();
	}

	public void SetDisableScale(bool @disable)
	{
		_object.SetDisableScale(@disable);
	}

	public bool IsScaleDisabled()
	{
		return _object.IsScaleDisabled();
	}

	public World3D GetWorld3d()
	{
		return _object.GetWorld3d();
	}

	public void ForceUpdateTransform()
	{
		_object.ForceUpdateTransform();
	}

	public void SetVisibilityParent(Godot.NodePath @path)
	{
		_object.SetVisibilityParent(@path);
	}

	public Godot.NodePath GetVisibilityParent()
	{
		return _object.GetVisibilityParent();
	}

	public void UpdateGizmos()
	{
		_object.UpdateGizmos();
	}

	public void AddGizmo(Node3DGizmo @gizmo)
	{
		_object.AddGizmo(@gizmo);
	}

	public Godot.Collections.Array<Godot.Node3DGizmo> GetGizmos()
	{
		return _object.GetGizmos();
	}

	public void ClearGizmos()
	{
		_object.ClearGizmos();
	}

	public void SetSubgizmoSelection(Node3DGizmo @gizmo, int @id, Godot.Transform3D @transform)
	{
		_object.SetSubgizmoSelection(@gizmo, @id, @transform);
	}

	public void ClearSubgizmoSelection()
	{
		_object.ClearSubgizmoSelection();
	}

	public void SetVisible(bool @visible)
	{
		_object.SetVisible(@visible);
	}

	public bool IsVisible()
	{
		return _object.IsVisible();
	}

	public bool IsVisibleInTree()
	{
		return _object.IsVisibleInTree();
	}

	public void Show()
	{
		_object.Show();
	}

	public void Hide()
	{
		_object.Hide();
	}

	public void SetNotifyLocalTransform(bool @enable)
	{
		_object.SetNotifyLocalTransform(@enable);
	}

	public bool IsLocalTransformNotificationEnabled()
	{
		return _object.IsLocalTransformNotificationEnabled();
	}

	public void SetNotifyTransform(bool @enable)
	{
		_object.SetNotifyTransform(@enable);
	}

	public bool IsTransformNotificationEnabled()
	{
		return _object.IsTransformNotificationEnabled();
	}

	public void Rotate(Godot.Vector3 @axis, float @angle)
	{
		_object.Rotate(@axis, @angle);
	}

	public void GlobalRotate(Godot.Vector3 @axis, float @angle)
	{
		_object.GlobalRotate(@axis, @angle);
	}

	public void GlobalScale(Godot.Vector3 @scale)
	{
		_object.GlobalScale(@scale);
	}

	public void GlobalTranslate(Godot.Vector3 @offset)
	{
		_object.GlobalTranslate(@offset);
	}

	public void RotateObjectLocal(Godot.Vector3 @axis, float @angle)
	{
		_object.RotateObjectLocal(@axis, @angle);
	}

	public void ScaleObjectLocal(Godot.Vector3 @scale)
	{
		_object.ScaleObjectLocal(@scale);
	}

	public void TranslateObjectLocal(Godot.Vector3 @offset)
	{
		_object.TranslateObjectLocal(@offset);
	}

	public void RotateX(float @angle)
	{
		_object.RotateX(@angle);
	}

	public void RotateY(float @angle)
	{
		_object.RotateY(@angle);
	}

	public void RotateZ(float @angle)
	{
		_object.RotateZ(@angle);
	}

	public void Translate(Godot.Vector3 @offset)
	{
		_object.Translate(@offset);
	}

	public void Orthonormalize()
	{
		_object.Orthonormalize();
	}

	public void SetIdentity()
	{
		_object.SetIdentity();
	}

	public void LookAt(Godot.Vector3 @target, Godot.Vector3? @up = null, bool @use_model_front = false)
	{
		@up ??= new(0.0f, 1.0f, 0.0f);
		_object.LookAt(@target, @up, @use_model_front);
	}

	public void LookAtFromPosition(Godot.Vector3 @position, Godot.Vector3 @target, Godot.Vector3? @up = null, bool @use_model_front = false)
	{
		@up ??= new(0.0f, 1.0f, 0.0f);
		_object.LookAtFromPosition(@position, @target, @up, @use_model_front);
	}

	public Godot.Vector3 ToLocal(Godot.Vector3 @global_point)
	{
		return _object.ToLocal(@global_point);
	}

	public Godot.Vector3 ToGlobal(Godot.Vector3 @local_point)
	{
		return _object.ToGlobal(@local_point);
	}

	public static void PrintOrphanNodes()
	{
		Node.PrintOrphanNodes();
	}

	public void AddSibling(Node @sibling, bool @force_readable_name = false)
	{
		_object.AddSibling(@sibling, @force_readable_name);
	}

	public void SetName(string @name)
	{
		_object.SetName(@name);
	}

	public Godot.StringName GetName()
	{
		return _object.GetName();
	}

	public void AddChild(Node @node, bool @force_readable_name = false, Node.InternalMode @internal = (Node.InternalMode)0)
	{
		_object.AddChild(@node, @force_readable_name, (int)@internal);
	}

	public void RemoveChild(Node @node)
	{
		_object.RemoveChild(@node);
	}

	public void Reparent(Node @new_parent, bool @keep_global_transform = true)
	{
		_object.Reparent(@new_parent, @keep_global_transform);
	}

	public int GetChildCount(bool @include_internal = false)
	{
		return _object.GetChildCount(@include_internal);
	}

	public Godot.Collections.Array<Godot.Node> GetChildren(bool @include_internal = false)
	{
		return _object.GetChildren(@include_internal);
	}

	public Node GetChild(int @idx, bool @include_internal = false)
	{
		return _object.GetChild(@idx, @include_internal);
	}

	public bool HasNode(Godot.NodePath @path)
	{
		return _object.HasNode(@path);
	}

	public Node GetNode(Godot.NodePath @path)
	{
		return _object.GetNode(@path);
	}

	public Node GetNodeOrNull(Godot.NodePath @path)
	{
		return _object.GetNodeOrNull(@path);
	}

	public Node GetParent()
	{
		return _object.GetParent();
	}

	public Node FindChild(string @pattern, bool @recursive = true, bool @owned = true)
	{
		return _object.FindChild(@pattern, @recursive, @owned);
	}

	public Godot.Collections.Array<Godot.Node> FindChildren(string @pattern, string @type = "", bool @recursive = true, bool @owned = true)
	{
		return _object.FindChildren(@pattern, @type, @recursive, @owned);
	}

	public Node FindParent(string @pattern)
	{
		return _object.FindParent(@pattern);
	}

	public bool HasNodeAndResource(Godot.NodePath @path)
	{
		return _object.HasNodeAndResource(@path);
	}

	public Godot.Collections.Array GetNodeAndResource(Godot.NodePath @path)
	{
		return _object.GetNodeAndResource(@path);
	}

	public bool IsInsideTree()
	{
		return _object.IsInsideTree();
	}

	public bool IsPartOfEditedScene()
	{
		return _object.IsPartOfEditedScene();
	}

	public bool IsAncestorOf(Node @node)
	{
		return _object.IsAncestorOf(@node);
	}

	public bool IsGreaterThan(Node @node)
	{
		return _object.IsGreaterThan(@node);
	}

	public Godot.NodePath GetPath()
	{
		return _object.GetPath();
	}

	public Godot.NodePath GetPathTo(Node @node, bool @use_unique_path = false)
	{
		return _object.GetPathTo(@node, @use_unique_path);
	}

	public void AddToGroup(Godot.StringName @group, bool @persistent = false)
	{
		_object.AddToGroup(@group, @persistent);
	}

	public void RemoveFromGroup(Godot.StringName @group)
	{
		_object.RemoveFromGroup(@group);
	}

	public bool IsInGroup(Godot.StringName @group)
	{
		return _object.IsInGroup(@group);
	}

	public void MoveChild(Node @child_node, int @to_index)
	{
		_object.MoveChild(@child_node, @to_index);
	}

	public Godot.Collections.Array<StringName> GetGroups()
	{
		return _object.GetGroups();
	}

	public void SetOwner(Node @owner)
	{
		_object.SetOwner(@owner);
	}

	public Node GetOwner()
	{
		return _object.GetOwner();
	}

	public int GetIndex(bool @include_internal = false)
	{
		return _object.GetIndex(@include_internal);
	}

	public void PrintTree()
	{
		_object.PrintTree();
	}

	public void PrintTreePretty()
	{
		_object.PrintTreePretty();
	}

	public string GetTreeString()
	{
		return _object.GetTreeString();
	}

	public string GetTreeStringPretty()
	{
		return _object.GetTreeStringPretty();
	}

	public void SetSceneFilePath(string @scene_file_path)
	{
		_object.SetSceneFilePath(@scene_file_path);
	}

	public string GetSceneFilePath()
	{
		return _object.GetSceneFilePath();
	}

	public void PropagateNotification(int @what)
	{
		_object.PropagateNotification(@what);
	}

	public void PropagateCall(Godot.StringName @method, Godot.Collections.Array @args = null, bool @parent_first = false)
	{
		@args ??= new();
		_object.PropagateCall(@method, @args, @parent_first);
	}

	public void SetPhysicsProcess(bool @enable)
	{
		_object.SetPhysicsProcess(@enable);
	}

	public float GetPhysicsProcessDeltaTime()
	{
		return _object.GetPhysicsProcessDeltaTime();
	}

	public bool IsPhysicsProcessing()
	{
		return _object.IsPhysicsProcessing();
	}

	public float GetProcessDeltaTime()
	{
		return _object.GetProcessDeltaTime();
	}

	public void SetProcess(bool @enable)
	{
		_object.SetProcess(@enable);
	}

	public void SetProcessPriority(int @priority)
	{
		_object.SetProcessPriority(@priority);
	}

	public int GetProcessPriority()
	{
		return _object.GetProcessPriority();
	}

	public void SetPhysicsProcessPriority(int @priority)
	{
		_object.SetPhysicsProcessPriority(@priority);
	}

	public int GetPhysicsProcessPriority()
	{
		return _object.GetPhysicsProcessPriority();
	}

	public bool IsProcessing()
	{
		return _object.IsProcessing();
	}

	public void SetProcessInput(bool @enable)
	{
		_object.SetProcessInput(@enable);
	}

	public bool IsProcessingInput()
	{
		return _object.IsProcessingInput();
	}

	public void SetProcessShortcutInput(bool @enable)
	{
		_object.SetProcessShortcutInput(@enable);
	}

	public bool IsProcessingShortcutInput()
	{
		return _object.IsProcessingShortcutInput();
	}

	public void SetProcessUnhandledInput(bool @enable)
	{
		_object.SetProcessUnhandledInput(@enable);
	}

	public bool IsProcessingUnhandledInput()
	{
		return _object.IsProcessingUnhandledInput();
	}

	public void SetProcessUnhandledKeyInput(bool @enable)
	{
		_object.SetProcessUnhandledKeyInput(@enable);
	}

	public bool IsProcessingUnhandledKeyInput()
	{
		return _object.IsProcessingUnhandledKeyInput();
	}

	public void SetProcessMode(Node.ProcessModeEnum @mode)
	{
		_object.SetProcessMode((int)@mode);
	}

	public Node.ProcessModeEnum GetProcessMode()
	{
		return _object.GetProcessMode();
	}

	public bool CanProcess()
	{
		return _object.CanProcess();
	}

	public void SetProcessThreadGroup(Node.ProcessThreadGroupEnum @mode)
	{
		_object.SetProcessThreadGroup((int)@mode);
	}

	public Node.ProcessThreadGroupEnum GetProcessThreadGroup()
	{
		return _object.GetProcessThreadGroup();
	}

	public void SetProcessThreadMessages(Node.ProcessThreadMessagesEnum @flags)
	{
		_object.SetProcessThreadMessages((int)@flags);
	}

	public Node.ProcessThreadMessagesEnum GetProcessThreadMessages()
	{
		return _object.GetProcessThreadMessages();
	}

	public void SetProcessThreadGroupOrder(int @order)
	{
		_object.SetProcessThreadGroupOrder(@order);
	}

	public int GetProcessThreadGroupOrder()
	{
		return _object.GetProcessThreadGroupOrder();
	}

	public void SetDisplayFolded(bool @fold)
	{
		_object.SetDisplayFolded(@fold);
	}

	public bool IsDisplayedFolded()
	{
		return _object.IsDisplayedFolded();
	}

	public void SetProcessInternal(bool @enable)
	{
		_object.SetProcessInternal(@enable);
	}

	public bool IsProcessingInternal()
	{
		return _object.IsProcessingInternal();
	}

	public void SetPhysicsProcessInternal(bool @enable)
	{
		_object.SetPhysicsProcessInternal(@enable);
	}

	public bool IsPhysicsProcessingInternal()
	{
		return _object.IsPhysicsProcessingInternal();
	}

	public void SetPhysicsInterpolationMode(Node.PhysicsInterpolationModeEnum @mode)
	{
		_object.SetPhysicsInterpolationMode((int)@mode);
	}

	public Node.PhysicsInterpolationModeEnum GetPhysicsInterpolationMode()
	{
		return _object.GetPhysicsInterpolationMode();
	}

	public bool IsPhysicsInterpolated()
	{
		return _object.IsPhysicsInterpolated();
	}

	public bool IsPhysicsInterpolatedAndEnabled()
	{
		return _object.IsPhysicsInterpolatedAndEnabled();
	}

	public void ResetPhysicsInterpolation()
	{
		_object.ResetPhysicsInterpolation();
	}

	public void SetAutoTranslateMode(Node.AutoTranslateModeEnum @mode)
	{
		_object.SetAutoTranslateMode((int)@mode);
	}

	public Node.AutoTranslateModeEnum GetAutoTranslateMode()
	{
		return _object.GetAutoTranslateMode();
	}

	public void SetTranslationDomainInherited()
	{
		_object.SetTranslationDomainInherited();
	}

	public Window GetWindow()
	{
		return _object.GetWindow();
	}

	public Window GetLastExclusiveWindow()
	{
		return _object.GetLastExclusiveWindow();
	}

	public SceneTree GetTree()
	{
		return _object.GetTree();
	}

	public Tween CreateTween()
	{
		return _object.CreateTween();
	}

	public Node Duplicate(int @flags = 15)
	{
		return _object.Duplicate(@flags);
	}

	public void ReplaceBy(Node @node, bool @keep_groups = false)
	{
		_object.ReplaceBy(@node, @keep_groups);
	}

	public void SetSceneInstanceLoadPlaceholder(bool @load_placeholder)
	{
		_object.SetSceneInstanceLoadPlaceholder(@load_placeholder);
	}

	public bool GetSceneInstanceLoadPlaceholder()
	{
		return _object.GetSceneInstanceLoadPlaceholder();
	}

	public void SetEditableInstance(Node @node, bool @is_editable)
	{
		_object.SetEditableInstance(@node, @is_editable);
	}

	public bool IsEditableInstance(Node @node)
	{
		return _object.IsEditableInstance(@node);
	}

	public Viewport GetViewport()
	{
		return _object.GetViewport();
	}

	public void QueueFree()
	{
		_object.QueueFree();
	}

	public void RequestReady()
	{
		_object.RequestReady();
	}

	public bool IsNodeReady()
	{
		return _object.IsNodeReady();
	}

	public void SetMultiplayerAuthority(int @id, bool @recursive = true)
	{
		_object.SetMultiplayerAuthority(@id, @recursive);
	}

	public int GetMultiplayerAuthority()
	{
		return _object.GetMultiplayerAuthority();
	}

	public bool IsMultiplayerAuthority()
	{
		return _object.IsMultiplayerAuthority();
	}

	public MultiplayerApi GetMultiplayer()
	{
		return _object.GetMultiplayer();
	}

	public void RpcConfig(Godot.StringName @method, Variant @config)
	{
		_object.RpcConfig(@method, @config);
	}

	public Variant GetRpcConfig()
	{
		return _object.GetRpcConfig();
	}

	public void SetEditorDescription(string @editor_description)
	{
		_object.SetEditorDescription(@editor_description);
	}

	public string GetEditorDescription()
	{
		return _object.GetEditorDescription();
	}

	public void SetUniqueNameInOwner(bool @enable)
	{
		_object.SetUniqueNameInOwner(@enable);
	}

	public bool IsUniqueNameInOwner()
	{
		return _object.IsUniqueNameInOwner();
	}

	public string Atr(string @message, Godot.StringName @context = null)
	{
		@context ??= "";
		return _object.Atr(@message, @context);
	}

	public string AtrN(string @message, Godot.StringName @plural_message, int @n, Godot.StringName @context = null)
	{
		@context ??= "";
		return _object.AtrN(@message, @plural_message, @n, @context);
	}

	public Godot.Error Rpc(Godot.StringName @method, params Variant[] varargs)
	{
		return _object.Rpc(@method, varargs);
	}

	public Godot.Error RpcId(int @peer_id, Godot.StringName @method, params Variant[] varargs)
	{
		return _object.RpcId(@peer_id, @method, varargs);
	}

	public void UpdateConfigurationWarnings()
	{
		_object.UpdateConfigurationWarnings();
	}

	public Variant CallDeferredThreadGroup(Godot.StringName @method, params Variant[] varargs)
	{
		return _object.CallDeferredThreadGroup(@method, varargs);
	}

	public void SetDeferredThreadGroup(Godot.StringName @property, Variant @value)
	{
		_object.SetDeferredThreadGroup(@property, @value);
	}

	public void NotifyDeferredThreadGroup(int @what)
	{
		_object.NotifyDeferredThreadGroup(@what);
	}

	public Variant CallThreadSafe(Godot.StringName @method, params Variant[] varargs)
	{
		return _object.CallThreadSafe(@method, varargs);
	}

	public void SetThreadSafe(Godot.StringName @property, Variant @value)
	{
		_object.SetThreadSafe(@property, @value);
	}

	public void NotifyThreadSafe(int @what)
	{
		_object.NotifyThreadSafe(@what);
	}

	public void Free()
	{
		_object.Free();
	}

	public string GetClass()
	{
		return _object.GetClass();
	}

	public bool IsClass(string @class)
	{
		return _object.IsClass(@class);
	}

	public void Set(Godot.StringName @property, Variant @value)
	{
		_object.Set(@property, @value);
	}

	public Variant Get(Godot.StringName @property)
	{
		return _object.Get(@property);
	}

	public void SetIndexed(Godot.NodePath @property_path, Variant @value)
	{
		_object.SetIndexed(@property_path, @value);
	}

	public Variant GetIndexed(Godot.NodePath @property_path)
	{
		return _object.GetIndexed(@property_path);
	}

	public Godot.Collections.Array<Godot.Collections.Dictionary> GetPropertyList()
	{
		return _object.GetPropertyList();
	}

	public Godot.Collections.Array<Godot.Collections.Dictionary> GetMethodList()
	{
		return _object.GetMethodList();
	}

	public bool PropertyCanRevert(Godot.StringName @property)
	{
		return _object.PropertyCanRevert(@property);
	}

	public Variant PropertyGetRevert(Godot.StringName @property)
	{
		return _object.PropertyGetRevert(@property);
	}

	public void Notification(int @what, bool @reversed = false)
	{
		_object.Notification(@what, @reversed);
	}

	public override string ToString()
	{
		return _object.ToString();
	}

	public ulong GetInstanceId()
	{
		return _object.GetInstanceId();
	}

	public void SetScript(Variant @script)
	{
		_object.SetScript(@script);
	}

	public Variant GetScript()
	{
		return _object.GetScript();
	}

	public void SetMeta(Godot.StringName @name, Variant @value)
	{
		_object.SetMeta(@name, @value);
	}

	public void RemoveMeta(Godot.StringName @name)
	{
		_object.RemoveMeta(@name);
	}

	public Variant GetMeta(Godot.StringName @name, Variant @default = default)
	{
		return _object.GetMeta(@name, @default);
	}

	public bool HasMeta(Godot.StringName @name)
	{
		return _object.HasMeta(@name);
	}

	public Godot.Collections.Array<StringName> GetMetaList()
	{
		return _object.GetMetaList();
	}

	public void AddUserSignal(string @signal, Godot.Collections.Array @arguments = null)
	{
		@arguments ??= new();
		_object.AddUserSignal(@signal, @arguments);
	}

	public bool HasUserSignal(Godot.StringName @signal)
	{
		return _object.HasUserSignal(@signal);
	}

	public void RemoveUserSignal(Godot.StringName @signal)
	{
		_object.RemoveUserSignal(@signal);
	}

	public Godot.Error EmitSignal(Godot.StringName @signal, params Variant[] varargs)
	{
		return _object.EmitSignal(@signal, varargs);
	}

	public Variant Call(Godot.StringName @method, params Variant[] varargs)
	{
		return _object.Call(@method, varargs);
	}

	public Variant CallDeferred(Godot.StringName @method, params Variant[] varargs)
	{
		return _object.CallDeferred(@method, varargs);
	}

	public void SetDeferred(Godot.StringName @property, Variant @value)
	{
		_object.SetDeferred(@property, @value);
	}

	public Variant Callv(Godot.StringName @method, Godot.Collections.Array @arg_array)
	{
		return _object.Callv(@method, @arg_array);
	}

	public bool HasMethod(Godot.StringName @method)
	{
		return _object.HasMethod(@method);
	}

	public int GetMethodArgumentCount(Godot.StringName @method)
	{
		return _object.GetMethodArgumentCount(@method);
	}

	public bool HasSignal(Godot.StringName @signal)
	{
		return _object.HasSignal(@signal);
	}

	public Godot.Collections.Array<Godot.Collections.Dictionary> GetSignalList()
	{
		return _object.GetSignalList();
	}

	public Godot.Collections.Array<Godot.Collections.Dictionary> GetSignalConnectionList(Godot.StringName @signal)
	{
		return _object.GetSignalConnectionList(@signal);
	}

	public Godot.Collections.Array<Godot.Collections.Dictionary> GetIncomingConnections()
	{
		return _object.GetIncomingConnections();
	}

	public Godot.Error Connect(Godot.StringName @signal, Godot.Callable @callable, uint @flags = (uint)0)
	{
		return _object.Connect(@signal, @callable, @flags);
	}

	public void Disconnect(Godot.StringName @signal, Godot.Callable @callable)
	{
		_object.Disconnect(@signal, @callable);
	}

	public bool IsConnected(Godot.StringName @signal, Godot.Callable @callable)
	{
		return _object.IsConnected(@signal, @callable);
	}

	public bool HasConnections(Godot.StringName @signal)
	{
		return _object.HasConnections(@signal);
	}

	public void SetBlockSignals(bool @enable)
	{
		_object.SetBlockSignals(@enable);
	}

	public bool IsBlockingSignals()
	{
		return _object.IsBlockingSignals();
	}

	public void NotifyPropertyListChanged()
	{
		_object.NotifyPropertyListChanged();
	}

	public void SetMessageTranslation(bool @enable)
	{
		_object.SetMessageTranslation(@enable);
	}

	public bool CanTranslateMessages()
	{
		return _object.CanTranslateMessages();
	}

	public string Tr(Godot.StringName @message, Godot.StringName @context = null)
	{
		@context ??= "";
		return _object.Tr(@message, @context);
	}

	public string TrN(Godot.StringName @message, Godot.StringName @plural_message, int @n, Godot.StringName @context = null)
	{
		@context ??= "";
		return _object.TrN(@message, @plural_message, @n, @context);
	}

	public Godot.StringName GetTranslationDomain()
	{
		return _object.GetTranslationDomain();
	}

	public void SetTranslationDomain(Godot.StringName @domain)
	{
		_object.SetTranslationDomain(@domain);
	}

	public bool IsQueuedForDeletion()
	{
		return _object.IsQueuedForDeletion();
	}

	public void CancelFree()
	{
		_object.CancelFree();
	}

	#endregion

	#region Signals

	public event Action<int> BoneIdxChangedEvent
	{
		add
		{
			Connect(SignalName.BoneIdxChanged, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.BoneIdxChanged, Callable.From(value));
		}
	}

	public event Action<int> ChainLengthChangedEvent
	{
		add
		{
			Connect(SignalName.ChainLengthChanged, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.ChainLengthChanged, Callable.From(value));
		}
	}

	#endregion

	#region Inherited Signals

	public event Action VisibilityChangedEvent
	{
		add
		{
			Connect(SignalName.VisibilityChanged, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.VisibilityChanged, Callable.From(value));
		}
	}

	public event Action ReadyEvent
	{
		add
		{
			Connect(SignalName.Ready, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.Ready, Callable.From(value));
		}
	}

	public event Action RenamedEvent
	{
		add
		{
			Connect(SignalName.Renamed, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.Renamed, Callable.From(value));
		}
	}

	public event Action TreeEnteredEvent
	{
		add
		{
			Connect(SignalName.TreeEntered, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.TreeEntered, Callable.From(value));
		}
	}

	public event Action TreeExitingEvent
	{
		add
		{
			Connect(SignalName.TreeExiting, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.TreeExiting, Callable.From(value));
		}
	}

	public event Action TreeExitedEvent
	{
		add
		{
			Connect(SignalName.TreeExited, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.TreeExited, Callable.From(value));
		}
	}

	public event Action<Node> ChildEnteredTreeEvent
	{
		add
		{
			Connect(SignalName.ChildEnteredTree, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.ChildEnteredTree, Callable.From(value));
		}
	}

	public event Action<Node> ChildExitingTreeEvent
	{
		add
		{
			Connect(SignalName.ChildExitingTree, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.ChildExitingTree, Callable.From(value));
		}
	}

	public event Action ChildOrderChangedEvent
	{
		add
		{
			Connect(SignalName.ChildOrderChanged, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.ChildOrderChanged, Callable.From(value));
		}
	}

	public event Action<Node> ReplacingByEvent
	{
		add
		{
			Connect(SignalName.ReplacingBy, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.ReplacingBy, Callable.From(value));
		}
	}

	public event Action<Node> EditorDescriptionChangedEvent
	{
		add
		{
			Connect(SignalName.EditorDescriptionChanged, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.EditorDescriptionChanged, Callable.From(value));
		}
	}

	public event Action EditorStateChangedEvent
	{
		add
		{
			Connect(SignalName.EditorStateChanged, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.EditorStateChanged, Callable.From(value));
		}
	}

	public event Action ScriptChangedEvent
	{
		add
		{
			Connect(SignalName.ScriptChanged, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.ScriptChanged, Callable.From(value));
		}
	}

	public event Action PropertyListChangedEvent
	{
		add
		{
			Connect(SignalName.PropertyListChanged, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.PropertyListChanged, Callable.From(value));
		}
	}

	#endregion
}
