// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;
using Object = Godot.GodotObject;

namespace GDExtensionBindgen;

public class JoltPhysicsDirectBodyState3DExtension
{
	// Engine object used for calling engine methods
	protected PhysicsDirectBodyState3DExtension _object;

	public JoltPhysicsDirectBodyState3DExtension() : this(NativeName)
	{
	}
	protected JoltPhysicsDirectBodyState3DExtension(StringName @class) : this(ClassDB.Instantiate(@class))
	{
	}
	protected JoltPhysicsDirectBodyState3DExtension(Variant variant) : this((PhysicsDirectBodyState3DExtension) variant)
	{
	}
	protected JoltPhysicsDirectBodyState3DExtension([NotNull] PhysicsDirectBodyState3DExtension @object)
	{
		_object = @object;
	}

	public static implicit operator PhysicsDirectBodyState3DExtension(JoltPhysicsDirectBodyState3DExtension self) => self?._object;
	public static implicit operator Variant(JoltPhysicsDirectBodyState3DExtension self) => self?._object;
	public static explicit operator JoltPhysicsDirectBodyState3DExtension(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public class PropertyName : PhysicsDirectBodyState3DExtension.PropertyName
	{

	}

	public class MethodName : PhysicsDirectBodyState3DExtension.MethodName
	{

	}

	public class SignalName : PhysicsDirectBodyState3DExtension.SignalName
	{

	}

	private static readonly StringName NativeName = "JoltPhysicsDirectBodyState3DExtension";

	#region Inherited Properties

	public float Step
	{
		get => _object.Step;
	}

	public float InverseMass
	{
		get => _object.InverseMass;
	}

	public float TotalAngularDamp
	{
		get => _object.TotalAngularDamp;
	}

	public float TotalLinearDamp
	{
		get => _object.TotalLinearDamp;
	}

	public Godot.Vector3 InverseInertia
	{
		get => _object.InverseInertia;
	}

	public Godot.Basis InverseInertiaTensor
	{
		get => _object.InverseInertiaTensor;
	}

	public Godot.Vector3 TotalGravity
	{
		get => _object.TotalGravity;
	}

	public Godot.Vector3 CenterOfMass
	{
		get => _object.CenterOfMass;
	}

	public Godot.Vector3 CenterOfMassLocal
	{
		get => _object.CenterOfMassLocal;
	}

	public Godot.Basis PrincipalInertiaAxes
	{
		get => _object.PrincipalInertiaAxes;
	}

	public Godot.Vector3 AngularVelocity
	{
		get => _object.AngularVelocity;
		set => _object.AngularVelocity = value;
	}

	public Godot.Vector3 LinearVelocity
	{
		get => _object.LinearVelocity;
		set => _object.LinearVelocity = value;
	}

	public bool Sleeping
	{
		get => _object.Sleeping;
		set => _object.Sleeping = value;
	}

	public Godot.Transform3D Transform
	{
		get => _object.Transform;
		set => _object.Transform = value;
	}

	#endregion

	#region Inherited Methods

	public Godot.Vector3 GetTotalGravity()
	{
		return _object.GetTotalGravity();
	}

	public float GetTotalLinearDamp()
	{
		return _object.GetTotalLinearDamp();
	}

	public float GetTotalAngularDamp()
	{
		return _object.GetTotalAngularDamp();
	}

	public Godot.Vector3 GetCenterOfMass()
	{
		return _object.GetCenterOfMass();
	}

	public Godot.Vector3 GetCenterOfMassLocal()
	{
		return _object.GetCenterOfMassLocal();
	}

	public Godot.Basis GetPrincipalInertiaAxes()
	{
		return _object.GetPrincipalInertiaAxes();
	}

	public float GetInverseMass()
	{
		return _object.GetInverseMass();
	}

	public Godot.Vector3 GetInverseInertia()
	{
		return _object.GetInverseInertia();
	}

	public Godot.Basis GetInverseInertiaTensor()
	{
		return _object.GetInverseInertiaTensor();
	}

	public void SetLinearVelocity(Godot.Vector3 @velocity)
	{
		_object.SetLinearVelocity(@velocity);
	}

	public Godot.Vector3 GetLinearVelocity()
	{
		return _object.GetLinearVelocity();
	}

	public void SetAngularVelocity(Godot.Vector3 @velocity)
	{
		_object.SetAngularVelocity(@velocity);
	}

	public Godot.Vector3 GetAngularVelocity()
	{
		return _object.GetAngularVelocity();
	}

	public void SetTransform(Godot.Transform3D @transform)
	{
		_object.SetTransform(@transform);
	}

	public Godot.Transform3D GetTransform()
	{
		return _object.GetTransform();
	}

	public Godot.Vector3 GetVelocityAtLocalPosition(Godot.Vector3 @local_position)
	{
		return _object.GetVelocityAtLocalPosition(@local_position);
	}

	public void ApplyCentralImpulse(Godot.Vector3? @impulse = null)
	{
		@impulse ??= new(0.0f, 0.0f, 0.0f);
		_object.ApplyCentralImpulse(@impulse);
	}

	public void ApplyImpulse(Godot.Vector3 @impulse, Godot.Vector3? @position = null)
	{
		@position ??= new(0.0f, 0.0f, 0.0f);
		_object.ApplyImpulse(@impulse, @position);
	}

	public void ApplyTorqueImpulse(Godot.Vector3 @impulse)
	{
		_object.ApplyTorqueImpulse(@impulse);
	}

	public void ApplyCentralForce(Godot.Vector3? @force = null)
	{
		@force ??= new(0.0f, 0.0f, 0.0f);
		_object.ApplyCentralForce(@force);
	}

	public void ApplyForce(Godot.Vector3 @force, Godot.Vector3? @position = null)
	{
		@position ??= new(0.0f, 0.0f, 0.0f);
		_object.ApplyForce(@force, @position);
	}

	public void ApplyTorque(Godot.Vector3 @torque)
	{
		_object.ApplyTorque(@torque);
	}

	public void AddConstantCentralForce(Godot.Vector3? @force = null)
	{
		@force ??= new(0.0f, 0.0f, 0.0f);
		_object.AddConstantCentralForce(@force);
	}

	public void AddConstantForce(Godot.Vector3 @force, Godot.Vector3? @position = null)
	{
		@position ??= new(0.0f, 0.0f, 0.0f);
		_object.AddConstantForce(@force, @position);
	}

	public void AddConstantTorque(Godot.Vector3 @torque)
	{
		_object.AddConstantTorque(@torque);
	}

	public void SetConstantForce(Godot.Vector3 @force)
	{
		_object.SetConstantForce(@force);
	}

	public Godot.Vector3 GetConstantForce()
	{
		return _object.GetConstantForce();
	}

	public void SetConstantTorque(Godot.Vector3 @torque)
	{
		_object.SetConstantTorque(@torque);
	}

	public Godot.Vector3 GetConstantTorque()
	{
		return _object.GetConstantTorque();
	}

	public void SetSleepState(bool @enabled)
	{
		_object.SetSleepState(@enabled);
	}

	public bool IsSleeping()
	{
		return _object.IsSleeping();
	}

	public int GetContactCount()
	{
		return _object.GetContactCount();
	}

	public Godot.Vector3 GetContactLocalPosition(int @contact_idx)
	{
		return _object.GetContactLocalPosition(@contact_idx);
	}

	public Godot.Vector3 GetContactLocalNormal(int @contact_idx)
	{
		return _object.GetContactLocalNormal(@contact_idx);
	}

	public Godot.Vector3 GetContactImpulse(int @contact_idx)
	{
		return _object.GetContactImpulse(@contact_idx);
	}

	public int GetContactLocalShape(int @contact_idx)
	{
		return _object.GetContactLocalShape(@contact_idx);
	}

	public Godot.Vector3 GetContactLocalVelocityAtPosition(int @contact_idx)
	{
		return _object.GetContactLocalVelocityAtPosition(@contact_idx);
	}

	public Godot.Rid GetContactCollider(int @contact_idx)
	{
		return _object.GetContactCollider(@contact_idx);
	}

	public Godot.Vector3 GetContactColliderPosition(int @contact_idx)
	{
		return _object.GetContactColliderPosition(@contact_idx);
	}

	public int GetContactColliderId(int @contact_idx)
	{
		return _object.GetContactColliderId(@contact_idx);
	}

	public GodotObject GetContactColliderObject(int @contact_idx)
	{
		return _object.GetContactColliderObject(@contact_idx);
	}

	public int GetContactColliderShape(int @contact_idx)
	{
		return _object.GetContactColliderShape(@contact_idx);
	}

	public Godot.Vector3 GetContactColliderVelocityAtPosition(int @contact_idx)
	{
		return _object.GetContactColliderVelocityAtPosition(@contact_idx);
	}

	public float GetStep()
	{
		return _object.GetStep();
	}

	public void IntegrateForces()
	{
		_object.IntegrateForces();
	}

	public PhysicsDirectSpaceState3D GetSpaceState()
	{
		return _object.GetSpaceState();
	}

	public void Free()
	{
		_object.Free();
	}

	public string GetClass()
	{
		return _object.GetClass();
	}

	public bool IsClass(string @class)
	{
		return _object.IsClass(@class);
	}

	public void Set(Godot.StringName @property, Variant @value)
	{
		_object.Set(@property, @value);
	}

	public Variant Get(Godot.StringName @property)
	{
		return _object.Get(@property);
	}

	public void SetIndexed(Godot.NodePath @property_path, Variant @value)
	{
		_object.SetIndexed(@property_path, @value);
	}

	public Variant GetIndexed(Godot.NodePath @property_path)
	{
		return _object.GetIndexed(@property_path);
	}

	public Godot.Collections.Array<Godot.Collections.Dictionary> GetPropertyList()
	{
		return _object.GetPropertyList();
	}

	public Godot.Collections.Array<Godot.Collections.Dictionary> GetMethodList()
	{
		return _object.GetMethodList();
	}

	public bool PropertyCanRevert(Godot.StringName @property)
	{
		return _object.PropertyCanRevert(@property);
	}

	public Variant PropertyGetRevert(Godot.StringName @property)
	{
		return _object.PropertyGetRevert(@property);
	}

	public void Notification(int @what, bool @reversed = false)
	{
		_object.Notification(@what, @reversed);
	}

	public override string ToString()
	{
		return _object.ToString();
	}

	public ulong GetInstanceId()
	{
		return _object.GetInstanceId();
	}

	public void SetScript(Variant @script)
	{
		_object.SetScript(@script);
	}

	public Variant GetScript()
	{
		return _object.GetScript();
	}

	public void SetMeta(Godot.StringName @name, Variant @value)
	{
		_object.SetMeta(@name, @value);
	}

	public void RemoveMeta(Godot.StringName @name)
	{
		_object.RemoveMeta(@name);
	}

	public Variant GetMeta(Godot.StringName @name, Variant @default = default)
	{
		return _object.GetMeta(@name, @default);
	}

	public bool HasMeta(Godot.StringName @name)
	{
		return _object.HasMeta(@name);
	}

	public Godot.Collections.Array<StringName> GetMetaList()
	{
		return _object.GetMetaList();
	}

	public void AddUserSignal(string @signal, Godot.Collections.Array @arguments = null)
	{
		@arguments ??= new();
		_object.AddUserSignal(@signal, @arguments);
	}

	public bool HasUserSignal(Godot.StringName @signal)
	{
		return _object.HasUserSignal(@signal);
	}

	public void RemoveUserSignal(Godot.StringName @signal)
	{
		_object.RemoveUserSignal(@signal);
	}

	public Godot.Error EmitSignal(Godot.StringName @signal, params Variant[] varargs)
	{
		return _object.EmitSignal(@signal, varargs);
	}

	public Variant Call(Godot.StringName @method, params Variant[] varargs)
	{
		return _object.Call(@method, varargs);
	}

	public Variant CallDeferred(Godot.StringName @method, params Variant[] varargs)
	{
		return _object.CallDeferred(@method, varargs);
	}

	public void SetDeferred(Godot.StringName @property, Variant @value)
	{
		_object.SetDeferred(@property, @value);
	}

	public Variant Callv(Godot.StringName @method, Godot.Collections.Array @arg_array)
	{
		return _object.Callv(@method, @arg_array);
	}

	public bool HasMethod(Godot.StringName @method)
	{
		return _object.HasMethod(@method);
	}

	public int GetMethodArgumentCount(Godot.StringName @method)
	{
		return _object.GetMethodArgumentCount(@method);
	}

	public bool HasSignal(Godot.StringName @signal)
	{
		return _object.HasSignal(@signal);
	}

	public Godot.Collections.Array<Godot.Collections.Dictionary> GetSignalList()
	{
		return _object.GetSignalList();
	}

	public Godot.Collections.Array<Godot.Collections.Dictionary> GetSignalConnectionList(Godot.StringName @signal)
	{
		return _object.GetSignalConnectionList(@signal);
	}

	public Godot.Collections.Array<Godot.Collections.Dictionary> GetIncomingConnections()
	{
		return _object.GetIncomingConnections();
	}

	public Godot.Error Connect(Godot.StringName @signal, Godot.Callable @callable, uint @flags = (uint)0)
	{
		return _object.Connect(@signal, @callable, @flags);
	}

	public void Disconnect(Godot.StringName @signal, Godot.Callable @callable)
	{
		_object.Disconnect(@signal, @callable);
	}

	public bool IsConnected(Godot.StringName @signal, Godot.Callable @callable)
	{
		return _object.IsConnected(@signal, @callable);
	}

	public bool HasConnections(Godot.StringName @signal)
	{
		return _object.HasConnections(@signal);
	}

	public void SetBlockSignals(bool @enable)
	{
		_object.SetBlockSignals(@enable);
	}

	public bool IsBlockingSignals()
	{
		return _object.IsBlockingSignals();
	}

	public void NotifyPropertyListChanged()
	{
		_object.NotifyPropertyListChanged();
	}

	public void SetMessageTranslation(bool @enable)
	{
		_object.SetMessageTranslation(@enable);
	}

	public bool CanTranslateMessages()
	{
		return _object.CanTranslateMessages();
	}

	public string Tr(Godot.StringName @message, Godot.StringName @context = null)
	{
		@context ??= "";
		return _object.Tr(@message, @context);
	}

	public string TrN(Godot.StringName @message, Godot.StringName @plural_message, int @n, Godot.StringName @context = null)
	{
		@context ??= "";
		return _object.TrN(@message, @plural_message, @n, @context);
	}

	public Godot.StringName GetTranslationDomain()
	{
		return _object.GetTranslationDomain();
	}

	public void SetTranslationDomain(Godot.StringName @domain)
	{
		_object.SetTranslationDomain(@domain);
	}

	public bool IsQueuedForDeletion()
	{
		return _object.IsQueuedForDeletion();
	}

	public void CancelFree()
	{
		_object.CancelFree();
	}

	#endregion

	#region Inherited Signals

	public event Action ScriptChangedEvent
	{
		add
		{
			Connect(SignalName.ScriptChanged, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.ScriptChanged, Callable.From(value));
		}
	}

	public event Action PropertyListChangedEvent
	{
		add
		{
			Connect(SignalName.PropertyListChanged, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.PropertyListChanged, Callable.From(value));
		}
	}

	#endregion
}
