// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;
using Object = Godot.GodotObject;

namespace GDExtensionBindgen;

public class JoltConeTwistJoint3D : JoltJoint3D
{
	public JoltConeTwistJoint3D() : base(NativeName)
	{
	}
	protected JoltConeTwistJoint3D(StringName @class) : base(@class)
	{
	}
	protected JoltConeTwistJoint3D(Variant variant) : base(variant)
	{
	}
	protected JoltConeTwistJoint3D([NotNull] Node3D @object) : base(@object)
	{
	}

	public static implicit operator Node3D(JoltConeTwistJoint3D self) => self?._object;
	public static implicit operator Variant(JoltConeTwistJoint3D self) => self?._object;
	public static explicit operator JoltConeTwistJoint3D(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public new class PropertyName : JoltJoint3D.PropertyName
	{
		public static readonly StringName SwingLimitEnabled = "swing_limit_enabled";
		public static readonly StringName SwingLimitSpan = "swing_limit_span";
		public static readonly StringName TwistLimitEnabled = "twist_limit_enabled";
		public static readonly StringName TwistLimitSpan = "twist_limit_span";
		public static readonly StringName SwingMotorEnabled = "swing_motor_enabled";
		public static readonly StringName SwingMotorTargetVelocityY = "swing_motor_target_velocity_y";
		public static readonly StringName SwingMotorTargetVelocityZ = "swing_motor_target_velocity_z";
		public static readonly StringName SwingMotorMaxTorque = "swing_motor_max_torque";
		public static readonly StringName TwistMotorEnabled = "twist_motor_enabled";
		public static readonly StringName TwistMotorTargetVelocity = "twist_motor_target_velocity";
		public static readonly StringName TwistMotorMaxTorque = "twist_motor_max_torque";
	}

	public new class MethodName : JoltJoint3D.MethodName
	{
		public static readonly StringName GetSwingLimitEnabled = "get_swing_limit_enabled";
		public static readonly StringName SetSwingLimitEnabled = "set_swing_limit_enabled";
		public static readonly StringName GetTwistLimitEnabled = "get_twist_limit_enabled";
		public static readonly StringName SetTwistLimitEnabled = "set_twist_limit_enabled";
		public static readonly StringName GetSwingLimitSpan = "get_swing_limit_span";
		public static readonly StringName SetSwingLimitSpan = "set_swing_limit_span";
		public static readonly StringName GetTwistLimitSpan = "get_twist_limit_span";
		public static readonly StringName SetTwistLimitSpan = "set_twist_limit_span";
		public static readonly StringName GetSwingMotorEnabled = "get_swing_motor_enabled";
		public static readonly StringName SetSwingMotorEnabled = "set_swing_motor_enabled";
		public static readonly StringName GetTwistMotorEnabled = "get_twist_motor_enabled";
		public static readonly StringName SetTwistMotorEnabled = "set_twist_motor_enabled";
		public static readonly StringName GetSwingMotorTargetVelocityY = "get_swing_motor_target_velocity_y";
		public static readonly StringName SetSwingMotorTargetVelocityY = "set_swing_motor_target_velocity_y";
		public static readonly StringName GetSwingMotorTargetVelocityZ = "get_swing_motor_target_velocity_z";
		public static readonly StringName SetSwingMotorTargetVelocityZ = "set_swing_motor_target_velocity_z";
		public static readonly StringName GetTwistMotorTargetVelocity = "get_twist_motor_target_velocity";
		public static readonly StringName SetTwistMotorTargetVelocity = "set_twist_motor_target_velocity";
		public static readonly StringName GetSwingMotorMaxTorque = "get_swing_motor_max_torque";
		public static readonly StringName SetSwingMotorMaxTorque = "set_swing_motor_max_torque";
		public static readonly StringName GetTwistMotorMaxTorque = "get_twist_motor_max_torque";
		public static readonly StringName SetTwistMotorMaxTorque = "set_twist_motor_max_torque";
		public static readonly StringName GetAppliedForce = "get_applied_force";
		public static readonly StringName GetAppliedTorque = "get_applied_torque";
	}

	public new class SignalName : JoltJoint3D.SignalName
	{

	}

	private static readonly StringName NativeName = "JoltConeTwistJoint3D";

	#region Properties

	public bool SwingLimitEnabled
	{
		get => (bool)_object.Get(PropertyName.SwingLimitEnabled);
		set => _object.Set(PropertyName.SwingLimitEnabled, value);
	}

	public float SwingLimitSpan
	{
		get => (float)_object.Get(PropertyName.SwingLimitSpan);
		set => _object.Set(PropertyName.SwingLimitSpan, value);
	}

	public bool TwistLimitEnabled
	{
		get => (bool)_object.Get(PropertyName.TwistLimitEnabled);
		set => _object.Set(PropertyName.TwistLimitEnabled, value);
	}

	public float TwistLimitSpan
	{
		get => (float)_object.Get(PropertyName.TwistLimitSpan);
		set => _object.Set(PropertyName.TwistLimitSpan, value);
	}

	public bool SwingMotorEnabled
	{
		get => (bool)_object.Get(PropertyName.SwingMotorEnabled);
		set => _object.Set(PropertyName.SwingMotorEnabled, value);
	}

	public float SwingMotorTargetVelocityY
	{
		get => (float)_object.Get(PropertyName.SwingMotorTargetVelocityY);
		set => _object.Set(PropertyName.SwingMotorTargetVelocityY, value);
	}

	public float SwingMotorTargetVelocityZ
	{
		get => (float)_object.Get(PropertyName.SwingMotorTargetVelocityZ);
		set => _object.Set(PropertyName.SwingMotorTargetVelocityZ, value);
	}

	public float SwingMotorMaxTorque
	{
		get => (float)_object.Get(PropertyName.SwingMotorMaxTorque);
		set => _object.Set(PropertyName.SwingMotorMaxTorque, value);
	}

	public bool TwistMotorEnabled
	{
		get => (bool)_object.Get(PropertyName.TwistMotorEnabled);
		set => _object.Set(PropertyName.TwistMotorEnabled, value);
	}

	public float TwistMotorTargetVelocity
	{
		get => (float)_object.Get(PropertyName.TwistMotorTargetVelocity);
		set => _object.Set(PropertyName.TwistMotorTargetVelocity, value);
	}

	public float TwistMotorMaxTorque
	{
		get => (float)_object.Get(PropertyName.TwistMotorMaxTorque);
		set => _object.Set(PropertyName.TwistMotorMaxTorque, value);
	}

	#endregion

	#region Methods

	public bool GetSwingLimitEnabled()
	{
		return (bool)_object.Call(MethodName.GetSwingLimitEnabled);
	}

	public void SetSwingLimitEnabled(bool @enabled)
	{
		_object.Call(MethodName.SetSwingLimitEnabled, @enabled);
	}

	public bool GetTwistLimitEnabled()
	{
		return (bool)_object.Call(MethodName.GetTwistLimitEnabled);
	}

	public void SetTwistLimitEnabled(bool @enabled)
	{
		_object.Call(MethodName.SetTwistLimitEnabled, @enabled);
	}

	public float GetSwingLimitSpan()
	{
		return (float)_object.Call(MethodName.GetSwingLimitSpan);
	}

	public void SetSwingLimitSpan(float @value)
	{
		_object.Call(MethodName.SetSwingLimitSpan, @value);
	}

	public float GetTwistLimitSpan()
	{
		return (float)_object.Call(MethodName.GetTwistLimitSpan);
	}

	public void SetTwistLimitSpan(float @value)
	{
		_object.Call(MethodName.SetTwistLimitSpan, @value);
	}

	public bool GetSwingMotorEnabled()
	{
		return (bool)_object.Call(MethodName.GetSwingMotorEnabled);
	}

	public void SetSwingMotorEnabled(bool @enabled)
	{
		_object.Call(MethodName.SetSwingMotorEnabled, @enabled);
	}

	public bool GetTwistMotorEnabled()
	{
		return (bool)_object.Call(MethodName.GetTwistMotorEnabled);
	}

	public void SetTwistMotorEnabled(bool @enabled)
	{
		_object.Call(MethodName.SetTwistMotorEnabled, @enabled);
	}

	public float GetSwingMotorTargetVelocityY()
	{
		return (float)_object.Call(MethodName.GetSwingMotorTargetVelocityY);
	}

	public void SetSwingMotorTargetVelocityY(float @value)
	{
		_object.Call(MethodName.SetSwingMotorTargetVelocityY, @value);
	}

	public float GetSwingMotorTargetVelocityZ()
	{
		return (float)_object.Call(MethodName.GetSwingMotorTargetVelocityZ);
	}

	public void SetSwingMotorTargetVelocityZ(float @value)
	{
		_object.Call(MethodName.SetSwingMotorTargetVelocityZ, @value);
	}

	public float GetTwistMotorTargetVelocity()
	{
		return (float)_object.Call(MethodName.GetTwistMotorTargetVelocity);
	}

	public void SetTwistMotorTargetVelocity(float @value)
	{
		_object.Call(MethodName.SetTwistMotorTargetVelocity, @value);
	}

	public float GetSwingMotorMaxTorque()
	{
		return (float)_object.Call(MethodName.GetSwingMotorMaxTorque);
	}

	public void SetSwingMotorMaxTorque(float @value)
	{
		_object.Call(MethodName.SetSwingMotorMaxTorque, @value);
	}

	public float GetTwistMotorMaxTorque()
	{
		return (float)_object.Call(MethodName.GetTwistMotorMaxTorque);
	}

	public void SetTwistMotorMaxTorque(float @value)
	{
		_object.Call(MethodName.SetTwistMotorMaxTorque, @value);
	}

	public float GetAppliedForce()
	{
		return (float)_object.Call(MethodName.GetAppliedForce);
	}

	public float GetAppliedTorque()
	{
		return (float)_object.Call(MethodName.GetAppliedTorque);
	}

	#endregion
}
