// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;
using Object = Godot.GodotObject;

namespace GDExtensionBindgen;

public class JoltGeneric6DOFJoint3D : JoltJoint3D
{
	public JoltGeneric6DOFJoint3D() : base(NativeName)
	{
	}
	protected JoltGeneric6DOFJoint3D(StringName @class) : base(@class)
	{
	}
	protected JoltGeneric6DOFJoint3D(Variant variant) : base(variant)
	{
	}
	protected JoltGeneric6DOFJoint3D([NotNull] Node3D @object) : base(@object)
	{
	}

	public static implicit operator Node3D(JoltGeneric6DOFJoint3D self) => self?._object;
	public static implicit operator Variant(JoltGeneric6DOFJoint3D self) => self?._object;
	public static explicit operator JoltGeneric6DOFJoint3D(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public new class PropertyName : JoltJoint3D.PropertyName
	{
		public static readonly StringName LinearLimitX/enabled = "linear_limit_x/enabled";
		public static readonly StringName LinearLimitX/upper = "linear_limit_x/upper";
		public static readonly StringName LinearLimitX/lower = "linear_limit_x/lower";
		public static readonly StringName LinearLimitY/enabled = "linear_limit_y/enabled";
		public static readonly StringName LinearLimitY/upper = "linear_limit_y/upper";
		public static readonly StringName LinearLimitY/lower = "linear_limit_y/lower";
		public static readonly StringName LinearLimitZ/enabled = "linear_limit_z/enabled";
		public static readonly StringName LinearLimitZ/upper = "linear_limit_z/upper";
		public static readonly StringName LinearLimitZ/lower = "linear_limit_z/lower";
		public static readonly StringName LinearLimitSpringX/enabled = "linear_limit_spring_x/enabled";
		public static readonly StringName LinearLimitSpringX/frequency = "linear_limit_spring_x/frequency";
		public static readonly StringName LinearLimitSpringX/damping = "linear_limit_spring_x/damping";
		public static readonly StringName LinearLimitSpringY/enabled = "linear_limit_spring_y/enabled";
		public static readonly StringName LinearLimitSpringY/frequency = "linear_limit_spring_y/frequency";
		public static readonly StringName LinearLimitSpringY/damping = "linear_limit_spring_y/damping";
		public static readonly StringName LinearLimitSpringZ/enabled = "linear_limit_spring_z/enabled";
		public static readonly StringName LinearLimitSpringZ/frequency = "linear_limit_spring_z/frequency";
		public static readonly StringName LinearLimitSpringZ/damping = "linear_limit_spring_z/damping";
		public static readonly StringName LinearMotorX/enabled = "linear_motor_x/enabled";
		public static readonly StringName LinearMotorX/targetVelocity = "linear_motor_x/target_velocity";
		public static readonly StringName LinearMotorX/maxForce = "linear_motor_x/max_force";
		public static readonly StringName LinearMotorY/enabled = "linear_motor_y/enabled";
		public static readonly StringName LinearMotorY/targetVelocity = "linear_motor_y/target_velocity";
		public static readonly StringName LinearMotorY/maxForce = "linear_motor_y/max_force";
		public static readonly StringName LinearMotorZ/enabled = "linear_motor_z/enabled";
		public static readonly StringName LinearMotorZ/targetVelocity = "linear_motor_z/target_velocity";
		public static readonly StringName LinearMotorZ/maxForce = "linear_motor_z/max_force";
		public static readonly StringName LinearSpringX/enabled = "linear_spring_x/enabled";
		public static readonly StringName LinearSpringX/frequency = "linear_spring_x/frequency";
		public static readonly StringName LinearSpringX/damping = "linear_spring_x/damping";
		public static readonly StringName LinearSpringX/equilibriumPoint = "linear_spring_x/equilibrium_point";
		public static readonly StringName LinearSpringX/maxForce = "linear_spring_x/max_force";
		public static readonly StringName LinearSpringY/enabled = "linear_spring_y/enabled";
		public static readonly StringName LinearSpringY/frequency = "linear_spring_y/frequency";
		public static readonly StringName LinearSpringY/damping = "linear_spring_y/damping";
		public static readonly StringName LinearSpringY/equilibriumPoint = "linear_spring_y/equilibrium_point";
		public static readonly StringName LinearSpringY/maxForce = "linear_spring_y/max_force";
		public static readonly StringName LinearSpringZ/enabled = "linear_spring_z/enabled";
		public static readonly StringName LinearSpringZ/frequency = "linear_spring_z/frequency";
		public static readonly StringName LinearSpringZ/damping = "linear_spring_z/damping";
		public static readonly StringName LinearSpringZ/equilibriumPoint = "linear_spring_z/equilibrium_point";
		public static readonly StringName LinearSpringZ/maxForce = "linear_spring_z/max_force";
		public static readonly StringName AngularLimitX/enabled = "angular_limit_x/enabled";
		public static readonly StringName AngularLimitX/upper = "angular_limit_x/upper";
		public static readonly StringName AngularLimitX/lower = "angular_limit_x/lower";
		public static readonly StringName AngularLimitY/enabled = "angular_limit_y/enabled";
		public static readonly StringName AngularLimitY/upper = "angular_limit_y/upper";
		public static readonly StringName AngularLimitY/lower = "angular_limit_y/lower";
		public static readonly StringName AngularLimitZ/enabled = "angular_limit_z/enabled";
		public static readonly StringName AngularLimitZ/upper = "angular_limit_z/upper";
		public static readonly StringName AngularLimitZ/lower = "angular_limit_z/lower";
		public static readonly StringName AngularMotorX/enabled = "angular_motor_x/enabled";
		public static readonly StringName AngularMotorX/targetVelocity = "angular_motor_x/target_velocity";
		public static readonly StringName AngularMotorX/maxTorque = "angular_motor_x/max_torque";
		public static readonly StringName AngularMotorY/enabled = "angular_motor_y/enabled";
		public static readonly StringName AngularMotorY/targetVelocity = "angular_motor_y/target_velocity";
		public static readonly StringName AngularMotorY/maxTorque = "angular_motor_y/max_torque";
		public static readonly StringName AngularMotorZ/enabled = "angular_motor_z/enabled";
		public static readonly StringName AngularMotorZ/targetVelocity = "angular_motor_z/target_velocity";
		public static readonly StringName AngularMotorZ/maxTorque = "angular_motor_z/max_torque";
		public static readonly StringName AngularSpringX/enabled = "angular_spring_x/enabled";
		public static readonly StringName AngularSpringX/frequency = "angular_spring_x/frequency";
		public static readonly StringName AngularSpringX/damping = "angular_spring_x/damping";
		public static readonly StringName AngularSpringX/equilibriumPoint = "angular_spring_x/equilibrium_point";
		public static readonly StringName AngularSpringX/maxTorque = "angular_spring_x/max_torque";
		public static readonly StringName AngularSpringY/enabled = "angular_spring_y/enabled";
		public static readonly StringName AngularSpringY/frequency = "angular_spring_y/frequency";
		public static readonly StringName AngularSpringY/damping = "angular_spring_y/damping";
		public static readonly StringName AngularSpringY/equilibriumPoint = "angular_spring_y/equilibrium_point";
		public static readonly StringName AngularSpringY/maxTorque = "angular_spring_y/max_torque";
		public static readonly StringName AngularSpringZ/enabled = "angular_spring_z/enabled";
		public static readonly StringName AngularSpringZ/frequency = "angular_spring_z/frequency";
		public static readonly StringName AngularSpringZ/damping = "angular_spring_z/damping";
		public static readonly StringName AngularSpringZ/equilibriumPoint = "angular_spring_z/equilibrium_point";
		public static readonly StringName AngularSpringZ/maxTorque = "angular_spring_z/max_torque";
	}

	public new class MethodName : JoltJoint3D.MethodName
	{
		public static readonly StringName GetParamX = "get_param_x";
		public static readonly StringName SetParamX = "set_param_x";
		public static readonly StringName GetParamY = "get_param_y";
		public static readonly StringName SetParamY = "set_param_y";
		public static readonly StringName GetParamZ = "get_param_z";
		public static readonly StringName SetParamZ = "set_param_z";
		public static readonly StringName GetFlagX = "get_flag_x";
		public static readonly StringName SetFlagX = "set_flag_x";
		public static readonly StringName GetFlagY = "get_flag_y";
		public static readonly StringName SetFlagY = "set_flag_y";
		public static readonly StringName GetFlagZ = "get_flag_z";
		public static readonly StringName SetFlagZ = "set_flag_z";
		public static readonly StringName GetLinearLimitXUpper = "get_linear_limit_x_upper";
		public static readonly StringName SetLinearLimitXUpper = "set_linear_limit_x_upper";
		public static readonly StringName GetLinearLimitXLower = "get_linear_limit_x_lower";
		public static readonly StringName SetLinearLimitXLower = "set_linear_limit_x_lower";
		public static readonly StringName GetLinearLimitYUpper = "get_linear_limit_y_upper";
		public static readonly StringName SetLinearLimitYUpper = "set_linear_limit_y_upper";
		public static readonly StringName GetLinearLimitYLower = "get_linear_limit_y_lower";
		public static readonly StringName SetLinearLimitYLower = "set_linear_limit_y_lower";
		public static readonly StringName GetLinearLimitZUpper = "get_linear_limit_z_upper";
		public static readonly StringName SetLinearLimitZUpper = "set_linear_limit_z_upper";
		public static readonly StringName GetLinearLimitZLower = "get_linear_limit_z_lower";
		public static readonly StringName SetLinearLimitZLower = "set_linear_limit_z_lower";
		public static readonly StringName GetLinearLimitSpringXFrequency = "get_linear_limit_spring_x_frequency";
		public static readonly StringName SetLinearLimitSpringXFrequency = "set_linear_limit_spring_x_frequency";
		public static readonly StringName GetLinearLimitSpringXDamping = "get_linear_limit_spring_x_damping";
		public static readonly StringName SetLinearLimitSpringXDamping = "set_linear_limit_spring_x_damping";
		public static readonly StringName GetLinearLimitSpringYFrequency = "get_linear_limit_spring_y_frequency";
		public static readonly StringName SetLinearLimitSpringYFrequency = "set_linear_limit_spring_y_frequency";
		public static readonly StringName GetLinearLimitSpringYDamping = "get_linear_limit_spring_y_damping";
		public static readonly StringName SetLinearLimitSpringYDamping = "set_linear_limit_spring_y_damping";
		public static readonly StringName GetLinearLimitSpringZFrequency = "get_linear_limit_spring_z_frequency";
		public static readonly StringName SetLinearLimitSpringZFrequency = "set_linear_limit_spring_z_frequency";
		public static readonly StringName GetLinearLimitSpringZDamping = "get_linear_limit_spring_z_damping";
		public static readonly StringName SetLinearLimitSpringZDamping = "set_linear_limit_spring_z_damping";
		public static readonly StringName GetLinearMotorXTargetVelocity = "get_linear_motor_x_target_velocity";
		public static readonly StringName SetLinearMotorXTargetVelocity = "set_linear_motor_x_target_velocity";
		public static readonly StringName GetLinearMotorXMaxForce = "get_linear_motor_x_max_force";
		public static readonly StringName SetLinearMotorXMaxForce = "set_linear_motor_x_max_force";
		public static readonly StringName GetLinearMotorYTargetVelocity = "get_linear_motor_y_target_velocity";
		public static readonly StringName SetLinearMotorYTargetVelocity = "set_linear_motor_y_target_velocity";
		public static readonly StringName GetLinearMotorYMaxForce = "get_linear_motor_y_max_force";
		public static readonly StringName SetLinearMotorYMaxForce = "set_linear_motor_y_max_force";
		public static readonly StringName GetLinearMotorZTargetVelocity = "get_linear_motor_z_target_velocity";
		public static readonly StringName SetLinearMotorZTargetVelocity = "set_linear_motor_z_target_velocity";
		public static readonly StringName GetLinearMotorZMaxForce = "get_linear_motor_z_max_force";
		public static readonly StringName SetLinearMotorZMaxForce = "set_linear_motor_z_max_force";
		public static readonly StringName GetLinearSpringXFrequency = "get_linear_spring_x_frequency";
		public static readonly StringName SetLinearSpringXFrequency = "set_linear_spring_x_frequency";
		public static readonly StringName GetLinearSpringXDamping = "get_linear_spring_x_damping";
		public static readonly StringName SetLinearSpringXDamping = "set_linear_spring_x_damping";
		public static readonly StringName GetLinearSpringXEquilibriumPoint = "get_linear_spring_x_equilibrium_point";
		public static readonly StringName SetLinearSpringXEquilibriumPoint = "set_linear_spring_x_equilibrium_point";
		public static readonly StringName GetLinearSpringXMaxForce = "get_linear_spring_x_max_force";
		public static readonly StringName SetLinearSpringXMaxForce = "set_linear_spring_x_max_force";
		public static readonly StringName GetLinearSpringYFrequency = "get_linear_spring_y_frequency";
		public static readonly StringName SetLinearSpringYFrequency = "set_linear_spring_y_frequency";
		public static readonly StringName GetLinearSpringYDamping = "get_linear_spring_y_damping";
		public static readonly StringName SetLinearSpringYDamping = "set_linear_spring_y_damping";
		public static readonly StringName GetLinearSpringYEquilibriumPoint = "get_linear_spring_y_equilibrium_point";
		public static readonly StringName SetLinearSpringYEquilibriumPoint = "set_linear_spring_y_equilibrium_point";
		public static readonly StringName GetLinearSpringYMaxForce = "get_linear_spring_y_max_force";
		public static readonly StringName SetLinearSpringYMaxForce = "set_linear_spring_y_max_force";
		public static readonly StringName GetLinearSpringZFrequency = "get_linear_spring_z_frequency";
		public static readonly StringName SetLinearSpringZFrequency = "set_linear_spring_z_frequency";
		public static readonly StringName GetLinearSpringZDamping = "get_linear_spring_z_damping";
		public static readonly StringName SetLinearSpringZDamping = "set_linear_spring_z_damping";
		public static readonly StringName GetLinearSpringZEquilibriumPoint = "get_linear_spring_z_equilibrium_point";
		public static readonly StringName SetLinearSpringZEquilibriumPoint = "set_linear_spring_z_equilibrium_point";
		public static readonly StringName GetLinearSpringZMaxForce = "get_linear_spring_z_max_force";
		public static readonly StringName SetLinearSpringZMaxForce = "set_linear_spring_z_max_force";
		public static readonly StringName GetLinearLimitXEnabled = "get_linear_limit_x_enabled";
		public static readonly StringName SetLinearLimitXEnabled = "set_linear_limit_x_enabled";
		public static readonly StringName GetLinearLimitYEnabled = "get_linear_limit_y_enabled";
		public static readonly StringName SetLinearLimitYEnabled = "set_linear_limit_y_enabled";
		public static readonly StringName GetLinearLimitZEnabled = "get_linear_limit_z_enabled";
		public static readonly StringName SetLinearLimitZEnabled = "set_linear_limit_z_enabled";
		public static readonly StringName GetLinearLimitSpringXEnabled = "get_linear_limit_spring_x_enabled";
		public static readonly StringName SetLinearLimitSpringXEnabled = "set_linear_limit_spring_x_enabled";
		public static readonly StringName GetLinearLimitSpringYEnabled = "get_linear_limit_spring_y_enabled";
		public static readonly StringName SetLinearLimitSpringYEnabled = "set_linear_limit_spring_y_enabled";
		public static readonly StringName GetLinearLimitSpringZEnabled = "get_linear_limit_spring_z_enabled";
		public static readonly StringName SetLinearLimitSpringZEnabled = "set_linear_limit_spring_z_enabled";
		public static readonly StringName GetLinearMotorXEnabled = "get_linear_motor_x_enabled";
		public static readonly StringName SetLinearMotorXEnabled = "set_linear_motor_x_enabled";
		public static readonly StringName GetLinearMotorYEnabled = "get_linear_motor_y_enabled";
		public static readonly StringName SetLinearMotorYEnabled = "set_linear_motor_y_enabled";
		public static readonly StringName GetLinearMotorZEnabled = "get_linear_motor_z_enabled";
		public static readonly StringName SetLinearMotorZEnabled = "set_linear_motor_z_enabled";
		public static readonly StringName GetLinearSpringXEnabled = "get_linear_spring_x_enabled";
		public static readonly StringName SetLinearSpringXEnabled = "set_linear_spring_x_enabled";
		public static readonly StringName GetLinearSpringYEnabled = "get_linear_spring_y_enabled";
		public static readonly StringName SetLinearSpringYEnabled = "set_linear_spring_y_enabled";
		public static readonly StringName GetLinearSpringZEnabled = "get_linear_spring_z_enabled";
		public static readonly StringName SetLinearSpringZEnabled = "set_linear_spring_z_enabled";
		public static readonly StringName GetAngularLimitXUpper = "get_angular_limit_x_upper";
		public static readonly StringName SetAngularLimitXUpper = "set_angular_limit_x_upper";
		public static readonly StringName GetAngularLimitXLower = "get_angular_limit_x_lower";
		public static readonly StringName SetAngularLimitXLower = "set_angular_limit_x_lower";
		public static readonly StringName GetAngularLimitYUpper = "get_angular_limit_y_upper";
		public static readonly StringName SetAngularLimitYUpper = "set_angular_limit_y_upper";
		public static readonly StringName GetAngularLimitYLower = "get_angular_limit_y_lower";
		public static readonly StringName SetAngularLimitYLower = "set_angular_limit_y_lower";
		public static readonly StringName GetAngularLimitZUpper = "get_angular_limit_z_upper";
		public static readonly StringName SetAngularLimitZUpper = "set_angular_limit_z_upper";
		public static readonly StringName GetAngularLimitZLower = "get_angular_limit_z_lower";
		public static readonly StringName SetAngularLimitZLower = "set_angular_limit_z_lower";
		public static readonly StringName GetAngularMotorXTargetVelocity = "get_angular_motor_x_target_velocity";
		public static readonly StringName SetAngularMotorXTargetVelocity = "set_angular_motor_x_target_velocity";
		public static readonly StringName GetAngularMotorXMaxTorque = "get_angular_motor_x_max_torque";
		public static readonly StringName SetAngularMotorXMaxTorque = "set_angular_motor_x_max_torque";
		public static readonly StringName GetAngularMotorYTargetVelocity = "get_angular_motor_y_target_velocity";
		public static readonly StringName SetAngularMotorYTargetVelocity = "set_angular_motor_y_target_velocity";
		public static readonly StringName GetAngularMotorYMaxTorque = "get_angular_motor_y_max_torque";
		public static readonly StringName SetAngularMotorYMaxTorque = "set_angular_motor_y_max_torque";
		public static readonly StringName GetAngularMotorZTargetVelocity = "get_angular_motor_z_target_velocity";
		public static readonly StringName SetAngularMotorZTargetVelocity = "set_angular_motor_z_target_velocity";
		public static readonly StringName GetAngularMotorZMaxTorque = "get_angular_motor_z_max_torque";
		public static readonly StringName SetAngularMotorZMaxTorque = "set_angular_motor_z_max_torque";
		public static readonly StringName GetAngularSpringXFrequency = "get_angular_spring_x_frequency";
		public static readonly StringName SetAngularSpringXFrequency = "set_angular_spring_x_frequency";
		public static readonly StringName GetAngularSpringXDamping = "get_angular_spring_x_damping";
		public static readonly StringName SetAngularSpringXDamping = "set_angular_spring_x_damping";
		public static readonly StringName GetAngularSpringXEquilibriumPoint = "get_angular_spring_x_equilibrium_point";
		public static readonly StringName SetAngularSpringXEquilibriumPoint = "set_angular_spring_x_equilibrium_point";
		public static readonly StringName GetAngularSpringXMaxTorque = "get_angular_spring_x_max_torque";
		public static readonly StringName SetAngularSpringXMaxTorque = "set_angular_spring_x_max_torque";
		public static readonly StringName GetAngularSpringYFrequency = "get_angular_spring_y_frequency";
		public static readonly StringName SetAngularSpringYFrequency = "set_angular_spring_y_frequency";
		public static readonly StringName GetAngularSpringYDamping = "get_angular_spring_y_damping";
		public static readonly StringName SetAngularSpringYDamping = "set_angular_spring_y_damping";
		public static readonly StringName GetAngularSpringYEquilibriumPoint = "get_angular_spring_y_equilibrium_point";
		public static readonly StringName SetAngularSpringYEquilibriumPoint = "set_angular_spring_y_equilibrium_point";
		public static readonly StringName GetAngularSpringYMaxTorque = "get_angular_spring_y_max_torque";
		public static readonly StringName SetAngularSpringYMaxTorque = "set_angular_spring_y_max_torque";
		public static readonly StringName GetAngularSpringZFrequency = "get_angular_spring_z_frequency";
		public static readonly StringName SetAngularSpringZFrequency = "set_angular_spring_z_frequency";
		public static readonly StringName GetAngularSpringZDamping = "get_angular_spring_z_damping";
		public static readonly StringName SetAngularSpringZDamping = "set_angular_spring_z_damping";
		public static readonly StringName GetAngularSpringZEquilibriumPoint = "get_angular_spring_z_equilibrium_point";
		public static readonly StringName SetAngularSpringZEquilibriumPoint = "set_angular_spring_z_equilibrium_point";
		public static readonly StringName GetAngularSpringZMaxTorque = "get_angular_spring_z_max_torque";
		public static readonly StringName SetAngularSpringZMaxTorque = "set_angular_spring_z_max_torque";
		public static readonly StringName GetAngularLimitXEnabled = "get_angular_limit_x_enabled";
		public static readonly StringName SetAngularLimitXEnabled = "set_angular_limit_x_enabled";
		public static readonly StringName GetAngularLimitYEnabled = "get_angular_limit_y_enabled";
		public static readonly StringName SetAngularLimitYEnabled = "set_angular_limit_y_enabled";
		public static readonly StringName GetAngularLimitZEnabled = "get_angular_limit_z_enabled";
		public static readonly StringName SetAngularLimitZEnabled = "set_angular_limit_z_enabled";
		public static readonly StringName GetAngularMotorXEnabled = "get_angular_motor_x_enabled";
		public static readonly StringName SetAngularMotorXEnabled = "set_angular_motor_x_enabled";
		public static readonly StringName GetAngularMotorYEnabled = "get_angular_motor_y_enabled";
		public static readonly StringName SetAngularMotorYEnabled = "set_angular_motor_y_enabled";
		public static readonly StringName GetAngularMotorZEnabled = "get_angular_motor_z_enabled";
		public static readonly StringName SetAngularMotorZEnabled = "set_angular_motor_z_enabled";
		public static readonly StringName GetAngularSpringXEnabled = "get_angular_spring_x_enabled";
		public static readonly StringName SetAngularSpringXEnabled = "set_angular_spring_x_enabled";
		public static readonly StringName GetAngularSpringYEnabled = "get_angular_spring_y_enabled";
		public static readonly StringName SetAngularSpringYEnabled = "set_angular_spring_y_enabled";
		public static readonly StringName GetAngularSpringZEnabled = "get_angular_spring_z_enabled";
		public static readonly StringName SetAngularSpringZEnabled = "set_angular_spring_z_enabled";
		public static readonly StringName GetAppliedForce = "get_applied_force";
		public static readonly StringName GetAppliedTorque = "get_applied_torque";
	}

	public new class SignalName : JoltJoint3D.SignalName
	{

	}

	private static readonly StringName NativeName = "JoltGeneric6DOFJoint3D";

	#region Enums

	public enum Param : long
	{
		ParamLinearLimitUpper = 1L,
		ParamLinearLimitLower = 0L,
		ParamLinearLimitSpringFrequency = 101L,
		ParamLinearLimitSpringDamping = 102L,
		ParamLinearMotorTargetVelocity = 5L,
		ParamLinearMotorMaxForce = 6L,
		ParamLinearSpringFrequency = 100L,
		ParamLinearSpringDamping = 8L,
		ParamLinearSpringEquilibriumPoint = 9L,
		ParamLinearSpringMaxForce = 104L,
		ParamAngularLimitUpper = 11L,
		ParamAngularLimitLower = 10L,
		ParamAngularMotorTargetVelocity = 17L,
		ParamAngularMotorMaxTorque = 18L,
		ParamAngularSpringFrequency = 103L,
		ParamAngularSpringDamping = 20L,
		ParamAngularSpringEquilibriumPoint = 21L,
		ParamAngularSpringMaxTorque = 105L,
	}

	public enum Flag : long
	{
		FlagEnableLinearLimit = 0L,
		FlagEnableLinearLimitSpring = 100L,
		FlagEnableLinearMotor = 5L,
		FlagEnableLinearSpring = 3L,
		FlagEnableAngularLimit = 1L,
		FlagEnableAngularMotor = 4L,
		FlagEnableAngularSpring = 2L,
	}

	#endregion

	#region Properties

	public bool LinearLimitX/enabled
	{
		get => (bool)_object.Get(PropertyName.LinearLimitX/enabled);
		set => _object.Set(PropertyName.LinearLimitX/enabled, value);
	}

	public float LinearLimitX/upper
	{
		get => (float)_object.Get(PropertyName.LinearLimitX/upper);
		set => _object.Set(PropertyName.LinearLimitX/upper, value);
	}

	public float LinearLimitX/lower
	{
		get => (float)_object.Get(PropertyName.LinearLimitX/lower);
		set => _object.Set(PropertyName.LinearLimitX/lower, value);
	}

	public bool LinearLimitY/enabled
	{
		get => (bool)_object.Get(PropertyName.LinearLimitY/enabled);
		set => _object.Set(PropertyName.LinearLimitY/enabled, value);
	}

	public float LinearLimitY/upper
	{
		get => (float)_object.Get(PropertyName.LinearLimitY/upper);
		set => _object.Set(PropertyName.LinearLimitY/upper, value);
	}

	public float LinearLimitY/lower
	{
		get => (float)_object.Get(PropertyName.LinearLimitY/lower);
		set => _object.Set(PropertyName.LinearLimitY/lower, value);
	}

	public bool LinearLimitZ/enabled
	{
		get => (bool)_object.Get(PropertyName.LinearLimitZ/enabled);
		set => _object.Set(PropertyName.LinearLimitZ/enabled, value);
	}

	public float LinearLimitZ/upper
	{
		get => (float)_object.Get(PropertyName.LinearLimitZ/upper);
		set => _object.Set(PropertyName.LinearLimitZ/upper, value);
	}

	public float LinearLimitZ/lower
	{
		get => (float)_object.Get(PropertyName.LinearLimitZ/lower);
		set => _object.Set(PropertyName.LinearLimitZ/lower, value);
	}

	public bool LinearLimitSpringX/enabled
	{
		get => (bool)_object.Get(PropertyName.LinearLimitSpringX/enabled);
		set => _object.Set(PropertyName.LinearLimitSpringX/enabled, value);
	}

	public float LinearLimitSpringX/frequency
	{
		get => (float)_object.Get(PropertyName.LinearLimitSpringX/frequency);
		set => _object.Set(PropertyName.LinearLimitSpringX/frequency, value);
	}

	public float LinearLimitSpringX/damping
	{
		get => (float)_object.Get(PropertyName.LinearLimitSpringX/damping);
		set => _object.Set(PropertyName.LinearLimitSpringX/damping, value);
	}

	public bool LinearLimitSpringY/enabled
	{
		get => (bool)_object.Get(PropertyName.LinearLimitSpringY/enabled);
		set => _object.Set(PropertyName.LinearLimitSpringY/enabled, value);
	}

	public float LinearLimitSpringY/frequency
	{
		get => (float)_object.Get(PropertyName.LinearLimitSpringY/frequency);
		set => _object.Set(PropertyName.LinearLimitSpringY/frequency, value);
	}

	public float LinearLimitSpringY/damping
	{
		get => (float)_object.Get(PropertyName.LinearLimitSpringY/damping);
		set => _object.Set(PropertyName.LinearLimitSpringY/damping, value);
	}

	public bool LinearLimitSpringZ/enabled
	{
		get => (bool)_object.Get(PropertyName.LinearLimitSpringZ/enabled);
		set => _object.Set(PropertyName.LinearLimitSpringZ/enabled, value);
	}

	public float LinearLimitSpringZ/frequency
	{
		get => (float)_object.Get(PropertyName.LinearLimitSpringZ/frequency);
		set => _object.Set(PropertyName.LinearLimitSpringZ/frequency, value);
	}

	public float LinearLimitSpringZ/damping
	{
		get => (float)_object.Get(PropertyName.LinearLimitSpringZ/damping);
		set => _object.Set(PropertyName.LinearLimitSpringZ/damping, value);
	}

	public bool LinearMotorX/enabled
	{
		get => (bool)_object.Get(PropertyName.LinearMotorX/enabled);
		set => _object.Set(PropertyName.LinearMotorX/enabled, value);
	}

	public float LinearMotorX/targetVelocity
	{
		get => (float)_object.Get(PropertyName.LinearMotorX/targetVelocity);
		set => _object.Set(PropertyName.LinearMotorX/targetVelocity, value);
	}

	public float LinearMotorX/maxForce
	{
		get => (float)_object.Get(PropertyName.LinearMotorX/maxForce);
		set => _object.Set(PropertyName.LinearMotorX/maxForce, value);
	}

	public bool LinearMotorY/enabled
	{
		get => (bool)_object.Get(PropertyName.LinearMotorY/enabled);
		set => _object.Set(PropertyName.LinearMotorY/enabled, value);
	}

	public float LinearMotorY/targetVelocity
	{
		get => (float)_object.Get(PropertyName.LinearMotorY/targetVelocity);
		set => _object.Set(PropertyName.LinearMotorY/targetVelocity, value);
	}

	public float LinearMotorY/maxForce
	{
		get => (float)_object.Get(PropertyName.LinearMotorY/maxForce);
		set => _object.Set(PropertyName.LinearMotorY/maxForce, value);
	}

	public bool LinearMotorZ/enabled
	{
		get => (bool)_object.Get(PropertyName.LinearMotorZ/enabled);
		set => _object.Set(PropertyName.LinearMotorZ/enabled, value);
	}

	public float LinearMotorZ/targetVelocity
	{
		get => (float)_object.Get(PropertyName.LinearMotorZ/targetVelocity);
		set => _object.Set(PropertyName.LinearMotorZ/targetVelocity, value);
	}

	public float LinearMotorZ/maxForce
	{
		get => (float)_object.Get(PropertyName.LinearMotorZ/maxForce);
		set => _object.Set(PropertyName.LinearMotorZ/maxForce, value);
	}

	public bool LinearSpringX/enabled
	{
		get => (bool)_object.Get(PropertyName.LinearSpringX/enabled);
		set => _object.Set(PropertyName.LinearSpringX/enabled, value);
	}

	public float LinearSpringX/frequency
	{
		get => (float)_object.Get(PropertyName.LinearSpringX/frequency);
		set => _object.Set(PropertyName.LinearSpringX/frequency, value);
	}

	public float LinearSpringX/damping
	{
		get => (float)_object.Get(PropertyName.LinearSpringX/damping);
		set => _object.Set(PropertyName.LinearSpringX/damping, value);
	}

	public float LinearSpringX/equilibriumPoint
	{
		get => (float)_object.Get(PropertyName.LinearSpringX/equilibriumPoint);
		set => _object.Set(PropertyName.LinearSpringX/equilibriumPoint, value);
	}

	public float LinearSpringX/maxForce
	{
		get => (float)_object.Get(PropertyName.LinearSpringX/maxForce);
		set => _object.Set(PropertyName.LinearSpringX/maxForce, value);
	}

	public bool LinearSpringY/enabled
	{
		get => (bool)_object.Get(PropertyName.LinearSpringY/enabled);
		set => _object.Set(PropertyName.LinearSpringY/enabled, value);
	}

	public float LinearSpringY/frequency
	{
		get => (float)_object.Get(PropertyName.LinearSpringY/frequency);
		set => _object.Set(PropertyName.LinearSpringY/frequency, value);
	}

	public float LinearSpringY/damping
	{
		get => (float)_object.Get(PropertyName.LinearSpringY/damping);
		set => _object.Set(PropertyName.LinearSpringY/damping, value);
	}

	public float LinearSpringY/equilibriumPoint
	{
		get => (float)_object.Get(PropertyName.LinearSpringY/equilibriumPoint);
		set => _object.Set(PropertyName.LinearSpringY/equilibriumPoint, value);
	}

	public float LinearSpringY/maxForce
	{
		get => (float)_object.Get(PropertyName.LinearSpringY/maxForce);
		set => _object.Set(PropertyName.LinearSpringY/maxForce, value);
	}

	public bool LinearSpringZ/enabled
	{
		get => (bool)_object.Get(PropertyName.LinearSpringZ/enabled);
		set => _object.Set(PropertyName.LinearSpringZ/enabled, value);
	}

	public float LinearSpringZ/frequency
	{
		get => (float)_object.Get(PropertyName.LinearSpringZ/frequency);
		set => _object.Set(PropertyName.LinearSpringZ/frequency, value);
	}

	public float LinearSpringZ/damping
	{
		get => (float)_object.Get(PropertyName.LinearSpringZ/damping);
		set => _object.Set(PropertyName.LinearSpringZ/damping, value);
	}

	public float LinearSpringZ/equilibriumPoint
	{
		get => (float)_object.Get(PropertyName.LinearSpringZ/equilibriumPoint);
		set => _object.Set(PropertyName.LinearSpringZ/equilibriumPoint, value);
	}

	public float LinearSpringZ/maxForce
	{
		get => (float)_object.Get(PropertyName.LinearSpringZ/maxForce);
		set => _object.Set(PropertyName.LinearSpringZ/maxForce, value);
	}

	public bool AngularLimitX/enabled
	{
		get => (bool)_object.Get(PropertyName.AngularLimitX/enabled);
		set => _object.Set(PropertyName.AngularLimitX/enabled, value);
	}

	public float AngularLimitX/upper
	{
		get => (float)_object.Get(PropertyName.AngularLimitX/upper);
		set => _object.Set(PropertyName.AngularLimitX/upper, value);
	}

	public float AngularLimitX/lower
	{
		get => (float)_object.Get(PropertyName.AngularLimitX/lower);
		set => _object.Set(PropertyName.AngularLimitX/lower, value);
	}

	public bool AngularLimitY/enabled
	{
		get => (bool)_object.Get(PropertyName.AngularLimitY/enabled);
		set => _object.Set(PropertyName.AngularLimitY/enabled, value);
	}

	public float AngularLimitY/upper
	{
		get => (float)_object.Get(PropertyName.AngularLimitY/upper);
		set => _object.Set(PropertyName.AngularLimitY/upper, value);
	}

	public float AngularLimitY/lower
	{
		get => (float)_object.Get(PropertyName.AngularLimitY/lower);
		set => _object.Set(PropertyName.AngularLimitY/lower, value);
	}

	public bool AngularLimitZ/enabled
	{
		get => (bool)_object.Get(PropertyName.AngularLimitZ/enabled);
		set => _object.Set(PropertyName.AngularLimitZ/enabled, value);
	}

	public float AngularLimitZ/upper
	{
		get => (float)_object.Get(PropertyName.AngularLimitZ/upper);
		set => _object.Set(PropertyName.AngularLimitZ/upper, value);
	}

	public float AngularLimitZ/lower
	{
		get => (float)_object.Get(PropertyName.AngularLimitZ/lower);
		set => _object.Set(PropertyName.AngularLimitZ/lower, value);
	}

	public bool AngularMotorX/enabled
	{
		get => (bool)_object.Get(PropertyName.AngularMotorX/enabled);
		set => _object.Set(PropertyName.AngularMotorX/enabled, value);
	}

	public float AngularMotorX/targetVelocity
	{
		get => (float)_object.Get(PropertyName.AngularMotorX/targetVelocity);
		set => _object.Set(PropertyName.AngularMotorX/targetVelocity, value);
	}

	public float AngularMotorX/maxTorque
	{
		get => (float)_object.Get(PropertyName.AngularMotorX/maxTorque);
		set => _object.Set(PropertyName.AngularMotorX/maxTorque, value);
	}

	public bool AngularMotorY/enabled
	{
		get => (bool)_object.Get(PropertyName.AngularMotorY/enabled);
		set => _object.Set(PropertyName.AngularMotorY/enabled, value);
	}

	public float AngularMotorY/targetVelocity
	{
		get => (float)_object.Get(PropertyName.AngularMotorY/targetVelocity);
		set => _object.Set(PropertyName.AngularMotorY/targetVelocity, value);
	}

	public float AngularMotorY/maxTorque
	{
		get => (float)_object.Get(PropertyName.AngularMotorY/maxTorque);
		set => _object.Set(PropertyName.AngularMotorY/maxTorque, value);
	}

	public bool AngularMotorZ/enabled
	{
		get => (bool)_object.Get(PropertyName.AngularMotorZ/enabled);
		set => _object.Set(PropertyName.AngularMotorZ/enabled, value);
	}

	public float AngularMotorZ/targetVelocity
	{
		get => (float)_object.Get(PropertyName.AngularMotorZ/targetVelocity);
		set => _object.Set(PropertyName.AngularMotorZ/targetVelocity, value);
	}

	public float AngularMotorZ/maxTorque
	{
		get => (float)_object.Get(PropertyName.AngularMotorZ/maxTorque);
		set => _object.Set(PropertyName.AngularMotorZ/maxTorque, value);
	}

	public bool AngularSpringX/enabled
	{
		get => (bool)_object.Get(PropertyName.AngularSpringX/enabled);
		set => _object.Set(PropertyName.AngularSpringX/enabled, value);
	}

	public float AngularSpringX/frequency
	{
		get => (float)_object.Get(PropertyName.AngularSpringX/frequency);
		set => _object.Set(PropertyName.AngularSpringX/frequency, value);
	}

	public float AngularSpringX/damping
	{
		get => (float)_object.Get(PropertyName.AngularSpringX/damping);
		set => _object.Set(PropertyName.AngularSpringX/damping, value);
	}

	public float AngularSpringX/equilibriumPoint
	{
		get => (float)_object.Get(PropertyName.AngularSpringX/equilibriumPoint);
		set => _object.Set(PropertyName.AngularSpringX/equilibriumPoint, value);
	}

	public float AngularSpringX/maxTorque
	{
		get => (float)_object.Get(PropertyName.AngularSpringX/maxTorque);
		set => _object.Set(PropertyName.AngularSpringX/maxTorque, value);
	}

	public bool AngularSpringY/enabled
	{
		get => (bool)_object.Get(PropertyName.AngularSpringY/enabled);
		set => _object.Set(PropertyName.AngularSpringY/enabled, value);
	}

	public float AngularSpringY/frequency
	{
		get => (float)_object.Get(PropertyName.AngularSpringY/frequency);
		set => _object.Set(PropertyName.AngularSpringY/frequency, value);
	}

	public float AngularSpringY/damping
	{
		get => (float)_object.Get(PropertyName.AngularSpringY/damping);
		set => _object.Set(PropertyName.AngularSpringY/damping, value);
	}

	public float AngularSpringY/equilibriumPoint
	{
		get => (float)_object.Get(PropertyName.AngularSpringY/equilibriumPoint);
		set => _object.Set(PropertyName.AngularSpringY/equilibriumPoint, value);
	}

	public float AngularSpringY/maxTorque
	{
		get => (float)_object.Get(PropertyName.AngularSpringY/maxTorque);
		set => _object.Set(PropertyName.AngularSpringY/maxTorque, value);
	}

	public bool AngularSpringZ/enabled
	{
		get => (bool)_object.Get(PropertyName.AngularSpringZ/enabled);
		set => _object.Set(PropertyName.AngularSpringZ/enabled, value);
	}

	public float AngularSpringZ/frequency
	{
		get => (float)_object.Get(PropertyName.AngularSpringZ/frequency);
		set => _object.Set(PropertyName.AngularSpringZ/frequency, value);
	}

	public float AngularSpringZ/damping
	{
		get => (float)_object.Get(PropertyName.AngularSpringZ/damping);
		set => _object.Set(PropertyName.AngularSpringZ/damping, value);
	}

	public float AngularSpringZ/equilibriumPoint
	{
		get => (float)_object.Get(PropertyName.AngularSpringZ/equilibriumPoint);
		set => _object.Set(PropertyName.AngularSpringZ/equilibriumPoint, value);
	}

	public float AngularSpringZ/maxTorque
	{
		get => (float)_object.Get(PropertyName.AngularSpringZ/maxTorque);
		set => _object.Set(PropertyName.AngularSpringZ/maxTorque, value);
	}

	#endregion

	#region Methods

	public float GetParamX(JoltGeneric6DOFJoint3D.Param @param)
	{
		return (float)_object.Call(MethodName.GetParamX, (int)@param);
	}

	public void SetParamX(JoltGeneric6DOFJoint3D.Param @param, float @value)
	{
		_object.Call(MethodName.SetParamX, (int)@param, @value);
	}

	public float GetParamY(JoltGeneric6DOFJoint3D.Param @param)
	{
		return (float)_object.Call(MethodName.GetParamY, (int)@param);
	}

	public void SetParamY(JoltGeneric6DOFJoint3D.Param @param, float @value)
	{
		_object.Call(MethodName.SetParamY, (int)@param, @value);
	}

	public float GetParamZ(JoltGeneric6DOFJoint3D.Param @param)
	{
		return (float)_object.Call(MethodName.GetParamZ, (int)@param);
	}

	public void SetParamZ(JoltGeneric6DOFJoint3D.Param @param, float @value)
	{
		_object.Call(MethodName.SetParamZ, (int)@param, @value);
	}

	public bool GetFlagX(JoltGeneric6DOFJoint3D.Flag @flag)
	{
		return (bool)_object.Call(MethodName.GetFlagX, (int)@flag);
	}

	public void SetFlagX(JoltGeneric6DOFJoint3D.Flag @flag, bool @enabled)
	{
		_object.Call(MethodName.SetFlagX, (int)@flag, @enabled);
	}

	public bool GetFlagY(JoltGeneric6DOFJoint3D.Flag @flag)
	{
		return (bool)_object.Call(MethodName.GetFlagY, (int)@flag);
	}

	public void SetFlagY(JoltGeneric6DOFJoint3D.Flag @flag, bool @enabled)
	{
		_object.Call(MethodName.SetFlagY, (int)@flag, @enabled);
	}

	public bool GetFlagZ(JoltGeneric6DOFJoint3D.Flag @flag)
	{
		return (bool)_object.Call(MethodName.GetFlagZ, (int)@flag);
	}

	public void SetFlagZ(JoltGeneric6DOFJoint3D.Flag @flag, bool @enabled)
	{
		_object.Call(MethodName.SetFlagZ, (int)@flag, @enabled);
	}

	public float GetLinearLimitXUpper()
	{
		return (float)_object.Call(MethodName.GetLinearLimitXUpper);
	}

	public void SetLinearLimitXUpper(float @value)
	{
		_object.Call(MethodName.SetLinearLimitXUpper, @value);
	}

	public float GetLinearLimitXLower()
	{
		return (float)_object.Call(MethodName.GetLinearLimitXLower);
	}

	public void SetLinearLimitXLower(float @value)
	{
		_object.Call(MethodName.SetLinearLimitXLower, @value);
	}

	public float GetLinearLimitYUpper()
	{
		return (float)_object.Call(MethodName.GetLinearLimitYUpper);
	}

	public void SetLinearLimitYUpper(float @value)
	{
		_object.Call(MethodName.SetLinearLimitYUpper, @value);
	}

	public float GetLinearLimitYLower()
	{
		return (float)_object.Call(MethodName.GetLinearLimitYLower);
	}

	public void SetLinearLimitYLower(float @value)
	{
		_object.Call(MethodName.SetLinearLimitYLower, @value);
	}

	public float GetLinearLimitZUpper()
	{
		return (float)_object.Call(MethodName.GetLinearLimitZUpper);
	}

	public void SetLinearLimitZUpper(float @value)
	{
		_object.Call(MethodName.SetLinearLimitZUpper, @value);
	}

	public float GetLinearLimitZLower()
	{
		return (float)_object.Call(MethodName.GetLinearLimitZLower);
	}

	public void SetLinearLimitZLower(float @value)
	{
		_object.Call(MethodName.SetLinearLimitZLower, @value);
	}

	public float GetLinearLimitSpringXFrequency()
	{
		return (float)_object.Call(MethodName.GetLinearLimitSpringXFrequency);
	}

	public void SetLinearLimitSpringXFrequency(float @value)
	{
		_object.Call(MethodName.SetLinearLimitSpringXFrequency, @value);
	}

	public float GetLinearLimitSpringXDamping()
	{
		return (float)_object.Call(MethodName.GetLinearLimitSpringXDamping);
	}

	public void SetLinearLimitSpringXDamping(float @value)
	{
		_object.Call(MethodName.SetLinearLimitSpringXDamping, @value);
	}

	public float GetLinearLimitSpringYFrequency()
	{
		return (float)_object.Call(MethodName.GetLinearLimitSpringYFrequency);
	}

	public void SetLinearLimitSpringYFrequency(float @value)
	{
		_object.Call(MethodName.SetLinearLimitSpringYFrequency, @value);
	}

	public float GetLinearLimitSpringYDamping()
	{
		return (float)_object.Call(MethodName.GetLinearLimitSpringYDamping);
	}

	public void SetLinearLimitSpringYDamping(float @value)
	{
		_object.Call(MethodName.SetLinearLimitSpringYDamping, @value);
	}

	public float GetLinearLimitSpringZFrequency()
	{
		return (float)_object.Call(MethodName.GetLinearLimitSpringZFrequency);
	}

	public void SetLinearLimitSpringZFrequency(float @value)
	{
		_object.Call(MethodName.SetLinearLimitSpringZFrequency, @value);
	}

	public float GetLinearLimitSpringZDamping()
	{
		return (float)_object.Call(MethodName.GetLinearLimitSpringZDamping);
	}

	public void SetLinearLimitSpringZDamping(float @value)
	{
		_object.Call(MethodName.SetLinearLimitSpringZDamping, @value);
	}

	public float GetLinearMotorXTargetVelocity()
	{
		return (float)_object.Call(MethodName.GetLinearMotorXTargetVelocity);
	}

	public void SetLinearMotorXTargetVelocity(float @value)
	{
		_object.Call(MethodName.SetLinearMotorXTargetVelocity, @value);
	}

	public float GetLinearMotorXMaxForce()
	{
		return (float)_object.Call(MethodName.GetLinearMotorXMaxForce);
	}

	public void SetLinearMotorXMaxForce(float @value)
	{
		_object.Call(MethodName.SetLinearMotorXMaxForce, @value);
	}

	public float GetLinearMotorYTargetVelocity()
	{
		return (float)_object.Call(MethodName.GetLinearMotorYTargetVelocity);
	}

	public void SetLinearMotorYTargetVelocity(float @value)
	{
		_object.Call(MethodName.SetLinearMotorYTargetVelocity, @value);
	}

	public float GetLinearMotorYMaxForce()
	{
		return (float)_object.Call(MethodName.GetLinearMotorYMaxForce);
	}

	public void SetLinearMotorYMaxForce(float @value)
	{
		_object.Call(MethodName.SetLinearMotorYMaxForce, @value);
	}

	public float GetLinearMotorZTargetVelocity()
	{
		return (float)_object.Call(MethodName.GetLinearMotorZTargetVelocity);
	}

	public void SetLinearMotorZTargetVelocity(float @value)
	{
		_object.Call(MethodName.SetLinearMotorZTargetVelocity, @value);
	}

	public float GetLinearMotorZMaxForce()
	{
		return (float)_object.Call(MethodName.GetLinearMotorZMaxForce);
	}

	public void SetLinearMotorZMaxForce(float @value)
	{
		_object.Call(MethodName.SetLinearMotorZMaxForce, @value);
	}

	public float GetLinearSpringXFrequency()
	{
		return (float)_object.Call(MethodName.GetLinearSpringXFrequency);
	}

	public void SetLinearSpringXFrequency(float @value)
	{
		_object.Call(MethodName.SetLinearSpringXFrequency, @value);
	}

	public float GetLinearSpringXDamping()
	{
		return (float)_object.Call(MethodName.GetLinearSpringXDamping);
	}

	public void SetLinearSpringXDamping(float @value)
	{
		_object.Call(MethodName.SetLinearSpringXDamping, @value);
	}

	public float GetLinearSpringXEquilibriumPoint()
	{
		return (float)_object.Call(MethodName.GetLinearSpringXEquilibriumPoint);
	}

	public void SetLinearSpringXEquilibriumPoint(float @value)
	{
		_object.Call(MethodName.SetLinearSpringXEquilibriumPoint, @value);
	}

	public float GetLinearSpringXMaxForce()
	{
		return (float)_object.Call(MethodName.GetLinearSpringXMaxForce);
	}

	public void SetLinearSpringXMaxForce(float @value)
	{
		_object.Call(MethodName.SetLinearSpringXMaxForce, @value);
	}

	public float GetLinearSpringYFrequency()
	{
		return (float)_object.Call(MethodName.GetLinearSpringYFrequency);
	}

	public void SetLinearSpringYFrequency(float @value)
	{
		_object.Call(MethodName.SetLinearSpringYFrequency, @value);
	}

	public float GetLinearSpringYDamping()
	{
		return (float)_object.Call(MethodName.GetLinearSpringYDamping);
	}

	public void SetLinearSpringYDamping(float @value)
	{
		_object.Call(MethodName.SetLinearSpringYDamping, @value);
	}

	public float GetLinearSpringYEquilibriumPoint()
	{
		return (float)_object.Call(MethodName.GetLinearSpringYEquilibriumPoint);
	}

	public void SetLinearSpringYEquilibriumPoint(float @value)
	{
		_object.Call(MethodName.SetLinearSpringYEquilibriumPoint, @value);
	}

	public float GetLinearSpringYMaxForce()
	{
		return (float)_object.Call(MethodName.GetLinearSpringYMaxForce);
	}

	public void SetLinearSpringYMaxForce(float @value)
	{
		_object.Call(MethodName.SetLinearSpringYMaxForce, @value);
	}

	public float GetLinearSpringZFrequency()
	{
		return (float)_object.Call(MethodName.GetLinearSpringZFrequency);
	}

	public void SetLinearSpringZFrequency(float @value)
	{
		_object.Call(MethodName.SetLinearSpringZFrequency, @value);
	}

	public float GetLinearSpringZDamping()
	{
		return (float)_object.Call(MethodName.GetLinearSpringZDamping);
	}

	public void SetLinearSpringZDamping(float @value)
	{
		_object.Call(MethodName.SetLinearSpringZDamping, @value);
	}

	public float GetLinearSpringZEquilibriumPoint()
	{
		return (float)_object.Call(MethodName.GetLinearSpringZEquilibriumPoint);
	}

	public void SetLinearSpringZEquilibriumPoint(float @value)
	{
		_object.Call(MethodName.SetLinearSpringZEquilibriumPoint, @value);
	}

	public float GetLinearSpringZMaxForce()
	{
		return (float)_object.Call(MethodName.GetLinearSpringZMaxForce);
	}

	public void SetLinearSpringZMaxForce(float @value)
	{
		_object.Call(MethodName.SetLinearSpringZMaxForce, @value);
	}

	public bool GetLinearLimitXEnabled()
	{
		return (bool)_object.Call(MethodName.GetLinearLimitXEnabled);
	}

	public void SetLinearLimitXEnabled(bool @enabled)
	{
		_object.Call(MethodName.SetLinearLimitXEnabled, @enabled);
	}

	public bool GetLinearLimitYEnabled()
	{
		return (bool)_object.Call(MethodName.GetLinearLimitYEnabled);
	}

	public void SetLinearLimitYEnabled(bool @enabled)
	{
		_object.Call(MethodName.SetLinearLimitYEnabled, @enabled);
	}

	public bool GetLinearLimitZEnabled()
	{
		return (bool)_object.Call(MethodName.GetLinearLimitZEnabled);
	}

	public void SetLinearLimitZEnabled(bool @enabled)
	{
		_object.Call(MethodName.SetLinearLimitZEnabled, @enabled);
	}

	public bool GetLinearLimitSpringXEnabled()
	{
		return (bool)_object.Call(MethodName.GetLinearLimitSpringXEnabled);
	}

	public void SetLinearLimitSpringXEnabled(bool @enabled)
	{
		_object.Call(MethodName.SetLinearLimitSpringXEnabled, @enabled);
	}

	public bool GetLinearLimitSpringYEnabled()
	{
		return (bool)_object.Call(MethodName.GetLinearLimitSpringYEnabled);
	}

	public void SetLinearLimitSpringYEnabled(bool @enabled)
	{
		_object.Call(MethodName.SetLinearLimitSpringYEnabled, @enabled);
	}

	public bool GetLinearLimitSpringZEnabled()
	{
		return (bool)_object.Call(MethodName.GetLinearLimitSpringZEnabled);
	}

	public void SetLinearLimitSpringZEnabled(bool @enabled)
	{
		_object.Call(MethodName.SetLinearLimitSpringZEnabled, @enabled);
	}

	public bool GetLinearMotorXEnabled()
	{
		return (bool)_object.Call(MethodName.GetLinearMotorXEnabled);
	}

	public void SetLinearMotorXEnabled(bool @enabled)
	{
		_object.Call(MethodName.SetLinearMotorXEnabled, @enabled);
	}

	public bool GetLinearMotorYEnabled()
	{
		return (bool)_object.Call(MethodName.GetLinearMotorYEnabled);
	}

	public void SetLinearMotorYEnabled(bool @enabled)
	{
		_object.Call(MethodName.SetLinearMotorYEnabled, @enabled);
	}

	public bool GetLinearMotorZEnabled()
	{
		return (bool)_object.Call(MethodName.GetLinearMotorZEnabled);
	}

	public void SetLinearMotorZEnabled(bool @enabled)
	{
		_object.Call(MethodName.SetLinearMotorZEnabled, @enabled);
	}

	public bool GetLinearSpringXEnabled()
	{
		return (bool)_object.Call(MethodName.GetLinearSpringXEnabled);
	}

	public void SetLinearSpringXEnabled(bool @enabled)
	{
		_object.Call(MethodName.SetLinearSpringXEnabled, @enabled);
	}

	public bool GetLinearSpringYEnabled()
	{
		return (bool)_object.Call(MethodName.GetLinearSpringYEnabled);
	}

	public void SetLinearSpringYEnabled(bool @enabled)
	{
		_object.Call(MethodName.SetLinearSpringYEnabled, @enabled);
	}

	public bool GetLinearSpringZEnabled()
	{
		return (bool)_object.Call(MethodName.GetLinearSpringZEnabled);
	}

	public void SetLinearSpringZEnabled(bool @enabled)
	{
		_object.Call(MethodName.SetLinearSpringZEnabled, @enabled);
	}

	public float GetAngularLimitXUpper()
	{
		return (float)_object.Call(MethodName.GetAngularLimitXUpper);
	}

	public void SetAngularLimitXUpper(float @value)
	{
		_object.Call(MethodName.SetAngularLimitXUpper, @value);
	}

	public float GetAngularLimitXLower()
	{
		return (float)_object.Call(MethodName.GetAngularLimitXLower);
	}

	public void SetAngularLimitXLower(float @value)
	{
		_object.Call(MethodName.SetAngularLimitXLower, @value);
	}

	public float GetAngularLimitYUpper()
	{
		return (float)_object.Call(MethodName.GetAngularLimitYUpper);
	}

	public void SetAngularLimitYUpper(float @value)
	{
		_object.Call(MethodName.SetAngularLimitYUpper, @value);
	}

	public float GetAngularLimitYLower()
	{
		return (float)_object.Call(MethodName.GetAngularLimitYLower);
	}

	public void SetAngularLimitYLower(float @value)
	{
		_object.Call(MethodName.SetAngularLimitYLower, @value);
	}

	public float GetAngularLimitZUpper()
	{
		return (float)_object.Call(MethodName.GetAngularLimitZUpper);
	}

	public void SetAngularLimitZUpper(float @value)
	{
		_object.Call(MethodName.SetAngularLimitZUpper, @value);
	}

	public float GetAngularLimitZLower()
	{
		return (float)_object.Call(MethodName.GetAngularLimitZLower);
	}

	public void SetAngularLimitZLower(float @value)
	{
		_object.Call(MethodName.SetAngularLimitZLower, @value);
	}

	public float GetAngularMotorXTargetVelocity()
	{
		return (float)_object.Call(MethodName.GetAngularMotorXTargetVelocity);
	}

	public void SetAngularMotorXTargetVelocity(float @value)
	{
		_object.Call(MethodName.SetAngularMotorXTargetVelocity, @value);
	}

	public float GetAngularMotorXMaxTorque()
	{
		return (float)_object.Call(MethodName.GetAngularMotorXMaxTorque);
	}

	public void SetAngularMotorXMaxTorque(float @value)
	{
		_object.Call(MethodName.SetAngularMotorXMaxTorque, @value);
	}

	public float GetAngularMotorYTargetVelocity()
	{
		return (float)_object.Call(MethodName.GetAngularMotorYTargetVelocity);
	}

	public void SetAngularMotorYTargetVelocity(float @value)
	{
		_object.Call(MethodName.SetAngularMotorYTargetVelocity, @value);
	}

	public float GetAngularMotorYMaxTorque()
	{
		return (float)_object.Call(MethodName.GetAngularMotorYMaxTorque);
	}

	public void SetAngularMotorYMaxTorque(float @value)
	{
		_object.Call(MethodName.SetAngularMotorYMaxTorque, @value);
	}

	public float GetAngularMotorZTargetVelocity()
	{
		return (float)_object.Call(MethodName.GetAngularMotorZTargetVelocity);
	}

	public void SetAngularMotorZTargetVelocity(float @value)
	{
		_object.Call(MethodName.SetAngularMotorZTargetVelocity, @value);
	}

	public float GetAngularMotorZMaxTorque()
	{
		return (float)_object.Call(MethodName.GetAngularMotorZMaxTorque);
	}

	public void SetAngularMotorZMaxTorque(float @value)
	{
		_object.Call(MethodName.SetAngularMotorZMaxTorque, @value);
	}

	public float GetAngularSpringXFrequency()
	{
		return (float)_object.Call(MethodName.GetAngularSpringXFrequency);
	}

	public void SetAngularSpringXFrequency(float @value)
	{
		_object.Call(MethodName.SetAngularSpringXFrequency, @value);
	}

	public float GetAngularSpringXDamping()
	{
		return (float)_object.Call(MethodName.GetAngularSpringXDamping);
	}

	public void SetAngularSpringXDamping(float @value)
	{
		_object.Call(MethodName.SetAngularSpringXDamping, @value);
	}

	public float GetAngularSpringXEquilibriumPoint()
	{
		return (float)_object.Call(MethodName.GetAngularSpringXEquilibriumPoint);
	}

	public void SetAngularSpringXEquilibriumPoint(float @value)
	{
		_object.Call(MethodName.SetAngularSpringXEquilibriumPoint, @value);
	}

	public float GetAngularSpringXMaxTorque()
	{
		return (float)_object.Call(MethodName.GetAngularSpringXMaxTorque);
	}

	public void SetAngularSpringXMaxTorque(float @value)
	{
		_object.Call(MethodName.SetAngularSpringXMaxTorque, @value);
	}

	public float GetAngularSpringYFrequency()
	{
		return (float)_object.Call(MethodName.GetAngularSpringYFrequency);
	}

	public void SetAngularSpringYFrequency(float @value)
	{
		_object.Call(MethodName.SetAngularSpringYFrequency, @value);
	}

	public float GetAngularSpringYDamping()
	{
		return (float)_object.Call(MethodName.GetAngularSpringYDamping);
	}

	public void SetAngularSpringYDamping(float @value)
	{
		_object.Call(MethodName.SetAngularSpringYDamping, @value);
	}

	public float GetAngularSpringYEquilibriumPoint()
	{
		return (float)_object.Call(MethodName.GetAngularSpringYEquilibriumPoint);
	}

	public void SetAngularSpringYEquilibriumPoint(float @value)
	{
		_object.Call(MethodName.SetAngularSpringYEquilibriumPoint, @value);
	}

	public float GetAngularSpringYMaxTorque()
	{
		return (float)_object.Call(MethodName.GetAngularSpringYMaxTorque);
	}

	public void SetAngularSpringYMaxTorque(float @value)
	{
		_object.Call(MethodName.SetAngularSpringYMaxTorque, @value);
	}

	public float GetAngularSpringZFrequency()
	{
		return (float)_object.Call(MethodName.GetAngularSpringZFrequency);
	}

	public void SetAngularSpringZFrequency(float @value)
	{
		_object.Call(MethodName.SetAngularSpringZFrequency, @value);
	}

	public float GetAngularSpringZDamping()
	{
		return (float)_object.Call(MethodName.GetAngularSpringZDamping);
	}

	public void SetAngularSpringZDamping(float @value)
	{
		_object.Call(MethodName.SetAngularSpringZDamping, @value);
	}

	public float GetAngularSpringZEquilibriumPoint()
	{
		return (float)_object.Call(MethodName.GetAngularSpringZEquilibriumPoint);
	}

	public void SetAngularSpringZEquilibriumPoint(float @value)
	{
		_object.Call(MethodName.SetAngularSpringZEquilibriumPoint, @value);
	}

	public float GetAngularSpringZMaxTorque()
	{
		return (float)_object.Call(MethodName.GetAngularSpringZMaxTorque);
	}

	public void SetAngularSpringZMaxTorque(float @value)
	{
		_object.Call(MethodName.SetAngularSpringZMaxTorque, @value);
	}

	public bool GetAngularLimitXEnabled()
	{
		return (bool)_object.Call(MethodName.GetAngularLimitXEnabled);
	}

	public void SetAngularLimitXEnabled(bool @enabled)
	{
		_object.Call(MethodName.SetAngularLimitXEnabled, @enabled);
	}

	public bool GetAngularLimitYEnabled()
	{
		return (bool)_object.Call(MethodName.GetAngularLimitYEnabled);
	}

	public void SetAngularLimitYEnabled(bool @enabled)
	{
		_object.Call(MethodName.SetAngularLimitYEnabled, @enabled);
	}

	public bool GetAngularLimitZEnabled()
	{
		return (bool)_object.Call(MethodName.GetAngularLimitZEnabled);
	}

	public void SetAngularLimitZEnabled(bool @enabled)
	{
		_object.Call(MethodName.SetAngularLimitZEnabled, @enabled);
	}

	public bool GetAngularMotorXEnabled()
	{
		return (bool)_object.Call(MethodName.GetAngularMotorXEnabled);
	}

	public void SetAngularMotorXEnabled(bool @enabled)
	{
		_object.Call(MethodName.SetAngularMotorXEnabled, @enabled);
	}

	public bool GetAngularMotorYEnabled()
	{
		return (bool)_object.Call(MethodName.GetAngularMotorYEnabled);
	}

	public void SetAngularMotorYEnabled(bool @enabled)
	{
		_object.Call(MethodName.SetAngularMotorYEnabled, @enabled);
	}

	public bool GetAngularMotorZEnabled()
	{
		return (bool)_object.Call(MethodName.GetAngularMotorZEnabled);
	}

	public void SetAngularMotorZEnabled(bool @enabled)
	{
		_object.Call(MethodName.SetAngularMotorZEnabled, @enabled);
	}

	public bool GetAngularSpringXEnabled()
	{
		return (bool)_object.Call(MethodName.GetAngularSpringXEnabled);
	}

	public void SetAngularSpringXEnabled(bool @enabled)
	{
		_object.Call(MethodName.SetAngularSpringXEnabled, @enabled);
	}

	public bool GetAngularSpringYEnabled()
	{
		return (bool)_object.Call(MethodName.GetAngularSpringYEnabled);
	}

	public void SetAngularSpringYEnabled(bool @enabled)
	{
		_object.Call(MethodName.SetAngularSpringYEnabled, @enabled);
	}

	public bool GetAngularSpringZEnabled()
	{
		return (bool)_object.Call(MethodName.GetAngularSpringZEnabled);
	}

	public void SetAngularSpringZEnabled(bool @enabled)
	{
		_object.Call(MethodName.SetAngularSpringZEnabled, @enabled);
	}

	public float GetAppliedForce()
	{
		return (float)_object.Call(MethodName.GetAppliedForce);
	}

	public float GetAppliedTorque()
	{
		return (float)_object.Call(MethodName.GetAppliedTorque);
	}

	#endregion
}
