#if TOOLS
// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;
using Object = Godot.GodotObject;

namespace GDExtensionBindgen;

public class JoltJointGizmoPlugin3D
{
	// Engine object used for calling engine methods
	protected EditorNode3DGizmoPlugin _object;

	public JoltJointGizmoPlugin3D() : this(NativeName)
	{
	}
	protected JoltJointGizmoPlugin3D(StringName @class) : this(ClassDB.Instantiate(@class))
	{
	}
	protected JoltJointGizmoPlugin3D(Variant variant) : this((EditorNode3DGizmoPlugin) variant)
	{
	}
	protected JoltJointGizmoPlugin3D([NotNull] EditorNode3DGizmoPlugin @object)
	{
		_object = @object;
	}

	public static implicit operator EditorNode3DGizmoPlugin(JoltJointGizmoPlugin3D self) => self?._object;
	public static implicit operator Variant(JoltJointGizmoPlugin3D self) => self?._object;
	public static explicit operator JoltJointGizmoPlugin3D(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public class PropertyName : EditorNode3DGizmoPlugin.PropertyName
	{

	}

	public class MethodName : EditorNode3DGizmoPlugin.MethodName
	{

	}

	public class SignalName : EditorNode3DGizmoPlugin.SignalName
	{

	}

	private static readonly StringName NativeName = "JoltJointGizmoPlugin3D";

	#region Inherited Properties

	public bool ResourceLocalToScene
	{
		get => _object.ResourceLocalToScene;
		set => _object.ResourceLocalToScene = value;
	}

	public string ResourcePath
	{
		get => _object.ResourcePath;
		set => _object.ResourcePath = value;
	}

	public string ResourceName
	{
		get => _object.ResourceName;
		set => _object.ResourceName = value;
	}

	public string ResourceSceneUniqueId
	{
		get => _object.ResourceSceneUniqueId;
		set => _object.ResourceSceneUniqueId = value;
	}

	#endregion

	#region Inherited Methods

	public void CreateMaterial(string @name, Godot.Color @color, bool @billboard = false, bool @on_top = false, bool @use_vertex_color = false)
	{
		_object.CreateMaterial(@name, @color, @billboard, @on_top, @use_vertex_color);
	}

	public void CreateIconMaterial(string @name, Texture2D @texture, bool @on_top = false, Godot.Color? @color = null)
	{
		@color ??= new(1.0f, 1.0f, 1.0f, 1.0f);
		_object.CreateIconMaterial(@name, @texture, @on_top, @color);
	}

	public void CreateHandleMaterial(string @name, bool @billboard = false, Texture2D @texture = default)
	{
		_object.CreateHandleMaterial(@name, @billboard, @texture);
	}

	public void AddMaterial(string @name, StandardMaterial3D @material)
	{
		_object.AddMaterial(@name, @material);
	}

	public StandardMaterial3D GetMaterial(string @name, EditorNode3DGizmo @gizmo = default)
	{
		return _object.GetMaterial(@name, @gizmo);
	}

	public void SetPath(string @path)
	{
		_object.SetPath(@path);
	}

	public void TakeOverPath(string @path)
	{
		_object.TakeOverPath(@path);
	}

	public string GetPath()
	{
		return _object.GetPath();
	}

	public void SetPathCache(string @path)
	{
		_object.SetPathCache(@path);
	}

	public void SetName(string @name)
	{
		_object.SetName(@name);
	}

	public string GetName()
	{
		return _object.GetName();
	}

	public Godot.Rid GetRid()
	{
		return _object.GetRid();
	}

	public void SetLocalToScene(bool @enable)
	{
		_object.SetLocalToScene(@enable);
	}

	public bool IsLocalToScene()
	{
		return _object.IsLocalToScene();
	}

	public Node GetLocalScene()
	{
		return _object.GetLocalScene();
	}

	public void SetupLocalToScene()
	{
		_object.SetupLocalToScene();
	}

	public void ResetState()
	{
		_object.ResetState();
	}

	public void SetIdForPath(string @path, string @id)
	{
		_object.SetIdForPath(@path, @id);
	}

	public string GetIdForPath(string @path)
	{
		return _object.GetIdForPath(@path);
	}

	public bool IsBuiltIn()
	{
		return _object.IsBuiltIn();
	}

	public static string GenerateSceneUniqueId()
	{
		return Resource.GenerateSceneUniqueId();
	}

	public void SetSceneUniqueId(string @id)
	{
		_object.SetSceneUniqueId(@id);
	}

	public string GetSceneUniqueId()
	{
		return _object.GetSceneUniqueId();
	}

	public void EmitChanged()
	{
		_object.EmitChanged();
	}

	public Resource Duplicate(bool @subresources = false)
	{
		return _object.Duplicate(@subresources);
	}

	public bool InitRef()
	{
		return _object.InitRef();
	}

	public bool Reference()
	{
		return _object.Reference();
	}

	public bool Unreference()
	{
		return _object.Unreference();
	}

	public int GetReferenceCount()
	{
		return _object.GetReferenceCount();
	}

	public void Free()
	{
		_object.Free();
	}

	public string GetClass()
	{
		return _object.GetClass();
	}

	public bool IsClass(string @class)
	{
		return _object.IsClass(@class);
	}

	public void Set(Godot.StringName @property, Variant @value)
	{
		_object.Set(@property, @value);
	}

	public Variant Get(Godot.StringName @property)
	{
		return _object.Get(@property);
	}

	public void SetIndexed(Godot.NodePath @property_path, Variant @value)
	{
		_object.SetIndexed(@property_path, @value);
	}

	public Variant GetIndexed(Godot.NodePath @property_path)
	{
		return _object.GetIndexed(@property_path);
	}

	public Godot.Collections.Array<Godot.Collections.Dictionary> GetPropertyList()
	{
		return _object.GetPropertyList();
	}

	public Godot.Collections.Array<Godot.Collections.Dictionary> GetMethodList()
	{
		return _object.GetMethodList();
	}

	public bool PropertyCanRevert(Godot.StringName @property)
	{
		return _object.PropertyCanRevert(@property);
	}

	public Variant PropertyGetRevert(Godot.StringName @property)
	{
		return _object.PropertyGetRevert(@property);
	}

	public void Notification(int @what, bool @reversed = false)
	{
		_object.Notification(@what, @reversed);
	}

	public override string ToString()
	{
		return _object.ToString();
	}

	public ulong GetInstanceId()
	{
		return _object.GetInstanceId();
	}

	public void SetScript(Variant @script)
	{
		_object.SetScript(@script);
	}

	public Variant GetScript()
	{
		return _object.GetScript();
	}

	public void SetMeta(Godot.StringName @name, Variant @value)
	{
		_object.SetMeta(@name, @value);
	}

	public void RemoveMeta(Godot.StringName @name)
	{
		_object.RemoveMeta(@name);
	}

	public Variant GetMeta(Godot.StringName @name, Variant @default = default)
	{
		return _object.GetMeta(@name, @default);
	}

	public bool HasMeta(Godot.StringName @name)
	{
		return _object.HasMeta(@name);
	}

	public Godot.Collections.Array<StringName> GetMetaList()
	{
		return _object.GetMetaList();
	}

	public void AddUserSignal(string @signal, Godot.Collections.Array @arguments = null)
	{
		@arguments ??= new();
		_object.AddUserSignal(@signal, @arguments);
	}

	public bool HasUserSignal(Godot.StringName @signal)
	{
		return _object.HasUserSignal(@signal);
	}

	public void RemoveUserSignal(Godot.StringName @signal)
	{
		_object.RemoveUserSignal(@signal);
	}

	public Godot.Error EmitSignal(Godot.StringName @signal, params Variant[] varargs)
	{
		return _object.EmitSignal(@signal, varargs);
	}

	public Variant Call(Godot.StringName @method, params Variant[] varargs)
	{
		return _object.Call(@method, varargs);
	}

	public Variant CallDeferred(Godot.StringName @method, params Variant[] varargs)
	{
		return _object.CallDeferred(@method, varargs);
	}

	public void SetDeferred(Godot.StringName @property, Variant @value)
	{
		_object.SetDeferred(@property, @value);
	}

	public Variant Callv(Godot.StringName @method, Godot.Collections.Array @arg_array)
	{
		return _object.Callv(@method, @arg_array);
	}

	public bool HasMethod(Godot.StringName @method)
	{
		return _object.HasMethod(@method);
	}

	public int GetMethodArgumentCount(Godot.StringName @method)
	{
		return _object.GetMethodArgumentCount(@method);
	}

	public bool HasSignal(Godot.StringName @signal)
	{
		return _object.HasSignal(@signal);
	}

	public Godot.Collections.Array<Godot.Collections.Dictionary> GetSignalList()
	{
		return _object.GetSignalList();
	}

	public Godot.Collections.Array<Godot.Collections.Dictionary> GetSignalConnectionList(Godot.StringName @signal)
	{
		return _object.GetSignalConnectionList(@signal);
	}

	public Godot.Collections.Array<Godot.Collections.Dictionary> GetIncomingConnections()
	{
		return _object.GetIncomingConnections();
	}

	public Godot.Error Connect(Godot.StringName @signal, Godot.Callable @callable, uint @flags = (uint)0)
	{
		return _object.Connect(@signal, @callable, @flags);
	}

	public void Disconnect(Godot.StringName @signal, Godot.Callable @callable)
	{
		_object.Disconnect(@signal, @callable);
	}

	public bool IsConnected(Godot.StringName @signal, Godot.Callable @callable)
	{
		return _object.IsConnected(@signal, @callable);
	}

	public bool HasConnections(Godot.StringName @signal)
	{
		return _object.HasConnections(@signal);
	}

	public void SetBlockSignals(bool @enable)
	{
		_object.SetBlockSignals(@enable);
	}

	public bool IsBlockingSignals()
	{
		return _object.IsBlockingSignals();
	}

	public void NotifyPropertyListChanged()
	{
		_object.NotifyPropertyListChanged();
	}

	public void SetMessageTranslation(bool @enable)
	{
		_object.SetMessageTranslation(@enable);
	}

	public bool CanTranslateMessages()
	{
		return _object.CanTranslateMessages();
	}

	public string Tr(Godot.StringName @message, Godot.StringName @context = null)
	{
		@context ??= "";
		return _object.Tr(@message, @context);
	}

	public string TrN(Godot.StringName @message, Godot.StringName @plural_message, int @n, Godot.StringName @context = null)
	{
		@context ??= "";
		return _object.TrN(@message, @plural_message, @n, @context);
	}

	public Godot.StringName GetTranslationDomain()
	{
		return _object.GetTranslationDomain();
	}

	public void SetTranslationDomain(Godot.StringName @domain)
	{
		_object.SetTranslationDomain(@domain);
	}

	public bool IsQueuedForDeletion()
	{
		return _object.IsQueuedForDeletion();
	}

	public void CancelFree()
	{
		_object.CancelFree();
	}

	#endregion

	#region Inherited Signals

	public event Action ChangedEvent
	{
		add
		{
			Connect(SignalName.Changed, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.Changed, Callable.From(value));
		}
	}

	public event Action SetupLocalToSceneRequestedEvent
	{
		add
		{
			Connect(SignalName.SetupLocalToSceneRequested, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.SetupLocalToSceneRequested, Callable.From(value));
		}
	}

	public event Action ScriptChangedEvent
	{
		add
		{
			Connect(SignalName.ScriptChanged, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.ScriptChanged, Callable.From(value));
		}
	}

	public event Action PropertyListChangedEvent
	{
		add
		{
			Connect(SignalName.PropertyListChanged, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.PropertyListChanged, Callable.From(value));
		}
	}

	#endregion
}
#endif
