// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;
using Object = Godot.GodotObject;

namespace GDExtensionBindgen;

public class JoltPinJoint3D : JoltJoint3D
{
	public JoltPinJoint3D() : base(NativeName)
	{
	}
	protected JoltPinJoint3D(StringName @class) : base(@class)
	{
	}
	protected JoltPinJoint3D(Variant variant) : base(variant)
	{
	}
	protected JoltPinJoint3D([NotNull] Node3D @object) : base(@object)
	{
	}

	public static implicit operator Node3D(JoltPinJoint3D self) => self?._object;
	public static implicit operator Variant(JoltPinJoint3D self) => self?._object;
	public static explicit operator JoltPinJoint3D(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public new class PropertyName : JoltJoint3D.PropertyName
	{

	}

	public new class MethodName : JoltJoint3D.MethodName
	{
		public static readonly StringName GetAppliedForce = "get_applied_force";
	}

	public new class SignalName : JoltJoint3D.SignalName
	{

	}

	private static readonly StringName NativeName = "JoltPinJoint3D";

	#region Methods

	public float GetAppliedForce()
	{
		return (float)_object.Call(MethodName.GetAppliedForce);
	}

	#endregion
}
