// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;
using Object = Godot.GodotObject;

namespace GDExtensionBindgen;

public class JoltSliderJoint3D : JoltJoint3D
{
	public JoltSliderJoint3D() : base(NativeName)
	{
	}
	protected JoltSliderJoint3D(StringName @class) : base(@class)
	{
	}
	protected JoltSliderJoint3D(Variant variant) : base(variant)
	{
	}
	protected JoltSliderJoint3D([NotNull] Node3D @object) : base(@object)
	{
	}

	public static implicit operator Node3D(JoltSliderJoint3D self) => self?._object;
	public static implicit operator Variant(JoltSliderJoint3D self) => self?._object;
	public static explicit operator JoltSliderJoint3D(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public new class PropertyName : JoltJoint3D.PropertyName
	{
		public static readonly StringName LimitEnabled = "limit_enabled";
		public static readonly StringName LimitUpper = "limit_upper";
		public static readonly StringName LimitLower = "limit_lower";
		public static readonly StringName LimitSpringEnabled = "limit_spring_enabled";
		public static readonly StringName LimitSpringFrequency = "limit_spring_frequency";
		public static readonly StringName LimitSpringDamping = "limit_spring_damping";
		public static readonly StringName MotorEnabled = "motor_enabled";
		public static readonly StringName MotorTargetVelocity = "motor_target_velocity";
		public static readonly StringName MotorMaxForce = "motor_max_force";
	}

	public new class MethodName : JoltJoint3D.MethodName
	{
		public static readonly StringName GetLimitEnabled = "get_limit_enabled";
		public static readonly StringName SetLimitEnabled = "set_limit_enabled";
		public static readonly StringName GetLimitUpper = "get_limit_upper";
		public static readonly StringName SetLimitUpper = "set_limit_upper";
		public static readonly StringName GetLimitLower = "get_limit_lower";
		public static readonly StringName SetLimitLower = "set_limit_lower";
		public static readonly StringName GetLimitSpringEnabled = "get_limit_spring_enabled";
		public static readonly StringName SetLimitSpringEnabled = "set_limit_spring_enabled";
		public static readonly StringName GetLimitSpringFrequency = "get_limit_spring_frequency";
		public static readonly StringName SetLimitSpringFrequency = "set_limit_spring_frequency";
		public static readonly StringName GetLimitSpringDamping = "get_limit_spring_damping";
		public static readonly StringName SetLimitSpringDamping = "set_limit_spring_damping";
		public static readonly StringName GetMotorEnabled = "get_motor_enabled";
		public static readonly StringName SetMotorEnabled = "set_motor_enabled";
		public static readonly StringName GetMotorTargetVelocity = "get_motor_target_velocity";
		public static readonly StringName SetMotorTargetVelocity = "set_motor_target_velocity";
		public static readonly StringName GetMotorMaxForce = "get_motor_max_force";
		public static readonly StringName SetMotorMaxForce = "set_motor_max_force";
		public static readonly StringName GetAppliedForce = "get_applied_force";
		public static readonly StringName GetAppliedTorque = "get_applied_torque";
	}

	public new class SignalName : JoltJoint3D.SignalName
	{

	}

	private static readonly StringName NativeName = "JoltSliderJoint3D";

	#region Properties

	public bool LimitEnabled
	{
		get => (bool)_object.Get(PropertyName.LimitEnabled);
		set => _object.Set(PropertyName.LimitEnabled, value);
	}

	public float LimitUpper
	{
		get => (float)_object.Get(PropertyName.LimitUpper);
		set => _object.Set(PropertyName.LimitUpper, value);
	}

	public float LimitLower
	{
		get => (float)_object.Get(PropertyName.LimitLower);
		set => _object.Set(PropertyName.LimitLower, value);
	}

	public bool LimitSpringEnabled
	{
		get => (bool)_object.Get(PropertyName.LimitSpringEnabled);
		set => _object.Set(PropertyName.LimitSpringEnabled, value);
	}

	public float LimitSpringFrequency
	{
		get => (float)_object.Get(PropertyName.LimitSpringFrequency);
		set => _object.Set(PropertyName.LimitSpringFrequency, value);
	}

	public float LimitSpringDamping
	{
		get => (float)_object.Get(PropertyName.LimitSpringDamping);
		set => _object.Set(PropertyName.LimitSpringDamping, value);
	}

	public bool MotorEnabled
	{
		get => (bool)_object.Get(PropertyName.MotorEnabled);
		set => _object.Set(PropertyName.MotorEnabled, value);
	}

	public float MotorTargetVelocity
	{
		get => (float)_object.Get(PropertyName.MotorTargetVelocity);
		set => _object.Set(PropertyName.MotorTargetVelocity, value);
	}

	public float MotorMaxForce
	{
		get => (float)_object.Get(PropertyName.MotorMaxForce);
		set => _object.Set(PropertyName.MotorMaxForce, value);
	}

	#endregion

	#region Methods

	public bool GetLimitEnabled()
	{
		return (bool)_object.Call(MethodName.GetLimitEnabled);
	}

	public void SetLimitEnabled(bool @enabled)
	{
		_object.Call(MethodName.SetLimitEnabled, @enabled);
	}

	public float GetLimitUpper()
	{
		return (float)_object.Call(MethodName.GetLimitUpper);
	}

	public void SetLimitUpper(float @value)
	{
		_object.Call(MethodName.SetLimitUpper, @value);
	}

	public float GetLimitLower()
	{
		return (float)_object.Call(MethodName.GetLimitLower);
	}

	public void SetLimitLower(float @value)
	{
		_object.Call(MethodName.SetLimitLower, @value);
	}

	public bool GetLimitSpringEnabled()
	{
		return (bool)_object.Call(MethodName.GetLimitSpringEnabled);
	}

	public void SetLimitSpringEnabled(bool @enabled)
	{
		_object.Call(MethodName.SetLimitSpringEnabled, @enabled);
	}

	public float GetLimitSpringFrequency()
	{
		return (float)_object.Call(MethodName.GetLimitSpringFrequency);
	}

	public void SetLimitSpringFrequency(float @value)
	{
		_object.Call(MethodName.SetLimitSpringFrequency, @value);
	}

	public float GetLimitSpringDamping()
	{
		return (float)_object.Call(MethodName.GetLimitSpringDamping);
	}

	public void SetLimitSpringDamping(float @value)
	{
		_object.Call(MethodName.SetLimitSpringDamping, @value);
	}

	public bool GetMotorEnabled()
	{
		return (bool)_object.Call(MethodName.GetMotorEnabled);
	}

	public void SetMotorEnabled(bool @enabled)
	{
		_object.Call(MethodName.SetMotorEnabled, @enabled);
	}

	public float GetMotorTargetVelocity()
	{
		return (float)_object.Call(MethodName.GetMotorTargetVelocity);
	}

	public void SetMotorTargetVelocity(float @value)
	{
		_object.Call(MethodName.SetMotorTargetVelocity, @value);
	}

	public float GetMotorMaxForce()
	{
		return (float)_object.Call(MethodName.GetMotorMaxForce);
	}

	public void SetMotorMaxForce(float @value)
	{
		_object.Call(MethodName.SetMotorMaxForce, @value);
	}

	public float GetAppliedForce()
	{
		return (float)_object.Call(MethodName.GetAppliedForce);
	}

	public float GetAppliedTorque()
	{
		return (float)_object.Call(MethodName.GetAppliedTorque);
	}

	#endregion
}
