// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;
using Object = Godot.GodotObject;

namespace GDExtensionBindgen;

public class JoltPhysicsServer3DExtension
{
	// Engine object used for calling engine methods
	protected PhysicsServer3DExtension _object;

	public JoltPhysicsServer3DExtension() : this(NativeName)
	{
	}
	protected JoltPhysicsServer3DExtension(StringName @class) : this(ClassDB.Instantiate(@class))
	{
	}
	protected JoltPhysicsServer3DExtension(Variant variant) : this((PhysicsServer3DExtension) variant)
	{
	}
	protected JoltPhysicsServer3DExtension([NotNull] PhysicsServer3DExtension @object)
	{
		_object = @object;
	}

	public static implicit operator PhysicsServer3DExtension(JoltPhysicsServer3DExtension self) => self?._object;
	public static implicit operator Variant(JoltPhysicsServer3DExtension self) => self?._object;
	public static explicit operator JoltPhysicsServer3DExtension(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public class PropertyName : PhysicsServer3DExtension.PropertyName
	{

	}

	public class MethodName : PhysicsServer3DExtension.MethodName
	{
		public static readonly StringName DumpDebugSnapshots = "dump_debug_snapshots";
		public static readonly StringName SpaceDumpDebugSnapshot = "space_dump_debug_snapshot";
		public static readonly StringName JointGetEnabled = "joint_get_enabled";
		public static readonly StringName JointSetEnabled = "joint_set_enabled";
		public static readonly StringName JointGetSolverVelocityIterations = "joint_get_solver_velocity_iterations";
		public static readonly StringName JointSetSolverVelocityIterations = "joint_set_solver_velocity_iterations";
		public static readonly StringName JointGetSolverPositionIterations = "joint_get_solver_position_iterations";
		public static readonly StringName JointSetSolverPositionIterations = "joint_set_solver_position_iterations";
		public static readonly StringName PinJointGetAppliedForce = "pin_joint_get_applied_force";
		public static readonly StringName HingeJointGetJoltParam = "hinge_joint_get_jolt_param";
		public static readonly StringName HingeJointSetJoltParam = "hinge_joint_set_jolt_param";
		public static readonly StringName HingeJointGetJoltFlag = "hinge_joint_get_jolt_flag";
		public static readonly StringName HingeJointSetJoltFlag = "hinge_joint_set_jolt_flag";
		public static readonly StringName HingeJointGetAppliedForce = "hinge_joint_get_applied_force";
		public static readonly StringName HingeJointGetAppliedTorque = "hinge_joint_get_applied_torque";
		public static readonly StringName SliderJointGetJoltParam = "slider_joint_get_jolt_param";
		public static readonly StringName SliderJointSetJoltParam = "slider_joint_set_jolt_param";
		public static readonly StringName SliderJointGetJoltFlag = "slider_joint_get_jolt_flag";
		public static readonly StringName SliderJointSetJoltFlag = "slider_joint_set_jolt_flag";
		public static readonly StringName SliderJointGetAppliedForce = "slider_joint_get_applied_force";
		public static readonly StringName SliderJointGetAppliedTorque = "slider_joint_get_applied_torque";
		public static readonly StringName ConeTwistJointGetJoltParam = "cone_twist_joint_get_jolt_param";
		public static readonly StringName ConeTwistJointSetJoltParam = "cone_twist_joint_set_jolt_param";
		public static readonly StringName ConeTwistJointGetJoltFlag = "cone_twist_joint_get_jolt_flag";
		public static readonly StringName ConeTwistJointSetJoltFlag = "cone_twist_joint_set_jolt_flag";
		public static readonly StringName ConeTwistJointGetAppliedForce = "cone_twist_joint_get_applied_force";
		public static readonly StringName ConeTwistJointGetAppliedTorque = "cone_twist_joint_get_applied_torque";
		public static readonly StringName Generic6DofJointGetJoltParam = "generic_6dof_joint_get_jolt_param";
		public static readonly StringName Generic6DofJointSetJoltParam = "generic_6dof_joint_set_jolt_param";
		public static readonly StringName Generic6DofJointGetJoltFlag = "generic_6dof_joint_get_jolt_flag";
		public static readonly StringName Generic6DofJointSetJoltFlag = "generic_6dof_joint_set_jolt_flag";
		public static readonly StringName Generic6DofJointGetAppliedForce = "generic_6dof_joint_get_applied_force";
		public static readonly StringName Generic6DofJointGetAppliedTorque = "generic_6dof_joint_get_applied_torque";
	}

	public class SignalName : PhysicsServer3DExtension.SignalName
	{

	}

	private static readonly StringName NativeName = "JoltPhysicsServer3DExtension";

	#region Enums

	public enum HingeJointParamJolt : long
	{
		HingeJointLimitSpringFrequency = 100L,
		HingeJointLimitSpringDamping = 101L,
		HingeJointMotorMaxTorque = 102L,
	}

	public enum HingeJointFlagJolt : long
	{
		HingeJointFlagUseLimitSpring = 100L,
	}

	public enum SliderJointParamJolt : long
	{
		SliderJointLimitSpringFrequency = 100L,
		SliderJointLimitSpringDamping = 101L,
		SliderJointMotorTargetVelocity = 102L,
		SliderJointMotorMaxForce = 103L,
	}

	public enum SliderJointFlagJolt : long
	{
		SliderJointFlagUseLimit = 100L,
		SliderJointFlagUseLimitSpring = 101L,
		SliderJointFlagEnableMotor = 102L,
	}

	public enum ConeTwistJointParamJolt : long
	{
		ConeTwistJointSwingMotorTargetVelocityY = 100L,
		ConeTwistJointSwingMotorTargetVelocityZ = 101L,
		ConeTwistJointTwistMotorTargetVelocity = 102L,
		ConeTwistJointSwingMotorMaxTorque = 103L,
		ConeTwistJointTwistMotorMaxTorque = 104L,
	}

	public enum ConeTwistJointFlagJolt : long
	{
		ConeTwistJointFlagUseSwingLimit = 100L,
		ConeTwistJointFlagUseTwistLimit = 101L,
		ConeTwistJointFlagEnableSwingMotor = 102L,
		ConeTwistJointFlagEnableTwistMotor = 103L,
	}

	public enum G6DOFJointAxisParamJolt : long
	{
		G6dofJointLinearSpringFrequency = 100L,
		G6dofJointLinearLimitSpringFrequency = 101L,
		G6dofJointLinearLimitSpringDamping = 102L,
		G6dofJointAngularSpringFrequency = 103L,
		G6dofJointLinearSpringMaxForce = 104L,
		G6dofJointAngularSpringMaxTorque = 105L,
	}

	public enum G6DOFJointAxisFlagJolt : long
	{
		G6dofJointFlagEnableLinearLimitSpring = 100L,
		G6dofJointFlagEnableLinearSpringFrequency = 101L,
		G6dofJointFlagEnableAngularSpringFrequency = 102L,
	}

	#endregion

	#region Methods

	public void DumpDebugSnapshots(string @dir)
	{
		_object.Call(MethodName.DumpDebugSnapshots, @dir);
	}

	public void SpaceDumpDebugSnapshot(Godot.Rid @space, string @dir)
	{
		_object.Call(MethodName.SpaceDumpDebugSnapshot, @space, @dir);
	}

	public bool JointGetEnabled(Godot.Rid @joint)
	{
		return (bool)_object.Call(MethodName.JointGetEnabled, @joint);
	}

	public void JointSetEnabled(Godot.Rid @joint, bool @enabled)
	{
		_object.Call(MethodName.JointSetEnabled, @joint, @enabled);
	}

	public int JointGetSolverVelocityIterations(Godot.Rid @joint)
	{
		return (int)_object.Call(MethodName.JointGetSolverVelocityIterations, @joint);
	}

	public void JointSetSolverVelocityIterations(Godot.Rid @joint, int @value)
	{
		_object.Call(MethodName.JointSetSolverVelocityIterations, @joint, @value);
	}

	public int JointGetSolverPositionIterations(Godot.Rid @joint)
	{
		return (int)_object.Call(MethodName.JointGetSolverPositionIterations, @joint);
	}

	public void JointSetSolverPositionIterations(Godot.Rid @joint, int @value)
	{
		_object.Call(MethodName.JointSetSolverPositionIterations, @joint, @value);
	}

	public float PinJointGetAppliedForce(Godot.Rid @joint)
	{
		return (float)_object.Call(MethodName.PinJointGetAppliedForce, @joint);
	}

	public float HingeJointGetJoltParam(Godot.Rid @joint, JoltPhysicsServer3DExtension.HingeJointParamJolt @param)
	{
		return (float)_object.Call(MethodName.HingeJointGetJoltParam, @joint, (int)@param);
	}

	public void HingeJointSetJoltParam(Godot.Rid @joint, JoltPhysicsServer3DExtension.HingeJointParamJolt @param, float @value)
	{
		_object.Call(MethodName.HingeJointSetJoltParam, @joint, (int)@param, @value);
	}

	public bool HingeJointGetJoltFlag(Godot.Rid @joint, JoltPhysicsServer3DExtension.HingeJointFlagJolt @flag)
	{
		return (bool)_object.Call(MethodName.HingeJointGetJoltFlag, @joint, (int)@flag);
	}

	public void HingeJointSetJoltFlag(Godot.Rid @joint, JoltPhysicsServer3DExtension.HingeJointFlagJolt @flag, bool @value)
	{
		_object.Call(MethodName.HingeJointSetJoltFlag, @joint, (int)@flag, @value);
	}

	public float HingeJointGetAppliedForce(Godot.Rid @joint)
	{
		return (float)_object.Call(MethodName.HingeJointGetAppliedForce, @joint);
	}

	public float HingeJointGetAppliedTorque(Godot.Rid @joint)
	{
		return (float)_object.Call(MethodName.HingeJointGetAppliedTorque, @joint);
	}

	public float SliderJointGetJoltParam(Godot.Rid @joint, JoltPhysicsServer3DExtension.SliderJointParamJolt @param)
	{
		return (float)_object.Call(MethodName.SliderJointGetJoltParam, @joint, (int)@param);
	}

	public void SliderJointSetJoltParam(Godot.Rid @joint, JoltPhysicsServer3DExtension.SliderJointParamJolt @param, float @value)
	{
		_object.Call(MethodName.SliderJointSetJoltParam, @joint, (int)@param, @value);
	}

	public bool SliderJointGetJoltFlag(Godot.Rid @joint, JoltPhysicsServer3DExtension.SliderJointFlagJolt @flag)
	{
		return (bool)_object.Call(MethodName.SliderJointGetJoltFlag, @joint, (int)@flag);
	}

	public void SliderJointSetJoltFlag(Godot.Rid @joint, JoltPhysicsServer3DExtension.SliderJointFlagJolt @flag, bool @value)
	{
		_object.Call(MethodName.SliderJointSetJoltFlag, @joint, (int)@flag, @value);
	}

	public float SliderJointGetAppliedForce(Godot.Rid @joint)
	{
		return (float)_object.Call(MethodName.SliderJointGetAppliedForce, @joint);
	}

	public float SliderJointGetAppliedTorque(Godot.Rid @joint)
	{
		return (float)_object.Call(MethodName.SliderJointGetAppliedTorque, @joint);
	}

	public float ConeTwistJointGetJoltParam(Godot.Rid @joint, JoltPhysicsServer3DExtension.ConeTwistJointParamJolt @param)
	{
		return (float)_object.Call(MethodName.ConeTwistJointGetJoltParam, @joint, (int)@param);
	}

	public void ConeTwistJointSetJoltParam(Godot.Rid @joint, JoltPhysicsServer3DExtension.ConeTwistJointParamJolt @param, float @value)
	{
		_object.Call(MethodName.ConeTwistJointSetJoltParam, @joint, (int)@param, @value);
	}

	public bool ConeTwistJointGetJoltFlag(Godot.Rid @joint, JoltPhysicsServer3DExtension.ConeTwistJointFlagJolt @flag)
	{
		return (bool)_object.Call(MethodName.ConeTwistJointGetJoltFlag, @joint, (int)@flag);
	}

	public void ConeTwistJointSetJoltFlag(Godot.Rid @joint, JoltPhysicsServer3DExtension.ConeTwistJointFlagJolt @flag, bool @value)
	{
		_object.Call(MethodName.ConeTwistJointSetJoltFlag, @joint, (int)@flag, @value);
	}

	public float ConeTwistJointGetAppliedForce(Godot.Rid @joint)
	{
		return (float)_object.Call(MethodName.ConeTwistJointGetAppliedForce, @joint);
	}

	public float ConeTwistJointGetAppliedTorque(Godot.Rid @joint)
	{
		return (float)_object.Call(MethodName.ConeTwistJointGetAppliedTorque, @joint);
	}

	public float Generic6DofJointGetJoltParam(Godot.Rid @joint, Vector3.Axis @axis, JoltPhysicsServer3DExtension.G6DOFJointAxisParamJolt @param)
	{
		return (float)_object.Call(MethodName.Generic6DofJointGetJoltParam, @joint, (int)@axis, (int)@param);
	}

	public void Generic6DofJointSetJoltParam(Godot.Rid @joint, Vector3.Axis @axis, JoltPhysicsServer3DExtension.G6DOFJointAxisParamJolt @param, float @value)
	{
		_object.Call(MethodName.Generic6DofJointSetJoltParam, @joint, (int)@axis, (int)@param, @value);
	}

	public bool Generic6DofJointGetJoltFlag(Godot.Rid @joint, Vector3.Axis @axis, JoltPhysicsServer3DExtension.G6DOFJointAxisFlagJolt @flag)
	{
		return (bool)_object.Call(MethodName.Generic6DofJointGetJoltFlag, @joint, (int)@axis, (int)@flag);
	}

	public void Generic6DofJointSetJoltFlag(Godot.Rid @joint, Vector3.Axis @axis, JoltPhysicsServer3DExtension.G6DOFJointAxisFlagJolt @flag, bool @value)
	{
		_object.Call(MethodName.Generic6DofJointSetJoltFlag, @joint, (int)@axis, (int)@flag, @value);
	}

	public float Generic6DofJointGetAppliedForce(Godot.Rid @joint)
	{
		return (float)_object.Call(MethodName.Generic6DofJointGetAppliedForce, @joint);
	}

	public float Generic6DofJointGetAppliedTorque(Godot.Rid @joint)
	{
		return (float)_object.Call(MethodName.Generic6DofJointGetAppliedTorque, @joint);
	}

	#endregion

	#region Inherited Methods

	public bool BodyTestMotionIsExcludingBody(Godot.Rid @body)
	{
		return _object.BodyTestMotionIsExcludingBody(@body);
	}

	public bool BodyTestMotionIsExcludingObject(int @object)
	{
		return _object.BodyTestMotionIsExcludingObject(@object);
	}

	public Godot.Rid WorldBoundaryShapeCreate()
	{
		return _object.WorldBoundaryShapeCreate();
	}

	public Godot.Rid SeparationRayShapeCreate()
	{
		return _object.SeparationRayShapeCreate();
	}

	public Godot.Rid SphereShapeCreate()
	{
		return _object.SphereShapeCreate();
	}

	public Godot.Rid BoxShapeCreate()
	{
		return _object.BoxShapeCreate();
	}

	public Godot.Rid CapsuleShapeCreate()
	{
		return _object.CapsuleShapeCreate();
	}

	public Godot.Rid CylinderShapeCreate()
	{
		return _object.CylinderShapeCreate();
	}

	public Godot.Rid ConvexPolygonShapeCreate()
	{
		return _object.ConvexPolygonShapeCreate();
	}

	public Godot.Rid ConcavePolygonShapeCreate()
	{
		return _object.ConcavePolygonShapeCreate();
	}

	public Godot.Rid HeightmapShapeCreate()
	{
		return _object.HeightmapShapeCreate();
	}

	public Godot.Rid CustomShapeCreate()
	{
		return _object.CustomShapeCreate();
	}

	public void ShapeSetData(Godot.Rid @shape, Variant @data)
	{
		_object.ShapeSetData(@shape, @data);
	}

	public void ShapeSetMargin(Godot.Rid @shape, float @margin)
	{
		_object.ShapeSetMargin(@shape, @margin);
	}

	public PhysicsServer3D.ShapeType ShapeGetType(Godot.Rid @shape)
	{
		return _object.ShapeGetType(@shape);
	}

	public Variant ShapeGetData(Godot.Rid @shape)
	{
		return _object.ShapeGetData(@shape);
	}

	public float ShapeGetMargin(Godot.Rid @shape)
	{
		return _object.ShapeGetMargin(@shape);
	}

	public Godot.Rid SpaceCreate()
	{
		return _object.SpaceCreate();
	}

	public void SpaceSetActive(Godot.Rid @space, bool @active)
	{
		_object.SpaceSetActive(@space, @active);
	}

	public bool SpaceIsActive(Godot.Rid @space)
	{
		return _object.SpaceIsActive(@space);
	}

	public void SpaceSetParam(Godot.Rid @space, PhysicsServer3D.SpaceParameter @param, float @value)
	{
		_object.SpaceSetParam(@space, (int)@param, @value);
	}

	public float SpaceGetParam(Godot.Rid @space, PhysicsServer3D.SpaceParameter @param)
	{
		return _object.SpaceGetParam(@space, (int)@param);
	}

	public PhysicsDirectSpaceState3D SpaceGetDirectState(Godot.Rid @space)
	{
		return _object.SpaceGetDirectState(@space);
	}

	public Godot.Rid AreaCreate()
	{
		return _object.AreaCreate();
	}

	public void AreaSetSpace(Godot.Rid @area, Godot.Rid @space)
	{
		_object.AreaSetSpace(@area, @space);
	}

	public Godot.Rid AreaGetSpace(Godot.Rid @area)
	{
		return _object.AreaGetSpace(@area);
	}

	public void AreaAddShape(Godot.Rid @area, Godot.Rid @shape, Godot.Transform3D? @transform = null, bool @disabled = false)
	{
		@transform ??= Godot.Transform3D.Identity;
		_object.AreaAddShape(@area, @shape, @transform, @disabled);
	}

	public void AreaSetShape(Godot.Rid @area, int @shape_idx, Godot.Rid @shape)
	{
		_object.AreaSetShape(@area, @shape_idx, @shape);
	}

	public void AreaSetShapeTransform(Godot.Rid @area, int @shape_idx, Godot.Transform3D @transform)
	{
		_object.AreaSetShapeTransform(@area, @shape_idx, @transform);
	}

	public void AreaSetShapeDisabled(Godot.Rid @area, int @shape_idx, bool @disabled)
	{
		_object.AreaSetShapeDisabled(@area, @shape_idx, @disabled);
	}

	public int AreaGetShapeCount(Godot.Rid @area)
	{
		return _object.AreaGetShapeCount(@area);
	}

	public Godot.Rid AreaGetShape(Godot.Rid @area, int @shape_idx)
	{
		return _object.AreaGetShape(@area, @shape_idx);
	}

	public Godot.Transform3D AreaGetShapeTransform(Godot.Rid @area, int @shape_idx)
	{
		return _object.AreaGetShapeTransform(@area, @shape_idx);
	}

	public void AreaRemoveShape(Godot.Rid @area, int @shape_idx)
	{
		_object.AreaRemoveShape(@area, @shape_idx);
	}

	public void AreaClearShapes(Godot.Rid @area)
	{
		_object.AreaClearShapes(@area);
	}

	public void AreaSetCollisionLayer(Godot.Rid @area, int @layer)
	{
		_object.AreaSetCollisionLayer(@area, @layer);
	}

	public int AreaGetCollisionLayer(Godot.Rid @area)
	{
		return _object.AreaGetCollisionLayer(@area);
	}

	public void AreaSetCollisionMask(Godot.Rid @area, int @mask)
	{
		_object.AreaSetCollisionMask(@area, @mask);
	}

	public int AreaGetCollisionMask(Godot.Rid @area)
	{
		return _object.AreaGetCollisionMask(@area);
	}

	public void AreaSetParam(Godot.Rid @area, PhysicsServer3D.AreaParameter @param, Variant @value)
	{
		_object.AreaSetParam(@area, (int)@param, @value);
	}

	public void AreaSetTransform(Godot.Rid @area, Godot.Transform3D @transform)
	{
		_object.AreaSetTransform(@area, @transform);
	}

	public Variant AreaGetParam(Godot.Rid @area, PhysicsServer3D.AreaParameter @param)
	{
		return _object.AreaGetParam(@area, (int)@param);
	}

	public Godot.Transform3D AreaGetTransform(Godot.Rid @area)
	{
		return _object.AreaGetTransform(@area);
	}

	public void AreaAttachObjectInstanceId(Godot.Rid @area, int @id)
	{
		_object.AreaAttachObjectInstanceId(@area, @id);
	}

	public int AreaGetObjectInstanceId(Godot.Rid @area)
	{
		return _object.AreaGetObjectInstanceId(@area);
	}

	public void AreaSetMonitorCallback(Godot.Rid @area, Godot.Callable @callback)
	{
		_object.AreaSetMonitorCallback(@area, @callback);
	}

	public void AreaSetAreaMonitorCallback(Godot.Rid @area, Godot.Callable @callback)
	{
		_object.AreaSetAreaMonitorCallback(@area, @callback);
	}

	public void AreaSetMonitorable(Godot.Rid @area, bool @monitorable)
	{
		_object.AreaSetMonitorable(@area, @monitorable);
	}

	public void AreaSetRayPickable(Godot.Rid @area, bool @enable)
	{
		_object.AreaSetRayPickable(@area, @enable);
	}

	public Godot.Rid BodyCreate()
	{
		return _object.BodyCreate();
	}

	public void BodySetSpace(Godot.Rid @body, Godot.Rid @space)
	{
		_object.BodySetSpace(@body, @space);
	}

	public Godot.Rid BodyGetSpace(Godot.Rid @body)
	{
		return _object.BodyGetSpace(@body);
	}

	public void BodySetMode(Godot.Rid @body, PhysicsServer3D.BodyMode @mode)
	{
		_object.BodySetMode(@body, (int)@mode);
	}

	public PhysicsServer3D.BodyMode BodyGetMode(Godot.Rid @body)
	{
		return _object.BodyGetMode(@body);
	}

	public void BodySetCollisionLayer(Godot.Rid @body, int @layer)
	{
		_object.BodySetCollisionLayer(@body, @layer);
	}

	public int BodyGetCollisionLayer(Godot.Rid @body)
	{
		return _object.BodyGetCollisionLayer(@body);
	}

	public void BodySetCollisionMask(Godot.Rid @body, int @mask)
	{
		_object.BodySetCollisionMask(@body, @mask);
	}

	public int BodyGetCollisionMask(Godot.Rid @body)
	{
		return _object.BodyGetCollisionMask(@body);
	}

	public void BodySetCollisionPriority(Godot.Rid @body, float @priority)
	{
		_object.BodySetCollisionPriority(@body, @priority);
	}

	public float BodyGetCollisionPriority(Godot.Rid @body)
	{
		return _object.BodyGetCollisionPriority(@body);
	}

	public void BodyAddShape(Godot.Rid @body, Godot.Rid @shape, Godot.Transform3D? @transform = null, bool @disabled = false)
	{
		@transform ??= Godot.Transform3D.Identity;
		_object.BodyAddShape(@body, @shape, @transform, @disabled);
	}

	public void BodySetShape(Godot.Rid @body, int @shape_idx, Godot.Rid @shape)
	{
		_object.BodySetShape(@body, @shape_idx, @shape);
	}

	public void BodySetShapeTransform(Godot.Rid @body, int @shape_idx, Godot.Transform3D @transform)
	{
		_object.BodySetShapeTransform(@body, @shape_idx, @transform);
	}

	public void BodySetShapeDisabled(Godot.Rid @body, int @shape_idx, bool @disabled)
	{
		_object.BodySetShapeDisabled(@body, @shape_idx, @disabled);
	}

	public int BodyGetShapeCount(Godot.Rid @body)
	{
		return _object.BodyGetShapeCount(@body);
	}

	public Godot.Rid BodyGetShape(Godot.Rid @body, int @shape_idx)
	{
		return _object.BodyGetShape(@body, @shape_idx);
	}

	public Godot.Transform3D BodyGetShapeTransform(Godot.Rid @body, int @shape_idx)
	{
		return _object.BodyGetShapeTransform(@body, @shape_idx);
	}

	public void BodyRemoveShape(Godot.Rid @body, int @shape_idx)
	{
		_object.BodyRemoveShape(@body, @shape_idx);
	}

	public void BodyClearShapes(Godot.Rid @body)
	{
		_object.BodyClearShapes(@body);
	}

	public void BodyAttachObjectInstanceId(Godot.Rid @body, int @id)
	{
		_object.BodyAttachObjectInstanceId(@body, @id);
	}

	public int BodyGetObjectInstanceId(Godot.Rid @body)
	{
		return _object.BodyGetObjectInstanceId(@body);
	}

	public void BodySetEnableContinuousCollisionDetection(Godot.Rid @body, bool @enable)
	{
		_object.BodySetEnableContinuousCollisionDetection(@body, @enable);
	}

	public bool BodyIsContinuousCollisionDetectionEnabled(Godot.Rid @body)
	{
		return _object.BodyIsContinuousCollisionDetectionEnabled(@body);
	}

	public void BodySetParam(Godot.Rid @body, PhysicsServer3D.BodyParameter @param, Variant @value)
	{
		_object.BodySetParam(@body, (int)@param, @value);
	}

	public Variant BodyGetParam(Godot.Rid @body, PhysicsServer3D.BodyParameter @param)
	{
		return _object.BodyGetParam(@body, (int)@param);
	}

	public void BodyResetMassProperties(Godot.Rid @body)
	{
		_object.BodyResetMassProperties(@body);
	}

	public void BodySetState(Godot.Rid @body, PhysicsServer3D.BodyState @state, Variant @value)
	{
		_object.BodySetState(@body, (int)@state, @value);
	}

	public Variant BodyGetState(Godot.Rid @body, PhysicsServer3D.BodyState @state)
	{
		return _object.BodyGetState(@body, (int)@state);
	}

	public void BodyApplyCentralImpulse(Godot.Rid @body, Godot.Vector3 @impulse)
	{
		_object.BodyApplyCentralImpulse(@body, @impulse);
	}

	public void BodyApplyImpulse(Godot.Rid @body, Godot.Vector3 @impulse, Godot.Vector3? @position = null)
	{
		@position ??= new(0.0f, 0.0f, 0.0f);
		_object.BodyApplyImpulse(@body, @impulse, @position);
	}

	public void BodyApplyTorqueImpulse(Godot.Rid @body, Godot.Vector3 @impulse)
	{
		_object.BodyApplyTorqueImpulse(@body, @impulse);
	}

	public void BodyApplyCentralForce(Godot.Rid @body, Godot.Vector3 @force)
	{
		_object.BodyApplyCentralForce(@body, @force);
	}

	public void BodyApplyForce(Godot.Rid @body, Godot.Vector3 @force, Godot.Vector3? @position = null)
	{
		@position ??= new(0.0f, 0.0f, 0.0f);
		_object.BodyApplyForce(@body, @force, @position);
	}

	public void BodyApplyTorque(Godot.Rid @body, Godot.Vector3 @torque)
	{
		_object.BodyApplyTorque(@body, @torque);
	}

	public void BodyAddConstantCentralForce(Godot.Rid @body, Godot.Vector3 @force)
	{
		_object.BodyAddConstantCentralForce(@body, @force);
	}

	public void BodyAddConstantForce(Godot.Rid @body, Godot.Vector3 @force, Godot.Vector3? @position = null)
	{
		@position ??= new(0.0f, 0.0f, 0.0f);
		_object.BodyAddConstantForce(@body, @force, @position);
	}

	public void BodyAddConstantTorque(Godot.Rid @body, Godot.Vector3 @torque)
	{
		_object.BodyAddConstantTorque(@body, @torque);
	}

	public void BodySetConstantForce(Godot.Rid @body, Godot.Vector3 @force)
	{
		_object.BodySetConstantForce(@body, @force);
	}

	public Godot.Vector3 BodyGetConstantForce(Godot.Rid @body)
	{
		return _object.BodyGetConstantForce(@body);
	}

	public void BodySetConstantTorque(Godot.Rid @body, Godot.Vector3 @torque)
	{
		_object.BodySetConstantTorque(@body, @torque);
	}

	public Godot.Vector3 BodyGetConstantTorque(Godot.Rid @body)
	{
		return _object.BodyGetConstantTorque(@body);
	}

	public void BodySetAxisVelocity(Godot.Rid @body, Godot.Vector3 @axis_velocity)
	{
		_object.BodySetAxisVelocity(@body, @axis_velocity);
	}

	public void BodySetAxisLock(Godot.Rid @body, PhysicsServer3D.BodyAxis @axis, bool @lock)
	{
		_object.BodySetAxisLock(@body, (int)@axis, @lock);
	}

	public bool BodyIsAxisLocked(Godot.Rid @body, PhysicsServer3D.BodyAxis @axis)
	{
		return _object.BodyIsAxisLocked(@body, (int)@axis);
	}

	public void BodyAddCollisionException(Godot.Rid @body, Godot.Rid @excepted_body)
	{
		_object.BodyAddCollisionException(@body, @excepted_body);
	}

	public void BodyRemoveCollisionException(Godot.Rid @body, Godot.Rid @excepted_body)
	{
		_object.BodyRemoveCollisionException(@body, @excepted_body);
	}

	public void BodySetMaxContactsReported(Godot.Rid @body, int @amount)
	{
		_object.BodySetMaxContactsReported(@body, @amount);
	}

	public int BodyGetMaxContactsReported(Godot.Rid @body)
	{
		return _object.BodyGetMaxContactsReported(@body);
	}

	public void BodySetOmitForceIntegration(Godot.Rid @body, bool @enable)
	{
		_object.BodySetOmitForceIntegration(@body, @enable);
	}

	public bool BodyIsOmittingForceIntegration(Godot.Rid @body)
	{
		return _object.BodyIsOmittingForceIntegration(@body);
	}

	public void BodySetStateSyncCallback(Godot.Rid @body, Godot.Callable @callable)
	{
		_object.BodySetStateSyncCallback(@body, @callable);
	}

	public void BodySetForceIntegrationCallback(Godot.Rid @body, Godot.Callable @callable, Variant @userdata = default)
	{
		_object.BodySetForceIntegrationCallback(@body, @callable, @userdata);
	}

	public void BodySetRayPickable(Godot.Rid @body, bool @enable)
	{
		_object.BodySetRayPickable(@body, @enable);
	}

	public bool BodyTestMotion(Godot.Rid @body, PhysicsTestMotionParameters3D @parameters, PhysicsTestMotionResult3D @result = default)
	{
		return _object.BodyTestMotion(@body, @parameters, @result);
	}

	public PhysicsDirectBodyState3D BodyGetDirectState(Godot.Rid @body)
	{
		return _object.BodyGetDirectState(@body);
	}

	public Godot.Rid SoftBodyCreate()
	{
		return _object.SoftBodyCreate();
	}

	public void SoftBodyUpdateRenderingServer(Godot.Rid @body, PhysicsServer3DRenderingServerHandler @rendering_server_handler)
	{
		_object.SoftBodyUpdateRenderingServer(@body, @rendering_server_handler);
	}

	public void SoftBodySetSpace(Godot.Rid @body, Godot.Rid @space)
	{
		_object.SoftBodySetSpace(@body, @space);
	}

	public Godot.Rid SoftBodyGetSpace(Godot.Rid @body)
	{
		return _object.SoftBodyGetSpace(@body);
	}

	public void SoftBodySetMesh(Godot.Rid @body, Godot.Rid @mesh)
	{
		_object.SoftBodySetMesh(@body, @mesh);
	}

	public Godot.Aabb SoftBodyGetBounds(Godot.Rid @body)
	{
		return _object.SoftBodyGetBounds(@body);
	}

	public void SoftBodySetCollisionLayer(Godot.Rid @body, int @layer)
	{
		_object.SoftBodySetCollisionLayer(@body, @layer);
	}

	public int SoftBodyGetCollisionLayer(Godot.Rid @body)
	{
		return _object.SoftBodyGetCollisionLayer(@body);
	}

	public void SoftBodySetCollisionMask(Godot.Rid @body, int @mask)
	{
		_object.SoftBodySetCollisionMask(@body, @mask);
	}

	public int SoftBodyGetCollisionMask(Godot.Rid @body)
	{
		return _object.SoftBodyGetCollisionMask(@body);
	}

	public void SoftBodyAddCollisionException(Godot.Rid @body, Godot.Rid @body_b)
	{
		_object.SoftBodyAddCollisionException(@body, @body_b);
	}

	public void SoftBodyRemoveCollisionException(Godot.Rid @body, Godot.Rid @body_b)
	{
		_object.SoftBodyRemoveCollisionException(@body, @body_b);
	}

	public void SoftBodySetState(Godot.Rid @body, PhysicsServer3D.BodyState @state, Variant @variant)
	{
		_object.SoftBodySetState(@body, (int)@state, @variant);
	}

	public Variant SoftBodyGetState(Godot.Rid @body, PhysicsServer3D.BodyState @state)
	{
		return _object.SoftBodyGetState(@body, (int)@state);
	}

	public void SoftBodySetTransform(Godot.Rid @body, Godot.Transform3D @transform)
	{
		_object.SoftBodySetTransform(@body, @transform);
	}

	public void SoftBodySetRayPickable(Godot.Rid @body, bool @enable)
	{
		_object.SoftBodySetRayPickable(@body, @enable);
	}

	public void SoftBodySetSimulationPrecision(Godot.Rid @body, int @simulation_precision)
	{
		_object.SoftBodySetSimulationPrecision(@body, @simulation_precision);
	}

	public int SoftBodyGetSimulationPrecision(Godot.Rid @body)
	{
		return _object.SoftBodyGetSimulationPrecision(@body);
	}

	public void SoftBodySetTotalMass(Godot.Rid @body, float @total_mass)
	{
		_object.SoftBodySetTotalMass(@body, @total_mass);
	}

	public float SoftBodyGetTotalMass(Godot.Rid @body)
	{
		return _object.SoftBodyGetTotalMass(@body);
	}

	public void SoftBodySetLinearStiffness(Godot.Rid @body, float @stiffness)
	{
		_object.SoftBodySetLinearStiffness(@body, @stiffness);
	}

	public float SoftBodyGetLinearStiffness(Godot.Rid @body)
	{
		return _object.SoftBodyGetLinearStiffness(@body);
	}

	public void SoftBodySetPressureCoefficient(Godot.Rid @body, float @pressure_coefficient)
	{
		_object.SoftBodySetPressureCoefficient(@body, @pressure_coefficient);
	}

	public float SoftBodyGetPressureCoefficient(Godot.Rid @body)
	{
		return _object.SoftBodyGetPressureCoefficient(@body);
	}

	public void SoftBodySetDampingCoefficient(Godot.Rid @body, float @damping_coefficient)
	{
		_object.SoftBodySetDampingCoefficient(@body, @damping_coefficient);
	}

	public float SoftBodyGetDampingCoefficient(Godot.Rid @body)
	{
		return _object.SoftBodyGetDampingCoefficient(@body);
	}

	public void SoftBodySetDragCoefficient(Godot.Rid @body, float @drag_coefficient)
	{
		_object.SoftBodySetDragCoefficient(@body, @drag_coefficient);
	}

	public float SoftBodyGetDragCoefficient(Godot.Rid @body)
	{
		return _object.SoftBodyGetDragCoefficient(@body);
	}

	public void SoftBodyMovePoint(Godot.Rid @body, int @point_index, Godot.Vector3 @global_position)
	{
		_object.SoftBodyMovePoint(@body, @point_index, @global_position);
	}

	public Godot.Vector3 SoftBodyGetPointGlobalPosition(Godot.Rid @body, int @point_index)
	{
		return _object.SoftBodyGetPointGlobalPosition(@body, @point_index);
	}

	public void SoftBodyRemoveAllPinnedPoints(Godot.Rid @body)
	{
		_object.SoftBodyRemoveAllPinnedPoints(@body);
	}

	public void SoftBodyPinPoint(Godot.Rid @body, int @point_index, bool @pin)
	{
		_object.SoftBodyPinPoint(@body, @point_index, @pin);
	}

	public bool SoftBodyIsPointPinned(Godot.Rid @body, int @point_index)
	{
		return _object.SoftBodyIsPointPinned(@body, @point_index);
	}

	public Godot.Rid JointCreate()
	{
		return _object.JointCreate();
	}

	public void JointClear(Godot.Rid @joint)
	{
		_object.JointClear(@joint);
	}

	public void JointMakePin(Godot.Rid @joint, Godot.Rid @body_A, Godot.Vector3 @local_A, Godot.Rid @body_B, Godot.Vector3 @local_B)
	{
		_object.JointMakePin(@joint, @body_A, @local_A, @body_B, @local_B);
	}

	public void PinJointSetParam(Godot.Rid @joint, PhysicsServer3D.PinJointParam @param, float @value)
	{
		_object.PinJointSetParam(@joint, (int)@param, @value);
	}

	public float PinJointGetParam(Godot.Rid @joint, PhysicsServer3D.PinJointParam @param)
	{
		return _object.PinJointGetParam(@joint, (int)@param);
	}

	public void PinJointSetLocalA(Godot.Rid @joint, Godot.Vector3 @local_A)
	{
		_object.PinJointSetLocalA(@joint, @local_A);
	}

	public Godot.Vector3 PinJointGetLocalA(Godot.Rid @joint)
	{
		return _object.PinJointGetLocalA(@joint);
	}

	public void PinJointSetLocalB(Godot.Rid @joint, Godot.Vector3 @local_B)
	{
		_object.PinJointSetLocalB(@joint, @local_B);
	}

	public Godot.Vector3 PinJointGetLocalB(Godot.Rid @joint)
	{
		return _object.PinJointGetLocalB(@joint);
	}

	public void JointMakeHinge(Godot.Rid @joint, Godot.Rid @body_A, Godot.Transform3D @hinge_A, Godot.Rid @body_B, Godot.Transform3D @hinge_B)
	{
		_object.JointMakeHinge(@joint, @body_A, @hinge_A, @body_B, @hinge_B);
	}

	public void HingeJointSetParam(Godot.Rid @joint, PhysicsServer3D.HingeJointParam @param, float @value)
	{
		_object.HingeJointSetParam(@joint, (int)@param, @value);
	}

	public float HingeJointGetParam(Godot.Rid @joint, PhysicsServer3D.HingeJointParam @param)
	{
		return _object.HingeJointGetParam(@joint, (int)@param);
	}

	public void HingeJointSetFlag(Godot.Rid @joint, PhysicsServer3D.HingeJointFlag @flag, bool @enabled)
	{
		_object.HingeJointSetFlag(@joint, (int)@flag, @enabled);
	}

	public bool HingeJointGetFlag(Godot.Rid @joint, PhysicsServer3D.HingeJointFlag @flag)
	{
		return _object.HingeJointGetFlag(@joint, (int)@flag);
	}

	public void JointMakeSlider(Godot.Rid @joint, Godot.Rid @body_A, Godot.Transform3D @local_ref_A, Godot.Rid @body_B, Godot.Transform3D @local_ref_B)
	{
		_object.JointMakeSlider(@joint, @body_A, @local_ref_A, @body_B, @local_ref_B);
	}

	public void SliderJointSetParam(Godot.Rid @joint, PhysicsServer3D.SliderJointParam @param, float @value)
	{
		_object.SliderJointSetParam(@joint, (int)@param, @value);
	}

	public float SliderJointGetParam(Godot.Rid @joint, PhysicsServer3D.SliderJointParam @param)
	{
		return _object.SliderJointGetParam(@joint, (int)@param);
	}

	public void JointMakeConeTwist(Godot.Rid @joint, Godot.Rid @body_A, Godot.Transform3D @local_ref_A, Godot.Rid @body_B, Godot.Transform3D @local_ref_B)
	{
		_object.JointMakeConeTwist(@joint, @body_A, @local_ref_A, @body_B, @local_ref_B);
	}

	public void ConeTwistJointSetParam(Godot.Rid @joint, PhysicsServer3D.ConeTwistJointParam @param, float @value)
	{
		_object.ConeTwistJointSetParam(@joint, (int)@param, @value);
	}

	public float ConeTwistJointGetParam(Godot.Rid @joint, PhysicsServer3D.ConeTwistJointParam @param)
	{
		return _object.ConeTwistJointGetParam(@joint, (int)@param);
	}

	public PhysicsServer3D.JointType JointGetType(Godot.Rid @joint)
	{
		return _object.JointGetType(@joint);
	}

	public void JointSetSolverPriority(Godot.Rid @joint, int @priority)
	{
		_object.JointSetSolverPriority(@joint, @priority);
	}

	public int JointGetSolverPriority(Godot.Rid @joint)
	{
		return _object.JointGetSolverPriority(@joint);
	}

	public void JointDisableCollisionsBetweenBodies(Godot.Rid @joint, bool @disable)
	{
		_object.JointDisableCollisionsBetweenBodies(@joint, @disable);
	}

	public bool JointIsDisabledCollisionsBetweenBodies(Godot.Rid @joint)
	{
		return _object.JointIsDisabledCollisionsBetweenBodies(@joint);
	}

	public void JointMakeGeneric6Dof(Godot.Rid @joint, Godot.Rid @body_A, Godot.Transform3D @local_ref_A, Godot.Rid @body_B, Godot.Transform3D @local_ref_B)
	{
		_object.JointMakeGeneric6Dof(@joint, @body_A, @local_ref_A, @body_B, @local_ref_B);
	}

	public void Generic6DofJointSetParam(Godot.Rid @joint, Vector3.Axis @axis, PhysicsServer3D.G6DOFJointAxisParam @param, float @value)
	{
		_object.Generic6DofJointSetParam(@joint, (int)@axis, (int)@param, @value);
	}

	public float Generic6DofJointGetParam(Godot.Rid @joint, Vector3.Axis @axis, PhysicsServer3D.G6DOFJointAxisParam @param)
	{
		return _object.Generic6DofJointGetParam(@joint, (int)@axis, (int)@param);
	}

	public void Generic6DofJointSetFlag(Godot.Rid @joint, Vector3.Axis @axis, PhysicsServer3D.G6DOFJointAxisFlag @flag, bool @enable)
	{
		_object.Generic6DofJointSetFlag(@joint, (int)@axis, (int)@flag, @enable);
	}

	public bool Generic6DofJointGetFlag(Godot.Rid @joint, Vector3.Axis @axis, PhysicsServer3D.G6DOFJointAxisFlag @flag)
	{
		return _object.Generic6DofJointGetFlag(@joint, (int)@axis, (int)@flag);
	}

	public void FreeRid(Godot.Rid @rid)
	{
		_object.FreeRid(@rid);
	}

	public void SetActive(bool @active)
	{
		_object.SetActive(@active);
	}

	public int GetProcessInfo(PhysicsServer3D.ProcessInfo @process_info)
	{
		return _object.GetProcessInfo((int)@process_info);
	}

	public void Free()
	{
		_object.Free();
	}

	public string GetClass()
	{
		return _object.GetClass();
	}

	public bool IsClass(string @class)
	{
		return _object.IsClass(@class);
	}

	public void Set(Godot.StringName @property, Variant @value)
	{
		_object.Set(@property, @value);
	}

	public Variant Get(Godot.StringName @property)
	{
		return _object.Get(@property);
	}

	public void SetIndexed(Godot.NodePath @property_path, Variant @value)
	{
		_object.SetIndexed(@property_path, @value);
	}

	public Variant GetIndexed(Godot.NodePath @property_path)
	{
		return _object.GetIndexed(@property_path);
	}

	public Godot.Collections.Array<Godot.Collections.Dictionary> GetPropertyList()
	{
		return _object.GetPropertyList();
	}

	public Godot.Collections.Array<Godot.Collections.Dictionary> GetMethodList()
	{
		return _object.GetMethodList();
	}

	public bool PropertyCanRevert(Godot.StringName @property)
	{
		return _object.PropertyCanRevert(@property);
	}

	public Variant PropertyGetRevert(Godot.StringName @property)
	{
		return _object.PropertyGetRevert(@property);
	}

	public void Notification(int @what, bool @reversed = false)
	{
		_object.Notification(@what, @reversed);
	}

	public override string ToString()
	{
		return _object.ToString();
	}

	public ulong GetInstanceId()
	{
		return _object.GetInstanceId();
	}

	public void SetScript(Variant @script)
	{
		_object.SetScript(@script);
	}

	public Variant GetScript()
	{
		return _object.GetScript();
	}

	public void SetMeta(Godot.StringName @name, Variant @value)
	{
		_object.SetMeta(@name, @value);
	}

	public void RemoveMeta(Godot.StringName @name)
	{
		_object.RemoveMeta(@name);
	}

	public Variant GetMeta(Godot.StringName @name, Variant @default = default)
	{
		return _object.GetMeta(@name, @default);
	}

	public bool HasMeta(Godot.StringName @name)
	{
		return _object.HasMeta(@name);
	}

	public Godot.Collections.Array<StringName> GetMetaList()
	{
		return _object.GetMetaList();
	}

	public void AddUserSignal(string @signal, Godot.Collections.Array @arguments = null)
	{
		@arguments ??= new();
		_object.AddUserSignal(@signal, @arguments);
	}

	public bool HasUserSignal(Godot.StringName @signal)
	{
		return _object.HasUserSignal(@signal);
	}

	public void RemoveUserSignal(Godot.StringName @signal)
	{
		_object.RemoveUserSignal(@signal);
	}

	public Godot.Error EmitSignal(Godot.StringName @signal, params Variant[] varargs)
	{
		return _object.EmitSignal(@signal, varargs);
	}

	public Variant Call(Godot.StringName @method, params Variant[] varargs)
	{
		return _object.Call(@method, varargs);
	}

	public Variant CallDeferred(Godot.StringName @method, params Variant[] varargs)
	{
		return _object.CallDeferred(@method, varargs);
	}

	public void SetDeferred(Godot.StringName @property, Variant @value)
	{
		_object.SetDeferred(@property, @value);
	}

	public Variant Callv(Godot.StringName @method, Godot.Collections.Array @arg_array)
	{
		return _object.Callv(@method, @arg_array);
	}

	public bool HasMethod(Godot.StringName @method)
	{
		return _object.HasMethod(@method);
	}

	public int GetMethodArgumentCount(Godot.StringName @method)
	{
		return _object.GetMethodArgumentCount(@method);
	}

	public bool HasSignal(Godot.StringName @signal)
	{
		return _object.HasSignal(@signal);
	}

	public Godot.Collections.Array<Godot.Collections.Dictionary> GetSignalList()
	{
		return _object.GetSignalList();
	}

	public Godot.Collections.Array<Godot.Collections.Dictionary> GetSignalConnectionList(Godot.StringName @signal)
	{
		return _object.GetSignalConnectionList(@signal);
	}

	public Godot.Collections.Array<Godot.Collections.Dictionary> GetIncomingConnections()
	{
		return _object.GetIncomingConnections();
	}

	public Godot.Error Connect(Godot.StringName @signal, Godot.Callable @callable, uint @flags = (uint)0)
	{
		return _object.Connect(@signal, @callable, @flags);
	}

	public void Disconnect(Godot.StringName @signal, Godot.Callable @callable)
	{
		_object.Disconnect(@signal, @callable);
	}

	public bool IsConnected(Godot.StringName @signal, Godot.Callable @callable)
	{
		return _object.IsConnected(@signal, @callable);
	}

	public bool HasConnections(Godot.StringName @signal)
	{
		return _object.HasConnections(@signal);
	}

	public void SetBlockSignals(bool @enable)
	{
		_object.SetBlockSignals(@enable);
	}

	public bool IsBlockingSignals()
	{
		return _object.IsBlockingSignals();
	}

	public void NotifyPropertyListChanged()
	{
		_object.NotifyPropertyListChanged();
	}

	public void SetMessageTranslation(bool @enable)
	{
		_object.SetMessageTranslation(@enable);
	}

	public bool CanTranslateMessages()
	{
		return _object.CanTranslateMessages();
	}

	public string Tr(Godot.StringName @message, Godot.StringName @context = null)
	{
		@context ??= "";
		return _object.Tr(@message, @context);
	}

	public string TrN(Godot.StringName @message, Godot.StringName @plural_message, int @n, Godot.StringName @context = null)
	{
		@context ??= "";
		return _object.TrN(@message, @plural_message, @n, @context);
	}

	public Godot.StringName GetTranslationDomain()
	{
		return _object.GetTranslationDomain();
	}

	public void SetTranslationDomain(Godot.StringName @domain)
	{
		_object.SetTranslationDomain(@domain);
	}

	public bool IsQueuedForDeletion()
	{
		return _object.IsQueuedForDeletion();
	}

	public void CancelFree()
	{
		_object.CancelFree();
	}

	#endregion

	#region Inherited Signals

	public event Action ScriptChangedEvent
	{
		add
		{
			Connect(SignalName.ScriptChanged, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.ScriptChanged, Callable.From(value));
		}
	}

	public event Action PropertyListChangedEvent
	{
		add
		{
			Connect(SignalName.PropertyListChanged, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.PropertyListChanged, Callable.From(value));
		}
	}

	#endregion
}
