// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;
using Object = Godot.GodotObject;

namespace GDExtensionBindgen;

public class SteamPeerConfig
{
	// Engine object used for calling engine methods
	protected RefCounted _object;

	public SteamPeerConfig() : this(NativeName)
	{
	}
	protected SteamPeerConfig(StringName @class) : this(ClassDB.Instantiate(@class))
	{
	}
	protected SteamPeerConfig(Variant variant) : this((RefCounted) variant)
	{
	}
	protected SteamPeerConfig([NotNull] RefCounted @object)
	{
		_object = @object;
	}

	public static implicit operator RefCounted(SteamPeerConfig self) => self?._object;
	public static implicit operator Variant(SteamPeerConfig self) => self?._object;
	public static explicit operator SteamPeerConfig(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public class PropertyName : RefCounted.PropertyName
	{
		public static readonly StringName Options = "options";
	}

	public class MethodName : RefCounted.MethodName
	{
		public static readonly StringName SetOptions = "set_options";
		public static readonly StringName GetOptions = "get_options";
		public static readonly StringName SetConfig = "set_config";
		public static readonly StringName ClearConfig = "clear_config";
		public static readonly StringName ClearAllConfigs = "clear_all_configs";
	}

	public class SignalName : RefCounted.SignalName
	{

	}

	private static readonly StringName NativeName = "SteamPeerConfig";

	#region Enums

	public enum SteamNetworkingConfig : long
	{
		NetworkingConfigInvalid = 0L,
		NetworkingConfigFakePacketLossSend = 2L,
		NetworkingConfigFakePacketLossRecv = 3L,
		NetworkingConfigFakePacketLagSend = 4L,
		NetworkingConfigFakePacketLagRecv = 5L,
		NetworkingConfigFakePacketReorderSend = 6L,
		NetworkingConfigFakePacketReorderRecv = 7L,
		NetworkingConfigFakePacketReorderTime = 8L,
		NetworkingConfigFakePacketDupSend = 26L,
		NetworkingConfigFakePacketDupRevc = 27L,
		NetworkingConfigFakePacketDupTimeMax = 28L,
		NetworkingConfigPacketTraceMaxBytes = 41L,
		NetworkingConfigFakeRateLimitSendRate = 42L,
		NetworkingConfigFakeRateLimitSendBurst = 43L,
		NetworkingConfigFakeRateLimitRecvRate = 44L,
		NetworkingConfigFakeRateLimitRecvBurst = 45L,
		NetworkingConfigOutOfOrderCorrectionWindowMicroseconds = 51L,
		NetworkingConfigConnectionUserData = 40L,
		NetworkingConfigTimeoutInitial = 24L,
		NetworkingConfigTimeoutConnected = 25L,
		NetworkingConfigSendBufferSize = 9L,
		NetworkingConfigRecvBufferSize = 47L,
		NetworkingConfigRecvBufferMessages = 48L,
		NetworkingConfigRecvMaxMessageSize = 49L,
		NetworkingConfigRecvMaxSegmentsPerPacket = 50L,
		NetworkingConfigSendRateMin = 10L,
		NetworkingConfigSendRateMax = 11L,
		NetworkingConfigNagleTime = 12L,
		NetworkingConfigIpAllowWithoutAuth = 23L,
		NetworkingConfigIpLocalHostAllowWithoutAuth = 52L,
		NetworkingConfigMtuPacketSize = 32L,
		NetworkingConfigMtuDataSize = 33L,
		NetworkingConfigUnencrypted = 34L,
		NetworkingConfigSymmetricConnect = 37L,
		NetworkingConfigLocalVirtualPort = 38L,
		NetworkingConfigDualWifiEnable = 39L,
		NetworkingConfigEnableDiagnosticsUi = 46L,
		NetworkingConfigSdrClientConsecPingTimeoutFailInitial = 19L,
		NetworkingConfigSdrClientConsecPingTimeoutFail = 20L,
		NetworkingConfigSdrClientMinPingsBeforePingAccurate = 21L,
		NetworkingConfigSdrClientSingleSocket = 22L,
		NetworkingConfigSdrClientForceRelayCluster = 29L,
		NetworkingConfigSdrClientDevTicket = 30L,
		NetworkingConfigSdrClientForceProxyAddr = 31L,
		NetworkingConfigSdrClientFakeClusterPing = 36L,
		NetworkingConfigSdrClientLimitPingProbesToNearestN = 60L,
		NetworkingConfigLogLevelAckRtt = 13L,
		NetworkingConfigLogLevelPacketDecode = 14L,
		NetworkingConfigLogLevelMessage = 15L,
		NetworkingConfigLogLevelPacketGaps = 16L,
		NetworkingConfigLogLevelP2pRendezvous = 17L,
		NetworkingConfigLogLevelSrdRelayPings = 18L,
		NetworkingConfigCallbackConnectionStatusChanged = 201L,
		NetworkingConfigCallbackAuthStatusChanged = 202L,
		NetworkingConfigCallbackRelayNetworkStatusChanged = 203L,
		NetworkingConfigCallbackMessageSessionRequest = 204L,
		NetworkingConfigCallbackMessagesSessionFailed = 205L,
		NetworkingConfigCallbackCreateConnectionSignaling = 206L,
		NetworkingConfigCallbackFakeIpResult = 207L,
		NetworkingConfigP2pStunServerList = 103L,
		NetworkingConfigP2pTransportIceEnable = 104L,
		NetworkingConfigP2pTransportIcePenalty = 105L,
		NetworkingConfigP2pTransportSdrPenalty = 106L,
		NetworkingConfigP2pTurnServerList = 107L,
		NetworkingConfigP2pTurnUserList = 108L,
		NetworkingConfigP2pTurnPassList = 109L,
		NetworkingConfigP2pTransportIceImplementation = 110L,
		NetworkingConfigEcn = 999L,
		NetworkingConfigValueForce32bit = 2147483647L,
	}

	#endregion

	#region Properties

	public Godot.Collections.Dictionary Options
	{
		get => (Godot.Collections.Dictionary)_object.Get(PropertyName.Options);
		set => _object.Set(PropertyName.Options, value);
	}

	#endregion

	#region Methods

	public void SetOptions(Godot.Collections.Dictionary @options)
	{
		_object.Call(MethodName.SetOptions, @options);
	}

	public Godot.Collections.Dictionary GetOptions()
	{
		return (Godot.Collections.Dictionary)_object.Call(MethodName.GetOptions);
	}

	public void SetConfig(SteamPeerConfig.SteamNetworkingConfig @steam_networking_config, Variant @value)
	{
		_object.Call(MethodName.SetConfig, (int)@steam_networking_config, @value);
	}

	public void ClearConfig(SteamPeerConfig.SteamNetworkingConfig @steam_networking_config)
	{
		_object.Call(MethodName.ClearConfig, (int)@steam_networking_config);
	}

	public void ClearAllConfigs()
	{
		_object.Call(MethodName.ClearAllConfigs);
	}

	#endregion

	#region Inherited Methods

	public bool InitRef()
	{
		return _object.InitRef();
	}

	public bool Reference()
	{
		return _object.Reference();
	}

	public bool Unreference()
	{
		return _object.Unreference();
	}

	public int GetReferenceCount()
	{
		return _object.GetReferenceCount();
	}

	public void Free()
	{
		_object.Free();
	}

	public string GetClass()
	{
		return _object.GetClass();
	}

	public bool IsClass(string @class)
	{
		return _object.IsClass(@class);
	}

	public void Set(Godot.StringName @property, Variant @value)
	{
		_object.Set(@property, @value);
	}

	public Variant Get(Godot.StringName @property)
	{
		return _object.Get(@property);
	}

	public void SetIndexed(Godot.NodePath @property_path, Variant @value)
	{
		_object.SetIndexed(@property_path, @value);
	}

	public Variant GetIndexed(Godot.NodePath @property_path)
	{
		return _object.GetIndexed(@property_path);
	}

	public Godot.Collections.Array<Godot.Collections.Dictionary> GetPropertyList()
	{
		return _object.GetPropertyList();
	}

	public Godot.Collections.Array<Godot.Collections.Dictionary> GetMethodList()
	{
		return _object.GetMethodList();
	}

	public bool PropertyCanRevert(Godot.StringName @property)
	{
		return _object.PropertyCanRevert(@property);
	}

	public Variant PropertyGetRevert(Godot.StringName @property)
	{
		return _object.PropertyGetRevert(@property);
	}

	public void Notification(int @what, bool @reversed = false)
	{
		_object.Notification(@what, @reversed);
	}

	public override string ToString()
	{
		return _object.ToString();
	}

	public ulong GetInstanceId()
	{
		return _object.GetInstanceId();
	}

	public void SetScript(Variant @script)
	{
		_object.SetScript(@script);
	}

	public Variant GetScript()
	{
		return _object.GetScript();
	}

	public void SetMeta(Godot.StringName @name, Variant @value)
	{
		_object.SetMeta(@name, @value);
	}

	public void RemoveMeta(Godot.StringName @name)
	{
		_object.RemoveMeta(@name);
	}

	public Variant GetMeta(Godot.StringName @name, Variant @default = default)
	{
		return _object.GetMeta(@name, @default);
	}

	public bool HasMeta(Godot.StringName @name)
	{
		return _object.HasMeta(@name);
	}

	public Godot.Collections.Array<StringName> GetMetaList()
	{
		return _object.GetMetaList();
	}

	public void AddUserSignal(string @signal, Godot.Collections.Array @arguments = null)
	{
		@arguments ??= new();
		_object.AddUserSignal(@signal, @arguments);
	}

	public bool HasUserSignal(Godot.StringName @signal)
	{
		return _object.HasUserSignal(@signal);
	}

	public void RemoveUserSignal(Godot.StringName @signal)
	{
		_object.RemoveUserSignal(@signal);
	}

	public Godot.Error EmitSignal(Godot.StringName @signal, params Variant[] varargs)
	{
		return _object.EmitSignal(@signal, varargs);
	}

	public Variant Call(Godot.StringName @method, params Variant[] varargs)
	{
		return _object.Call(@method, varargs);
	}

	public Variant CallDeferred(Godot.StringName @method, params Variant[] varargs)
	{
		return _object.CallDeferred(@method, varargs);
	}

	public void SetDeferred(Godot.StringName @property, Variant @value)
	{
		_object.SetDeferred(@property, @value);
	}

	public Variant Callv(Godot.StringName @method, Godot.Collections.Array @arg_array)
	{
		return _object.Callv(@method, @arg_array);
	}

	public bool HasMethod(Godot.StringName @method)
	{
		return _object.HasMethod(@method);
	}

	public int GetMethodArgumentCount(Godot.StringName @method)
	{
		return _object.GetMethodArgumentCount(@method);
	}

	public bool HasSignal(Godot.StringName @signal)
	{
		return _object.HasSignal(@signal);
	}

	public Godot.Collections.Array<Godot.Collections.Dictionary> GetSignalList()
	{
		return _object.GetSignalList();
	}

	public Godot.Collections.Array<Godot.Collections.Dictionary> GetSignalConnectionList(Godot.StringName @signal)
	{
		return _object.GetSignalConnectionList(@signal);
	}

	public Godot.Collections.Array<Godot.Collections.Dictionary> GetIncomingConnections()
	{
		return _object.GetIncomingConnections();
	}

	public Godot.Error Connect(Godot.StringName @signal, Godot.Callable @callable, uint @flags = (uint)0)
	{
		return _object.Connect(@signal, @callable, @flags);
	}

	public void Disconnect(Godot.StringName @signal, Godot.Callable @callable)
	{
		_object.Disconnect(@signal, @callable);
	}

	public bool IsConnected(Godot.StringName @signal, Godot.Callable @callable)
	{
		return _object.IsConnected(@signal, @callable);
	}

	public bool HasConnections(Godot.StringName @signal)
	{
		return _object.HasConnections(@signal);
	}

	public void SetBlockSignals(bool @enable)
	{
		_object.SetBlockSignals(@enable);
	}

	public bool IsBlockingSignals()
	{
		return _object.IsBlockingSignals();
	}

	public void NotifyPropertyListChanged()
	{
		_object.NotifyPropertyListChanged();
	}

	public void SetMessageTranslation(bool @enable)
	{
		_object.SetMessageTranslation(@enable);
	}

	public bool CanTranslateMessages()
	{
		return _object.CanTranslateMessages();
	}

	public string Tr(Godot.StringName @message, Godot.StringName @context = null)
	{
		@context ??= "";
		return _object.Tr(@message, @context);
	}

	public string TrN(Godot.StringName @message, Godot.StringName @plural_message, int @n, Godot.StringName @context = null)
	{
		@context ??= "";
		return _object.TrN(@message, @plural_message, @n, @context);
	}

	public Godot.StringName GetTranslationDomain()
	{
		return _object.GetTranslationDomain();
	}

	public void SetTranslationDomain(Godot.StringName @domain)
	{
		_object.SetTranslationDomain(@domain);
	}

	public bool IsQueuedForDeletion()
	{
		return _object.IsQueuedForDeletion();
	}

	public void CancelFree()
	{
		_object.CancelFree();
	}

	#endregion

	#region Inherited Signals

	public event Action ScriptChangedEvent
	{
		add
		{
			Connect(SignalName.ScriptChanged, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.ScriptChanged, Callable.From(value));
		}
	}

	public event Action PropertyListChangedEvent
	{
		add
		{
			Connect(SignalName.PropertyListChanged, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.PropertyListChanged, Callable.From(value));
		}
	}

	#endregion
}
