// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;
using Object = Godot.GodotObject;

namespace GDExtensionBindgen;

public class SteamMultiplayerPeer
{
	// Engine object used for calling engine methods
	protected MultiplayerPeerExtension _object;

	public SteamMultiplayerPeer() : this(NativeName)
	{
	}
	protected SteamMultiplayerPeer(StringName @class) : this(ClassDB.Instantiate(@class))
	{
	}
	protected SteamMultiplayerPeer(Variant variant) : this((MultiplayerPeerExtension) variant)
	{
	}
	protected SteamMultiplayerPeer([NotNull] MultiplayerPeerExtension @object)
	{
		_object = @object;
	}

	public static implicit operator MultiplayerPeerExtension(SteamMultiplayerPeer self) => self?._object;
	public static implicit operator Variant(SteamMultiplayerPeer self) => self?._object;
	public static explicit operator SteamMultiplayerPeer(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public class PropertyName : MultiplayerPeerExtension.PropertyName
	{
		public static readonly StringName ListenSocket = "listen_socket";
		public static readonly StringName NoNagle = "no_nagle";
		public static readonly StringName NoDelay = "no_delay";
		public static readonly StringName Configs = "configs";
	}

	public class MethodName : MultiplayerPeerExtension.MethodName
	{
		public static readonly StringName CreateHost = "create_host";
		public static readonly StringName CreateClient = "create_client";
		public static readonly StringName SetListenSocket = "set_listen_socket";
		public static readonly StringName GetListenSocket = "get_listen_socket";
		public static readonly StringName GetSteam64FromPeerId = "get_steam64_from_peer_id";
		public static readonly StringName GetPeerIdFromSteam64 = "get_peer_id_from_steam64";
		public static readonly StringName SetNoNagle = "set_no_nagle";
		public static readonly StringName GetNoNagle = "get_no_nagle";
		public static readonly StringName SetNoDelay = "set_no_delay";
		public static readonly StringName GetNoDelay = "get_no_delay";
		public static readonly StringName SetConfigs = "set_configs";
		public static readonly StringName GetConfigs = "get_configs";
		public static readonly StringName SetConfig = "set_config";
		public static readonly StringName ClearConfig = "clear_config";
		public static readonly StringName ClearAllConfigs = "clear_all_configs";
	}

	public class SignalName : MultiplayerPeerExtension.SignalName
	{
		public static readonly StringName NetworkConnectionStatusChanged = "network_connection_status_changed";
	}

	private static readonly StringName NativeName = "SteamMultiplayerPeer";

	#region Properties

	public int ListenSocket
	{
		get => (int)_object.Get(PropertyName.ListenSocket);
		set => _object.Set(PropertyName.ListenSocket, value);
	}

	public bool NoNagle
	{
		get => (bool)_object.Get(PropertyName.NoNagle);
		set => _object.Set(PropertyName.NoNagle, value);
	}

	public bool NoDelay
	{
		get => (bool)_object.Get(PropertyName.NoDelay);
		set => _object.Set(PropertyName.NoDelay, value);
	}

	public GodotObject Configs
	{
		get => (GodotObject)_object.Get(PropertyName.Configs);
		set => _object.Set(PropertyName.Configs, value);
	}

	#endregion

	#region Inherited Properties

	public bool RefuseNewConnections
	{
		get => _object.RefuseNewConnections;
		set => _object.RefuseNewConnections = value;
	}

	public int TransferMode
	{
		get => _object.TransferMode;
		set => _object.TransferMode = value;
	}

	public int TransferChannel
	{
		get => _object.TransferChannel;
		set => _object.TransferChannel = value;
	}

	public int EncodeBufferMaxSize
	{
		get => _object.EncodeBufferMaxSize;
		set => _object.EncodeBufferMaxSize = value;
	}

	#endregion

	#region Methods

	public Godot.Error CreateHost(int @n_local_virtual_port = default)
	{
		return (Godot.Error)(int)_object.Call(MethodName.CreateHost, @n_local_virtual_port);
	}

	public Godot.Error CreateClient(int @identity_remote, int @n_local_virtual_port = default)
	{
		return (Godot.Error)(int)_object.Call(MethodName.CreateClient, @identity_remote, @n_local_virtual_port);
	}

	public void SetListenSocket(int @listen_socket)
	{
		_object.Call(MethodName.SetListenSocket, @listen_socket);
	}

	public int GetListenSocket()
	{
		return (int)_object.Call(MethodName.GetListenSocket);
	}

	public int GetSteam64FromPeerId(int @peer_id)
	{
		return (int)_object.Call(MethodName.GetSteam64FromPeerId, @peer_id);
	}

	public int GetPeerIdFromSteam64(int @steamid)
	{
		return (int)_object.Call(MethodName.GetPeerIdFromSteam64, @steamid);
	}

	public void SetNoNagle(bool @no_nagle)
	{
		_object.Call(MethodName.SetNoNagle, @no_nagle);
	}

	public bool GetNoNagle()
	{
		return (bool)_object.Call(MethodName.GetNoNagle);
	}

	public void SetNoDelay(bool @no_delay)
	{
		_object.Call(MethodName.SetNoDelay, @no_delay);
	}

	public bool GetNoDelay()
	{
		return (bool)_object.Call(MethodName.GetNoDelay);
	}

	public void SetConfigs(SteamPeerConfig @configs)
	{
		_object.Call(MethodName.SetConfigs, @configs);
	}

	public SteamPeerConfig GetConfigs()
	{
		return (SteamPeerConfig)_object.Call(MethodName.GetConfigs);
	}

	public void SetConfig(SteamPeerConfig.SteamNetworkingConfig @config, Variant @value)
	{
		_object.Call(MethodName.SetConfig, (int)@config, @value);
	}

	public void ClearConfig(SteamPeerConfig.SteamNetworkingConfig @config)
	{
		_object.Call(MethodName.ClearConfig, (int)@config);
	}

	public void ClearAllConfigs()
	{
		_object.Call(MethodName.ClearAllConfigs);
	}

	#endregion

	#region Inherited Methods

	public void SetTransferChannel(int @channel)
	{
		_object.SetTransferChannel(@channel);
	}

	public int GetTransferChannel()
	{
		return _object.GetTransferChannel();
	}

	public void SetTransferMode(MultiplayerPeer.TransferModeEnum @mode)
	{
		_object.SetTransferMode((int)@mode);
	}

	public MultiplayerPeer.TransferModeEnum GetTransferMode()
	{
		return _object.GetTransferMode();
	}

	public void SetTargetPeer(int @id)
	{
		_object.SetTargetPeer(@id);
	}

	public int GetPacketPeer()
	{
		return _object.GetPacketPeer();
	}

	public int GetPacketChannel()
	{
		return _object.GetPacketChannel();
	}

	public MultiplayerPeer.TransferModeEnum GetPacketMode()
	{
		return _object.GetPacketMode();
	}

	public void Poll()
	{
		_object.Poll();
	}

	public void Close()
	{
		_object.Close();
	}

	public void DisconnectPeer(int @peer, bool @force = false)
	{
		_object.DisconnectPeer(@peer, @force);
	}

	public MultiplayerPeer.ConnectionStatus GetConnectionStatus()
	{
		return _object.GetConnectionStatus();
	}

	public int GetUniqueId()
	{
		return _object.GetUniqueId();
	}

	public int GenerateUniqueId()
	{
		return _object.GenerateUniqueId();
	}

	public void SetRefuseNewConnections(bool @enable)
	{
		_object.SetRefuseNewConnections(@enable);
	}

	public bool IsRefusingNewConnections()
	{
		return _object.IsRefusingNewConnections();
	}

	public bool IsServerRelaySupported()
	{
		return _object.IsServerRelaySupported();
	}

	public Variant GetVar(bool @allow_objects = false)
	{
		return _object.GetVar(@allow_objects);
	}

	public Godot.Error PutVar(Variant @var, bool @full_objects = false)
	{
		return _object.PutVar(@var, @full_objects);
	}

	public byte[] GetPacket()
	{
		return _object.GetPacket();
	}

	public Godot.Error PutPacket(byte[] @buffer)
	{
		return _object.PutPacket(@buffer);
	}

	public Godot.Error GetPacketError()
	{
		return _object.GetPacketError();
	}

	public int GetAvailablePacketCount()
	{
		return _object.GetAvailablePacketCount();
	}

	public int GetEncodeBufferMaxSize()
	{
		return _object.GetEncodeBufferMaxSize();
	}

	public void SetEncodeBufferMaxSize(int @max_size)
	{
		_object.SetEncodeBufferMaxSize(@max_size);
	}

	public bool InitRef()
	{
		return _object.InitRef();
	}

	public bool Reference()
	{
		return _object.Reference();
	}

	public bool Unreference()
	{
		return _object.Unreference();
	}

	public int GetReferenceCount()
	{
		return _object.GetReferenceCount();
	}

	public void Free()
	{
		_object.Free();
	}

	public string GetClass()
	{
		return _object.GetClass();
	}

	public bool IsClass(string @class)
	{
		return _object.IsClass(@class);
	}

	public void Set(Godot.StringName @property, Variant @value)
	{
		_object.Set(@property, @value);
	}

	public Variant Get(Godot.StringName @property)
	{
		return _object.Get(@property);
	}

	public void SetIndexed(Godot.NodePath @property_path, Variant @value)
	{
		_object.SetIndexed(@property_path, @value);
	}

	public Variant GetIndexed(Godot.NodePath @property_path)
	{
		return _object.GetIndexed(@property_path);
	}

	public Godot.Collections.Array<Godot.Collections.Dictionary> GetPropertyList()
	{
		return _object.GetPropertyList();
	}

	public Godot.Collections.Array<Godot.Collections.Dictionary> GetMethodList()
	{
		return _object.GetMethodList();
	}

	public bool PropertyCanRevert(Godot.StringName @property)
	{
		return _object.PropertyCanRevert(@property);
	}

	public Variant PropertyGetRevert(Godot.StringName @property)
	{
		return _object.PropertyGetRevert(@property);
	}

	public void Notification(int @what, bool @reversed = false)
	{
		_object.Notification(@what, @reversed);
	}

	public override string ToString()
	{
		return _object.ToString();
	}

	public ulong GetInstanceId()
	{
		return _object.GetInstanceId();
	}

	public void SetScript(Variant @script)
	{
		_object.SetScript(@script);
	}

	public Variant GetScript()
	{
		return _object.GetScript();
	}

	public void SetMeta(Godot.StringName @name, Variant @value)
	{
		_object.SetMeta(@name, @value);
	}

	public void RemoveMeta(Godot.StringName @name)
	{
		_object.RemoveMeta(@name);
	}

	public Variant GetMeta(Godot.StringName @name, Variant @default = default)
	{
		return _object.GetMeta(@name, @default);
	}

	public bool HasMeta(Godot.StringName @name)
	{
		return _object.HasMeta(@name);
	}

	public Godot.Collections.Array<StringName> GetMetaList()
	{
		return _object.GetMetaList();
	}

	public void AddUserSignal(string @signal, Godot.Collections.Array @arguments = null)
	{
		@arguments ??= new();
		_object.AddUserSignal(@signal, @arguments);
	}

	public bool HasUserSignal(Godot.StringName @signal)
	{
		return _object.HasUserSignal(@signal);
	}

	public void RemoveUserSignal(Godot.StringName @signal)
	{
		_object.RemoveUserSignal(@signal);
	}

	public Godot.Error EmitSignal(Godot.StringName @signal, params Variant[] varargs)
	{
		return _object.EmitSignal(@signal, varargs);
	}

	public Variant Call(Godot.StringName @method, params Variant[] varargs)
	{
		return _object.Call(@method, varargs);
	}

	public Variant CallDeferred(Godot.StringName @method, params Variant[] varargs)
	{
		return _object.CallDeferred(@method, varargs);
	}

	public void SetDeferred(Godot.StringName @property, Variant @value)
	{
		_object.SetDeferred(@property, @value);
	}

	public Variant Callv(Godot.StringName @method, Godot.Collections.Array @arg_array)
	{
		return _object.Callv(@method, @arg_array);
	}

	public bool HasMethod(Godot.StringName @method)
	{
		return _object.HasMethod(@method);
	}

	public int GetMethodArgumentCount(Godot.StringName @method)
	{
		return _object.GetMethodArgumentCount(@method);
	}

	public bool HasSignal(Godot.StringName @signal)
	{
		return _object.HasSignal(@signal);
	}

	public Godot.Collections.Array<Godot.Collections.Dictionary> GetSignalList()
	{
		return _object.GetSignalList();
	}

	public Godot.Collections.Array<Godot.Collections.Dictionary> GetSignalConnectionList(Godot.StringName @signal)
	{
		return _object.GetSignalConnectionList(@signal);
	}

	public Godot.Collections.Array<Godot.Collections.Dictionary> GetIncomingConnections()
	{
		return _object.GetIncomingConnections();
	}

	public Godot.Error Connect(Godot.StringName @signal, Godot.Callable @callable, uint @flags = (uint)0)
	{
		return _object.Connect(@signal, @callable, @flags);
	}

	public void Disconnect(Godot.StringName @signal, Godot.Callable @callable)
	{
		_object.Disconnect(@signal, @callable);
	}

	public bool IsConnected(Godot.StringName @signal, Godot.Callable @callable)
	{
		return _object.IsConnected(@signal, @callable);
	}

	public bool HasConnections(Godot.StringName @signal)
	{
		return _object.HasConnections(@signal);
	}

	public void SetBlockSignals(bool @enable)
	{
		_object.SetBlockSignals(@enable);
	}

	public bool IsBlockingSignals()
	{
		return _object.IsBlockingSignals();
	}

	public void NotifyPropertyListChanged()
	{
		_object.NotifyPropertyListChanged();
	}

	public void SetMessageTranslation(bool @enable)
	{
		_object.SetMessageTranslation(@enable);
	}

	public bool CanTranslateMessages()
	{
		return _object.CanTranslateMessages();
	}

	public string Tr(Godot.StringName @message, Godot.StringName @context = null)
	{
		@context ??= "";
		return _object.Tr(@message, @context);
	}

	public string TrN(Godot.StringName @message, Godot.StringName @plural_message, int @n, Godot.StringName @context = null)
	{
		@context ??= "";
		return _object.TrN(@message, @plural_message, @n, @context);
	}

	public Godot.StringName GetTranslationDomain()
	{
		return _object.GetTranslationDomain();
	}

	public void SetTranslationDomain(Godot.StringName @domain)
	{
		_object.SetTranslationDomain(@domain);
	}

	public bool IsQueuedForDeletion()
	{
		return _object.IsQueuedForDeletion();
	}

	public void CancelFree()
	{
		_object.CancelFree();
	}

	#endregion

	#region Signals

	public event Action<int, Godot.Collections.Dictionary, int> NetworkConnectionStatusChangedEvent
	{
		add
		{
			Connect(SignalName.NetworkConnectionStatusChanged, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.NetworkConnectionStatusChanged, Callable.From(value));
		}
	}

	#endregion

	#region Inherited Signals

	public event Action<int> PeerConnectedEvent
	{
		add
		{
			Connect(SignalName.PeerConnected, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.PeerConnected, Callable.From(value));
		}
	}

	public event Action<int> PeerDisconnectedEvent
	{
		add
		{
			Connect(SignalName.PeerDisconnected, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.PeerDisconnected, Callable.From(value));
		}
	}

	public event Action ScriptChangedEvent
	{
		add
		{
			Connect(SignalName.ScriptChanged, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.ScriptChanged, Callable.From(value));
		}
	}

	public event Action PropertyListChangedEvent
	{
		add
		{
			Connect(SignalName.PropertyListChanged, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.PropertyListChanged, Callable.From(value));
		}
	}

	#endregion
}
